[versions]
agp = "9.4.0"
kotlin = "2.4.10"
appcompat = "1.7.1"
core = "1.17.0"
playServicesAds = "25.5.0"
ump = "4.0.0"
junit = "4.13.2"
orgJson = "20250517"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
ump = { module = "com.google.android.ump:user-messaging-platform", version.ref = "ump" }
junit = { module = "junit:junit", version.ref = "junit" }
org-json = { module = "org.json:json", version.ref = "orgJson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
