"""School-style formats (descriptive label only; no claim to mirror any official exam)."""
from lib import PR, ST, M

# ---- Pronunciation: odd one first; [ ] marks the underlined letters.
PR(["want[ed]", "play[ed]", "clean[ed]", "open[ed]"], "wanted đọc /ɪd/ (sau t); các từ còn lại đọc /d/.")
PR(["walk[ed]", "need[ed]", "decid[ed]", "start[ed]"], "walked đọc /t/ (sau âm vô thanh /k/); các từ còn lại đọc /ɪd/.")
PR(["stay[ed]", "watch[ed]", "kiss[ed]", "laugh[ed]"], "stayed đọc /d/; các từ còn lại đọc /t/.")
PR(["visit[ed]", "help[ed]", "look[ed]", "stopp[ed]"], "visited đọc /ɪd/; các từ còn lại đọc /t/.")
PR(["finish[ed]", "rain[ed]", "travel[ed]", "call[ed]"], "finished đọc /t/ (sau /ʃ/); các từ còn lại đọc /d/.")
PR(["invit[ed]", "lov[ed]", "arriv[ed]", "smil[ed]"], "invited đọc /ɪd/; các từ còn lại đọc /d/.")
PR(["mix[ed]", "mov[ed]", "answer[ed]", "show[ed]"], "mixed đọc /t/ (x = /ks/); các từ còn lại đọc /d/.")
PR(["plann[ed]", "hop[ed]", "cook[ed]", "dress[ed]"], "planned đọc /d/; các từ còn lại đọc /t/.")
PR(["watch[es]", "book[s]", "cat[s]", "stop[s]"], "watches đọc /ɪz/; các từ còn lại đọc /s/.")
PR(["bag[s]", "map[s]", "desk[s]", "laugh[s]"], "bags đọc /z/; các từ còn lại đọc /s/.")
PR(["book[s]", "pen[s]", "dog[s]", "chair[s]"], "books đọc /s/; các từ còn lại đọc /z/.")
PR(["box[es]", "play[s]", "song[s]", "friend[s]"], "boxes đọc /ɪz/; các từ còn lại đọc /z/.")
PR(["month[s]", "bed[s]", "car[s]", "tree[s]"], "months đọc /s/ (sau /θ/); các từ còn lại đọc /z/.")
PR(["bridg[es]", "cake[s]", "shop[s]", "street[s]"], "bridges đọc /ɪz/; các từ còn lại đọc /s/.")
PR(["h[ea]d", "m[ea]t", "s[ea]t", "t[ea]ch"], "head đọc /e/; các từ còn lại đọc /iː/.")
PR(["b[oo]k", "f[oo]d", "m[oo]n", "s[oo]n"], "book đọc /ʊ/; các từ còn lại đọc /uː/.")
PR(["c[a]ke", "c[a]t", "h[a]t", "m[a]p"], "cake đọc /eɪ/; các từ còn lại đọc /æ/.", level=1)
PR(["l[i]ke", "s[i]t", "b[i]g", "f[i]sh"], "like đọc /aɪ/; các từ còn lại đọc /ɪ/.", level=1)
PR(["[ch]aracter", "[ch]air", "[ch]eap", "[ch]ild"], "character đọc /k/; các từ còn lại đọc /tʃ/.")
PR(["[h]our", "[h]ouse", "[h]appy", "[h]old"], "hour có h câm; các từ còn lại đọc /h/.")
PR(["c[o]me", "h[o]me", "n[o]te", "ph[o]ne"], "come đọc /ʌ/; các từ còn lại đọc /oʊ/.")
PR(["[th]ink", "[th]is", "[th]ey", "[th]ere"], "think đọc /θ/; các từ còn lại đọc /ð/.")
PR(["[s]ure", "[s]un", "[s]ee", "[s]ummer"], "sure đọc /ʃ/; các từ còn lại đọc /s/.")
PR(["w[o]man", "w[o]n", "w[o]nder", "c[o]lor"], "woman đọc /ʊ/; các từ còn lại đọc /ʌ/.", level=3)
PR(["br[ea]kfast", "br[ea]k", "gr[ea]t", "st[ea]k"], "breakfast đọc /e/; các từ còn lại đọc /eɪ/.", level=3)
PR(["c[ou]ntry", "h[ou]se", "m[ou]th", "s[ou]th"], "country đọc /ʌ/; các từ còn lại đọc /aʊ/.", level=3)

# ---- Word stress: the word whose stress position differs comes first.
ST(["begin", "happy", "table", "money"], "begin nhấn âm 2; các từ còn lại nhấn âm 1.", level=1)
ST(["teacher", "decide", "arrive", "explain"], "teacher nhấn âm 1; các từ còn lại nhấn âm 2.", level=1)
ST(["hotel", "doctor", "student", "picture"], "hotel nhấn âm 2; các từ còn lại nhấn âm 1.")
ST(["computer", "family", "beautiful", "holiday"], "computer nhấn âm 2; các từ còn lại nhấn âm 1.")
ST(["important", "interview", "telephone", "festival"], "important nhấn âm 2; các từ còn lại nhấn âm 1.")
ST(["engineer", "company", "different", "camera"], "engineer nhấn âm 3 (đuôi -eer nhận trọng âm); các từ còn lại nhấn âm 1.", level=3)
ST(["information", "geography", "photography", "biology"], "information nhấn âm 3 (ngay trước -tion); các từ còn lại nhấn âm 2.", level=3)
ST(["economic", "economy", "ecology", "efficient"], "economic nhấn âm 3 (ngay trước -ic); các từ còn lại nhấn âm 2.", level=4)
ST(["visit", "enjoy", "invite", "repeat"], "visit nhấn âm 1; các động từ còn lại nhấn âm 2.")
ST(["polite", "garden", "window", "busy"], "polite nhấn âm 2; các từ còn lại nhấn âm 1.")
ST(["advertise", "advantage", "attractive", "achievement"], "advertise nhấn âm 1; các từ còn lại nhấn âm 2.", level=4)
ST(["volunteer", "musician", "position", "relation"], "volunteer nhấn âm 3; các từ còn lại nhấn âm 2 (ngay trước -ian/-tion).", level=3)
ST(["comfortable", "material", "particular", "experience"], "comfortable nhấn âm 1; các từ còn lại nhấn âm 2.", level=4)
ST(["population", "community", "activity", "ability"], "population nhấn âm 3; các từ còn lại nhấn âm 2 (ngay trước -ity).", level=3)
ST(["answer", "agree", "become", "forget"], "answer nhấn âm 1; các từ còn lại nhấn âm 2.")
ST(["Japanese", "Japan", "machine", "result"], "Japanese nhấn âm 3 (đuôi -ese nhận trọng âm); các từ còn lại nhấn âm 2.", level=3)

# ---- Synonyms / antonyms ([ ] marks the underlined word). Correct first.
S_ = dict(fmt="school", gp=None)
M("The meeting was [postponed] until next Friday because the director was ill.", ["delayed", "canceled", "attended", "arranged"], "postpone = hoãn lại ≈ delay.", qtype="synonym", level=3, skills=["vocab_core"], **S_)
M("She is a very [generous] person who always helps others.", ["kind and giving", "selfish", "shy", "lazy"], "generous = hào phóng ≈ kind and giving.", qtype="synonym", level=3, skills=["vocab_core"], **S_)
M("It is [essential] to drink enough water every day.", ["necessary", "useless", "difficult", "possible"], "essential = thiết yếu ≈ necessary.", qtype="synonym", level=3, skills=["vocab_core"], **S_)
M("The children were [delighted] with their new toys.", ["very happy", "very angry", "bored", "worried"], "delighted = rất vui ≈ very happy.", qtype="synonym", level=3, skills=["vocab_core"], **S_)
M("He [quickly] realized that he had made a mistake.", ["soon", "slowly", "never", "hardly"], "quickly = nhanh chóng ≈ soon (trong ngữ cảnh này).", qtype="synonym", level=2, skills=["vocab_core"], **S_)
M("The old house needs to be [repaired] before winter.", ["fixed", "sold", "built", "painted"], "repair = sửa chữa ≈ fix.", qtype="synonym", level=2, skills=["vocab_core"], **S_)
M("We were [astonished] by the beautiful view from the top.", ["amazed", "bored", "scared", "confused"], "astonished = kinh ngạc ≈ amazed.", qtype="synonym", level=4, skills=["vocab_core"], **S_)
M("The company aims to [reduce] plastic waste by half.", ["cut", "increase", "produce", "collect"], "reduce = giảm ≈ cut.", qtype="synonym", level=2, skills=["vocab_core"], **S_)
M("Learning a new language requires a lot of [effort].", ["hard work", "free time", "money", "luck"], "effort = nỗ lực ≈ hard work.", qtype="synonym", level=3, skills=["vocab_core"], **S_)
M("Please [inform] us if you change your address.", ["tell", "ask", "visit", "forget"], "inform = thông báo ≈ tell.", qtype="synonym", level=3, skills=["vocab_core"], **S_)
M("The new teacher is very [patient] with young students.", ["impatient", "calm", "kind", "gentle"], "patient (kiên nhẫn) >< impatient (thiếu kiên nhẫn).", qtype="antonym", level=2, skills=["vocab_core"], **S_)
M("The weather today is extremely [hot].", ["cold", "warm", "sunny", "dry"], "hot >< cold.", qtype="antonym", level=1, skills=["vocab_core"], **S_)
M("This exercise is quite [simple].", ["complicated", "easy", "short", "clear"], "simple (đơn giản) >< complicated (phức tạp).", qtype="antonym", level=3, skills=["vocab_core"], **S_)
M("The shop was [crowded] on Saturday morning.", ["empty", "busy", "full", "noisy"], "crowded (đông) >< empty (vắng).", qtype="antonym", level=2, skills=["vocab_core"], **S_)
M("Her answer was [correct].", ["wrong", "right", "true", "exact"], "correct >< wrong.", qtype="antonym", level=1, skills=["vocab_core"], **S_)
M("The company [increased] its prices last year.", ["lowered", "raised", "changed", "kept"], "increase (tăng) >< lower (giảm).", qtype="antonym", level=2, skills=["vocab_core"], **S_)
M("He is always [polite] to his customers.", ["rude", "friendly", "kind", "helpful"], "polite (lịch sự) >< rude (thô lỗ).", qtype="antonym", level=3, skills=["vocab_core"], **S_)
M("Our team [accepted] the new proposal.", ["rejected", "approved", "discussed", "received"], "accept (chấp nhận) >< reject (từ chối).", qtype="antonym", level=3, skills=["vocab_core"], **S_)
M("The museum is [temporarily] closed for repairs.", ["permanently", "briefly", "currently", "recently"], "temporarily (tạm thời) >< permanently (vĩnh viễn).", qtype="antonym", level=4, skills=["vocab_core"], **S_)
M("She felt very [confident] before the interview.", ["nervous", "sure", "relaxed", "happy"], "confident (tự tin) >< nervous (lo lắng).", qtype="antonym", level=3, skills=["vocab_core"], **S_)
