"""Additional meanings / parts of speech for words defined in the topic files (context matters!)."""
from lib import SW

SW("interest", "n", "sự quan tâm, sở thích", "She has a strong interest in music.", "Cô ấy rất quan tâm đến âm nhạc.")
SW("interest", "v", "làm ai quan tâm", "History doesn't interest me much.", "Lịch sử không làm tôi hứng thú lắm.")
SW("balance", "n", "sự cân bằng", "Try to keep a balance between work and rest.", "Hãy cố giữ cân bằng giữa làm việc và nghỉ ngơi.")
SW("statement", "n", "lời tuyên bố, phát biểu", "The company made a statement to the press.", "Công ty đã ra tuyên bố với báo chí.")
SW("figure", "n", "dáng người; nhân vật", "She is an important figure in Vietnamese art.", "Bà ấy là một nhân vật quan trọng của nghệ thuật Việt Nam.")
SW("figure", "v", "figure out: hiểu ra", "I finally figured out how the app works.", "Cuối cùng tôi cũng hiểu ra ứng dụng hoạt động thế nào.")
SW("stock", "n", "hàng tồn kho", "We have plenty of paper in stock.", "Chúng tôi còn nhiều giấy trong kho.")
SW("branch", "n", "cành cây", "A bird is sitting on the branch.", "Một con chim đang đậu trên cành cây.")
SW("fund", "v", "cấp vốn, tài trợ", "The project is funded by the city.", "Dự án được thành phố cấp vốn.")
SW("leave", "v", "rời đi; để lại", "The bus leaves at 8.", "Xe buýt rời bến lúc 8 giờ.")
SW("party", "n", "bữa tiệc", "We're having a birthday party on Saturday.", "Chúng tôi tổ chức tiệc sinh nhật vào thứ Bảy.")
SW("party", "n", "đảng (chính trị)", "Which party won the election?", "Đảng nào thắng cuộc bầu cử?")
SW("notice", "v", "để ý, nhận thấy", "Did you notice anything strange?", "Bạn có để ý điều gì lạ không?")
SW("charge", "n", "phí; sự phụ trách", "There is no charge for children.", "Trẻ em không mất phí.")
SW("charge", "v", "sạc (pin)", "I need to charge my phone.", "Tôi cần sạc điện thoại.")
SW("deal", "v", "deal with: giải quyết", "She deals with customer complaints.", "Cô ấy giải quyết khiếu nại của khách hàng.")
SW("suit", "n", "bộ com-lê", "He wore a dark suit to the interview.", "Anh ấy mặc bộ com-lê tối màu đi phỏng vấn.")
SW("book", "n", "quyển sách", "I'm reading a book about history.", "Tôi đang đọc một cuốn sách về lịch sử.")
SW("host", "v", "dẫn chương trình", "Who is hosting the show tonight?", "Ai dẫn chương trình tối nay?")
SW("tip", "n", "mẹo, lời khuyên", "Here are five tips for learning new words.", "Đây là năm mẹo học từ mới.")
SW("track", "n", "đường chạy; bài hát (trong album)", "The third track on the album is my favorite.", "Bài thứ ba trong album là bài tôi thích nhất.")
SW("sign", "n", "biển báo; dấu hiệu", "The sign says 'No parking'.", "Biển báo ghi 'Cấm đỗ xe'.")
SW("permit", "v", "cho phép (trang trọng)", "Smoking is not permitted here.", "Không được phép hút thuốc ở đây.")
SW("target", "v", "nhắm tới", "The ad targets young parents.", "Quảng cáo nhắm tới các bậc cha mẹ trẻ.")
SW("launch", "n", "sự ra mắt", "The product launch was a big success.", "Buổi ra mắt sản phẩm rất thành công.")
SW("handle", "n", "tay cầm", "The handle of the door is broken.", "Tay nắm cửa bị hỏng.")
SW("order", "n", "trật tự, thứ tự", "Put the words in the correct order.", "Sắp xếp các từ theo đúng thứ tự.")
SW("process", "v", "xử lý", "Your order is being processed.", "Đơn hàng của bạn đang được xử lý.")
SW("demand", "v", "yêu cầu (gắt gao)", "The customers demanded a refund.", "Khách hàng đòi hoàn tiền.")
SW("survey", "v", "khảo sát", "We surveyed 300 students.", "Chúng tôi đã khảo sát 300 sinh viên.")
SW("estimate", "v", "ước tính", "We estimate that the work will take two weeks.", "Chúng tôi ước tính công việc mất hai tuần.")
SW("quote", "v", "trích dẫn; báo giá", "The article quoted the director.", "Bài báo trích lời giám đốc.")
SW("transfer", "n", "sự chuyển (tiền, công tác)", "The bank transfer takes one day.", "Việc chuyển khoản mất một ngày.")
SW("cash", "v", "đổi ra tiền mặt", "Can I cash this check here?", "Tôi có thể đổi tờ séc này ra tiền mặt ở đây không?")
SW("loan", "v", "cho vay", "He loaned me his car for the weekend.", "Anh ấy cho tôi mượn xe cuối tuần.")
SW("cost", "v", "có giá, tốn", "How much does it cost?", "Cái này giá bao nhiêu?")
SW("increase", "n", "sự tăng", "There was a sharp increase in prices.", "Giá cả tăng mạnh.")
SW("decrease", "n", "sự giảm", "We saw a small decrease in sales.", "Doanh số giảm nhẹ.")
SW("total", "adj", "tổng cộng; hoàn toàn", "The total cost is 2 million dong.", "Tổng chi phí là 2 triệu đồng.")
SW("draft", "v", "soạn thảo", "Can you draft a reply to this email?", "Bạn soạn giúp thư trả lời email này được không?")
SW("contract", "v", "co lại; nhiễm (bệnh)", "Metal contracts in the cold.", "Kim loại co lại khi lạnh.")
SW("court", "n", "sân (tennis, cầu lông)", "The tennis courts are behind the hotel.", "Sân tennis ở sau khách sạn.")
SW("license", "v", "cấp phép", "The shop is licensed to sell medicine.", "Cửa hàng được cấp phép bán thuốc.")
SW("load", "n", "khối lượng, gánh nặng", "The truck was carrying a heavy load.", "Xe tải đang chở một khối hàng nặng.")
SW("package", "n", "gói (dịch vụ)", "The hotel offers a honeymoon package.", "Khách sạn có gói trăng mật.")
SW("delay", "v", "trì hoãn", "The flight was delayed by two hours.", "Chuyến bay bị hoãn hai tiếng.")
SW("trade", "v", "buôn bán; trao đổi", "The two countries trade rice and coffee.", "Hai nước buôn bán gạo và cà phê.")
SW("sale", "n", "sự bán, doanh số (sales)", "Sales went up in December.", "Doanh số tăng trong tháng Mười Hai.")
SW("fit", "n", "độ vừa vặn", "This jacket is a perfect fit.", "Chiếc áo khoác này vừa như in.")
SW("flight", "n", "chuyến bay; sự chạy trốn", "The flight to Seoul is full.", "Chuyến bay đến Seoul đã kín chỗ.")
SW("fare", "v", "xoay sở (fare well/badly)", "How did you fare in the exam?", "Bạn làm bài thi thế nào?")
SW("guide", "v", "hướng dẫn, dẫn đường", "She guided us through the old town.", "Cô ấy dẫn chúng tôi tham quan phố cổ.")
SW("serve", "v", "phát bóng (thể thao)", "It's your turn to serve.", "Đến lượt bạn phát bóng.")
SW("dish", "n", "cái đĩa", "Put the dish in the sink.", "Để cái đĩa vào bồn rửa.")
SW("presentation", "n", "sự trình bày (cách thể hiện)", "The presentation of the food is beautiful.", "Cách bày biện món ăn rất đẹp.")
SW("award", "v", "trao giải", "She was awarded a scholarship.", "Cô ấy được trao học bổng.")
SW("register", "n", "sổ đăng ký; quầy thu tiền", "The teacher checked the class register.", "Giáo viên kiểm tra sổ điểm danh.")
SW("session", "n", "buổi (học, tập)", "Today's study session lasts 15 minutes.", "Buổi học hôm nay kéo dài 15 phút.")
SW("screen", "v", "sàng lọc; chiếu (phim)", "All applicants are screened carefully.", "Mọi ứng viên đều được sàng lọc kỹ.")
SW("virus", "n", "vi-rút máy tính", "Antivirus software protects your laptop.", "Phần mềm diệt vi-rút bảo vệ laptop của bạn.")
SW("network", "n", "mạng lưới (quan hệ)", "She has a large network of contacts.", "Cô ấy có mạng lưới quan hệ rộng.")
SW("approve", "v", "approve of: tán thành", "My parents don't approve of my new hairstyle.", "Bố mẹ tôi không tán thành kiểu tóc mới của tôi.")
SW("attend", "v", "attend to: chăm sóc, xử lý", "A nurse will attend to you shortly.", "Y tá sẽ chăm sóc bạn ngay.")
SW("assign", "v", "chỉ định (chỗ, vị trí)", "Each student is assigned a seat.", "Mỗi học sinh được xếp một chỗ ngồi.")
SW("memo", "n", "ghi chú (memo trên điện thoại)", "I recorded a voice memo.", "Tôi đã ghi âm một ghi chú bằng giọng nói.")
SW("office", "n", "chức vụ, nhiệm kỳ", "The president took office in 2021.", "Tổng thống nhậm chức năm 2021.")
SW("position", "n", "vị trí, tư thế", "Sit in a comfortable position.", "Ngồi ở tư thế thoải mái.")
SW("position", "v", "đặt vào vị trí", "Position the camera above the door.", "Đặt máy quay phía trên cửa.")
SW("reference", "n", "sự tham khảo, nhắc đến", "Keep this guide for future reference.", "Giữ cuốn hướng dẫn này để tham khảo sau.")
SW("training", "n", "sự tập luyện (thể thao)", "The team is in training for the final.", "Đội đang tập luyện cho trận chung kết.")
SW("benefit", "v", "có lợi, được lợi", "Everyone will benefit from the new park.", "Mọi người đều được lợi từ công viên mới.")
SW("promote", "v", "quảng bá, thúc đẩy", "The campaign promotes healthy eating.", "Chiến dịch thúc đẩy ăn uống lành mạnh.")
SW("brand", "v", "gắn mác", "He was branded a liar.", "Anh ta bị gắn mác kẻ nói dối.")
SW("image", "n", "hình ảnh, bức ảnh", "The image on the screen is blurry.", "Hình ảnh trên màn hình bị mờ.")
SW("commercial", "adj", "thương mại", "This is a commercial area with many shops.", "Đây là khu thương mại có nhiều cửa hàng.")
SW("exchange", "n", "sự trao đổi", "We had an exchange of ideas.", "Chúng tôi đã trao đổi ý tưởng.")
SW("order", "v", "ra lệnh", "The doctor ordered him to rest.", "Bác sĩ yêu cầu anh ấy nghỉ ngơi.")
SW("check out", "phr", "xem thử", "Check out our new menu!", "Xem thử thực đơn mới của chúng tôi nhé!")
