from lib import topic, W

# Hues index the 10 curated topic colours in the app (0-9). IPA: General American.

topic("office", "Văn phòng & điều hành", "🏢", 0)
W("office", "n", "ˈɑːfɪs", 1, "văn phòng", "Our office is on the third floor.", "Văn phòng của chúng tôi ở tầng ba.")
W("meeting", "n", "ˈmiːtɪŋ", 1, "cuộc họp", "The meeting starts at nine o'clock.", "Cuộc họp bắt đầu lúc chín giờ.", fam={"verb": "meet"})
W("schedule", "n", "ˈskedʒuːl", 2, "lịch trình, thời gian biểu", "Please check the schedule before you book a room.", "Vui lòng xem lịch trước khi đặt phòng.", coll=["ahead of schedule", "behind schedule", "on schedule"])
W("deadline", "n", "ˈdedlaɪn", 2, "hạn chót", "We must finish the report before the deadline.", "Chúng ta phải hoàn thành báo cáo trước hạn chót.", coll=["meet a deadline", "miss a deadline"])
W("colleague", "n", "ˈkɑːliːɡ", 2, "đồng nghiệp", "My colleague helped me with the presentation.", "Đồng nghiệp đã giúp tôi chuẩn bị bài thuyết trình.")
W("supervisor", "n", "ˈsuːpərvaɪzər", 2, "người giám sát, cấp trên trực tiếp", "Ask your supervisor if you need a day off.", "Hãy hỏi cấp trên nếu bạn cần nghỉ một ngày.", fam={"verb": "supervise", "noun": "supervision"})
W("department", "n", "dɪˈpɑːrtmənt", 2, "phòng ban, bộ phận", "She works in the sales department.", "Cô ấy làm việc ở phòng kinh doanh.")
W("agenda", "n", "əˈdʒendə", 3, "chương trình nghị sự (cuộc họp)", "The first item on the agenda is the budget.", "Mục đầu tiên trong chương trình họp là ngân sách.")
W("memo", "n", "ˈmemoʊ", 3, "thông báo nội bộ", "The manager sent a memo to all staff.", "Quản lý đã gửi thông báo nội bộ cho toàn bộ nhân viên.")
W("document", "n", "ˈdɑːkjəmənt", 1, "tài liệu, văn bản", "Save the document before you close it.", "Hãy lưu tài liệu trước khi đóng.", fam={"noun": "documentation", "verb": "document"})
W("photocopy", "v", "ˈfoʊtoʊkɑːpi", 2, "photo, sao chụp", "Could you photocopy these pages for me?", "Bạn có thể photo những trang này giúp tôi không?")
W("submit", "v", "səbˈmɪt", 3, "nộp, đệ trình", "Please submit your expense report by Friday.", "Vui lòng nộp báo cáo chi phí trước thứ Sáu.", fam={"noun": "submission"})
W("approve", "v", "əˈpruːv", 3, "phê duyệt, chấp thuận", "The director approved the new plan.", "Giám đốc đã phê duyệt kế hoạch mới.", fam={"noun": "approval"})
W("postpone", "v", "poʊstˈpoʊn", 3, "hoãn lại", "The meeting was postponed until next week.", "Cuộc họp đã bị hoãn đến tuần sau.")
W("assign", "v", "əˈsaɪn", 3, "giao (việc), phân công", "The manager assigned the task to two new employees.", "Quản lý giao nhiệm vụ cho hai nhân viên mới.", fam={"noun": "assignment"})
W("remind", "v", "rɪˈmaɪnd", 2, "nhắc nhở", "Please remind me to call the client.", "Hãy nhắc tôi gọi cho khách hàng nhé.", fam={"noun": "reminder"})
W("arrange", "v", "əˈreɪndʒ", 3, "sắp xếp, thu xếp", "Her assistant arranged a meeting with the client.", "Trợ lý của cô ấy đã thu xếp một cuộc họp với khách hàng.", fam={"noun": "arrangement"})
W("attend", "v", "əˈtend", 2, "tham dự", "All managers must attend the training session.", "Tất cả quản lý phải tham dự buổi đào tạo.", fam={"noun": "attendance", "adj": "attendee"})
W("efficient", "adj", "ɪˈfɪʃnt", 3, "hiệu quả (không lãng phí)", "The new printer is faster and more efficient.", "Máy in mới nhanh hơn và hiệu quả hơn.", fam={"noun": "efficiency", "adv": "efficiently"})
W("urgent", "adj", "ˈɜːrdʒənt", 3, "khẩn cấp, gấp", "I have an urgent message for Mr. Lee.", "Tôi có một tin nhắn khẩn cho ông Lee.", fam={"noun": "urgency", "adv": "urgently"})
W("temporary", "adj", "ˈtempəreri", 3, "tạm thời", "He found a temporary job for the summer.", "Anh ấy tìm được một công việc tạm thời cho mùa hè.", fam={"adv": "temporarily"})
W("productive", "adj", "prəˈdʌktɪv", 3, "năng suất, hiệu quả", "The team had a very productive meeting.", "Cả nhóm đã có một buổi họp rất hiệu quả.", fam={"noun": "productivity", "verb": "produce"})
W("stationery", "n", "ˈsteɪʃəneri", 3, "văn phòng phẩm", "Pens and paper are in the stationery cabinet.", "Bút và giấy ở trong tủ văn phòng phẩm.")
W("extension", "n", "ɪkˈstenʃn", 4, "số máy lẻ; sự gia hạn", "You can reach me at extension 214.", "Bạn có thể liên lạc với tôi qua số máy lẻ 214.")
W("delegate", "v", "ˈdelɪɡeɪt", 4, "ủy thác, giao bớt (việc)", "Good managers delegate routine tasks.", "Nhà quản lý giỏi biết giao bớt việc thường ngày.", fam={"noun": "delegation"})
W("workload", "n", "ˈwɜːrkloʊd", 3, "khối lượng công việc", "My workload is heavy this month.", "Khối lượng công việc của tôi tháng này rất nặng.")
W("in charge of", "phr", "ɪn tʃɑːrdʒ əv", 3, "phụ trách", "Ms. Park is in charge of the new project.", "Bà Park phụ trách dự án mới.")
W("on behalf of", "phr", "ɑːn bɪˈhæf əv", 4, "thay mặt cho", "I am writing on behalf of the whole team.", "Tôi viết thư này thay mặt cho cả nhóm.")
W("headquarters", "n", "ˈhedkwɔːrtərz", 3, "trụ sở chính", "The company's headquarters is in Singapore.", "Trụ sở chính của công ty ở Singapore.")
W("reception", "n", "rɪˈsepʃn", 2, "quầy lễ tân", "Please leave the package at reception.", "Vui lòng để gói hàng ở quầy lễ tân.", fam={"noun": "receptionist"})

topic("hr", "Nhân sự & tuyển dụng", "🧑‍💼", 1)
W("applicant", "n", "ˈæplɪkənt", 3, "người nộp đơn, ứng viên", "We received over fifty applicants for the position.", "Chúng tôi nhận được hơn năm mươi ứng viên cho vị trí này.", fam={"verb": "apply", "noun": "application"})
W("candidate", "n", "ˈkændɪdət", 3, "ứng viên", "The best candidate has ten years of experience.", "Ứng viên tốt nhất có mười năm kinh nghiệm.")
W("résumé", "n", "ˈrezəmeɪ", 3, "sơ yếu lý lịch (CV)", "Please send your résumé by email.", "Vui lòng gửi CV của bạn qua email.")
W("interview", "n", "ˈɪntərvjuː", 1, "buổi phỏng vấn", "I have a job interview tomorrow morning.", "Tôi có một buổi phỏng vấn xin việc vào sáng mai.", fam={"noun": "interviewer", "verb": "interview"})
W("hire", "v", "haɪər", 2, "thuê, tuyển dụng", "The hotel plans to hire twenty new staff.", "Khách sạn dự định tuyển hai mươi nhân viên mới.")
W("recruit", "v", "rɪˈkruːt", 3, "tuyển dụng", "The company recruits graduates every spring.", "Công ty tuyển sinh viên mới tốt nghiệp vào mỗi mùa xuân.", fam={"noun": "recruitment"})
W("qualified", "adj", "ˈkwɑːlɪfaɪd", 3, "đủ năng lực, đủ tiêu chuẩn", "She is highly qualified for this job.", "Cô ấy rất đủ năng lực cho công việc này.", fam={"noun": "qualification", "verb": "qualify"})
W("experience", "n", "ɪkˈspɪriəns", 2, "kinh nghiệm", "Do you have any experience in sales?", "Bạn có kinh nghiệm bán hàng không?", fam={"adj": "experienced"})
W("salary", "n", "ˈsæləri", 2, "lương (tháng/năm)", "The salary is paid on the last day of each month.", "Lương được trả vào ngày cuối mỗi tháng.")
W("wage", "n", "weɪdʒ", 3, "tiền công (theo giờ/tuần)", "The minimum wage will rise next year.", "Mức lương tối thiểu sẽ tăng vào năm tới.")
W("benefit", "n", "ˈbenɪfɪt", 3, "phúc lợi; lợi ích", "The job offers good benefits, including health insurance.", "Công việc có phúc lợi tốt, bao gồm bảo hiểm y tế.", fam={"adj": "beneficial"})
W("promote", "v", "prəˈmoʊt", 3, "thăng chức; quảng bá", "He was promoted to sales manager last year.", "Anh ấy được thăng chức trưởng phòng kinh doanh năm ngoái.", fam={"noun": "promotion"})
W("resign", "v", "rɪˈzaɪn", 3, "từ chức, nghỉ việc", "She resigned to start her own business.", "Cô ấy nghỉ việc để tự kinh doanh.", fam={"noun": "resignation"})
W("retire", "v", "rɪˈtaɪər", 3, "nghỉ hưu", "My father retired at the age of sixty.", "Bố tôi nghỉ hưu năm sáu mươi tuổi.", fam={"noun": "retirement"})
W("employee", "n", "ɪmˈplɔɪiː", 2, "nhân viên", "The company has about 300 employees.", "Công ty có khoảng 300 nhân viên.", fam={"noun": "employer", "verb": "employ"})
W("employer", "n", "ɪmˈplɔɪər", 2, "người sử dụng lao động, chủ", "Your employer must give you a written contract.", "Người sử dụng lao động phải đưa cho bạn hợp đồng bằng văn bản.")
W("position", "n", "pəˈzɪʃn", 2, "vị trí (công việc)", "We have an open position in the IT department.", "Chúng tôi đang tuyển một vị trí ở phòng IT.")
W("training", "n", "ˈtreɪnɪŋ", 2, "đào tạo", "New staff receive two weeks of training.", "Nhân viên mới được đào tạo hai tuần.", fam={"verb": "train", "noun": "trainee"})
W("performance", "n", "pərˈfɔːrməns", 3, "hiệu suất, thành tích", "Her performance this year has been excellent.", "Thành tích của cô ấy năm nay rất xuất sắc.", fam={"verb": "perform"})
W("evaluate", "v", "ɪˈvæljueɪt", 4, "đánh giá", "Managers evaluate each employee once a year.", "Quản lý đánh giá từng nhân viên mỗi năm một lần.", fam={"noun": "evaluation"})
W("probation", "n", "proʊˈbeɪʃn", 4, "thời gian thử việc", "New employees have a three-month probation period.", "Nhân viên mới có thời gian thử việc ba tháng.")
W("full-time", "adj", "ˌfʊl ˈtaɪm", 2, "toàn thời gian", "She has a full-time job at a bank.", "Cô ấy làm toàn thời gian ở một ngân hàng.")
W("part-time", "adj", "ˌpɑːrt ˈtaɪm", 2, "bán thời gian", "Many students have part-time jobs.", "Nhiều sinh viên làm việc bán thời gian.")
W("personnel", "n", "ˌpɜːrsəˈnel", 4, "nhân sự, toàn bộ nhân viên", "Only authorized personnel may enter this area.", "Chỉ nhân viên được phép mới được vào khu vực này.")
W("reference", "n", "ˈrefrəns", 3, "thư giới thiệu; người giới thiệu", "Please provide two references from former employers.", "Vui lòng cung cấp hai người giới thiệu từ nơi làm việc cũ.")
W("vacancy", "n", "ˈveɪkənsi", 4, "vị trí còn trống", "There is a vacancy for an accountant.", "Đang có một vị trí kế toán còn trống.")
W("workforce", "n", "ˈwɜːrkfɔːrs", 4, "lực lượng lao động", "Women make up half of our workforce.", "Phụ nữ chiếm một nửa lực lượng lao động của chúng tôi.")
W("apply for", "phr", "əˈplaɪ fɔːr", 2, "nộp đơn xin (việc, học bổng...)", "I want to apply for the marketing position.", "Tôi muốn ứng tuyển vị trí marketing.")
W("leave", "n", "liːv", 3, "kỳ nghỉ phép", "She is on maternity leave until June.", "Cô ấy nghỉ thai sản đến tháng Sáu.", coll=["sick leave", "annual leave", "on leave"])
W("incentive", "n", "ɪnˈsentɪv", 4, "khoản khuyến khích, động lực", "The company offers incentives for good performance.", "Công ty có khoản thưởng khuyến khích cho thành tích tốt.")

topic("finance", "Tài chính & ngân hàng", "🏦", 2)
W("account", "n", "əˈkaʊnt", 1, "tài khoản", "I opened a savings account at the bank.", "Tôi đã mở một tài khoản tiết kiệm ở ngân hàng.")
W("deposit", "v", "dɪˈpɑːzɪt", 3, "gửi (tiền vào tài khoản)", "You can deposit cash at any branch.", "Bạn có thể gửi tiền mặt ở bất kỳ chi nhánh nào.")
W("withdraw", "v", "wɪðˈdrɔː", 3, "rút (tiền)", "I need to withdraw some money from the ATM.", "Tôi cần rút một ít tiền từ máy ATM.", fam={"noun": "withdrawal"})
W("loan", "n", "loʊn", 3, "khoản vay", "They took out a loan to buy a house.", "Họ vay một khoản để mua nhà.")
W("interest", "n", "ˈɪntrəst", 3, "tiền lãi; sự quan tâm", "The bank pays 5 percent interest on this account.", "Ngân hàng trả lãi 5% cho tài khoản này.", coll=["interest rate"])
W("balance", "n", "ˈbæləns", 3, "số dư", "Please check your account balance online.", "Vui lòng kiểm tra số dư tài khoản trực tuyến.")
W("transfer", "v", "trænsˈfɜːr", 3, "chuyển (tiền, công tác)", "I transferred the money to your account yesterday.", "Tôi đã chuyển tiền vào tài khoản của bạn hôm qua.")
W("branch", "n", "bræntʃ", 2, "chi nhánh", "The bank has a branch near my office.", "Ngân hàng có một chi nhánh gần văn phòng tôi.")
W("currency", "n", "ˈkɜːrənsi", 3, "tiền tệ", "The euro is the currency of many European countries.", "Đồng euro là tiền tệ của nhiều nước châu Âu.", coll=["foreign currency", "exchange currency"])
W("exchange rate", "n", "ɪksˈtʃeɪndʒ reɪt", 3, "tỷ giá hối đoái", "The exchange rate changes every day.", "Tỷ giá hối đoái thay đổi mỗi ngày.")
W("invest", "v", "ɪnˈvest", 3, "đầu tư", "She invested her savings in a small business.", "Cô ấy đầu tư tiền tiết kiệm vào một doanh nghiệp nhỏ.", fam={"noun": "investment", "noun2": "investor"})
W("profit", "n", "ˈprɑːfɪt", 3, "lợi nhuận", "The company made a large profit last year.", "Công ty thu được lợi nhuận lớn năm ngoái.", fam={"adj": "profitable"})
W("revenue", "n", "ˈrevənuː", 4, "doanh thu", "Online sales now account for half of our revenue.", "Bán hàng trực tuyến hiện chiếm một nửa doanh thu.")
W("budget", "n", "ˈbʌdʒɪt", 2, "ngân sách", "We need to stay within the budget.", "Chúng ta cần chi tiêu trong ngân sách.", coll=["over budget", "within budget"])
W("expense", "n", "ɪkˈspens", 3, "chi phí, khoản chi", "Travel expenses will be paid by the company.", "Chi phí đi lại sẽ do công ty chi trả.", fam={"adj": "expensive"})
W("afford", "v", "əˈfɔːrd", 3, "đủ khả năng (chi trả)", "We can't afford a new car this year.", "Năm nay chúng tôi không đủ tiền mua xe mới.", fam={"adj": "affordable"})
W("debt", "n", "det", 3, "khoản nợ", "He paid off all his debts.", "Anh ấy đã trả hết các khoản nợ.")
W("mortgage", "n", "ˈmɔːrɡɪdʒ", 4, "khoản vay thế chấp (mua nhà)", "They pay their mortgage every month.", "Họ trả khoản vay mua nhà hằng tháng.")
W("savings", "n", "ˈseɪvɪŋz", 2, "tiền tiết kiệm", "She spent all her savings on the trip.", "Cô ấy tiêu hết tiền tiết kiệm cho chuyến đi.")
W("transaction", "n", "trænˈzækʃn", 4, "giao dịch", "Each transaction is recorded in the system.", "Mỗi giao dịch đều được ghi lại trong hệ thống.")
W("statement", "n", "ˈsteɪtmənt", 3, "sao kê; bản tuyên bố", "Your bank statement arrives at the start of each month.", "Sao kê ngân hàng đến vào đầu mỗi tháng.")
W("financial", "adj", "faɪˈnænʃl", 3, "(thuộc) tài chính", "The company is in a strong financial position.", "Công ty đang có tình hình tài chính vững mạnh.", fam={"noun": "finance", "adv": "financially"})
W("economy", "n", "ɪˈkɑːnəmi", 3, "nền kinh tế", "The economy grew by 6 percent this year.", "Nền kinh tế tăng trưởng 6% trong năm nay.", fam={"adj": "economic", "adj2": "economical"})
W("fund", "n", "fʌnd", 3, "quỹ; tiền vốn", "The school raised funds for a new library.", "Trường đã gây quỹ để xây thư viện mới.")
W("stock", "n", "stɑːk", 3, "cổ phiếu; hàng tồn kho", "The price of the company's stock rose sharply.", "Giá cổ phiếu của công ty tăng mạnh.")
W("cash", "n", "kæʃ", 1, "tiền mặt", "Do you want to pay by card or in cash?", "Bạn muốn trả bằng thẻ hay tiền mặt?")
W("credit card", "n", "ˈkredɪt kɑːrd", 1, "thẻ tín dụng", "Can I pay with a credit card?", "Tôi có thể thanh toán bằng thẻ tín dụng không?")
W("fee", "n", "fiː", 3, "phí, lệ phí", "There is no fee for opening an account.", "Không mất phí khi mở tài khoản.")
W("borrow", "v", "ˈbɑːroʊ", 2, "mượn, vay", "Can I borrow your pen for a minute?", "Tôi có thể mượn bút của bạn một chút không?")
W("lend", "v", "lend", 2, "cho mượn, cho vay", "Banks lend money to small businesses.", "Ngân hàng cho các doanh nghiệp nhỏ vay tiền.")

topic("accounting", "Kế toán & thuế", "🧾", 3)
W("invoice", "n", "ˈɪnvɔɪs", 3, "hóa đơn (đòi tiền)", "Please pay the invoice within 30 days.", "Vui lòng thanh toán hóa đơn trong vòng 30 ngày.")
W("receipt", "n", "rɪˈsiːt", 2, "biên lai, hóa đơn (đã trả)", "Keep the receipt in case you want to return it.", "Hãy giữ hóa đơn phòng khi bạn muốn trả lại hàng.")
W("tax", "n", "tæks", 2, "thuế", "Prices include a 10 percent sales tax.", "Giá đã bao gồm 10% thuế bán hàng.")
W("audit", "n", "ˈɔːdɪt", 4, "cuộc kiểm toán", "An external audit is carried out every year.", "Một cuộc kiểm toán độc lập được thực hiện hằng năm.", fam={"noun": "auditor"})
W("accountant", "n", "əˈkaʊntənt", 2, "kế toán viên", "Our accountant prepares the tax forms.", "Kế toán của chúng tôi chuẩn bị các tờ khai thuế.", fam={"noun": "accounting"})
W("calculate", "v", "ˈkælkjuleɪt", 3, "tính toán", "We calculated the total cost of the project.", "Chúng tôi đã tính tổng chi phí dự án.", fam={"noun": "calculation"})
W("estimate", "n", "ˈestɪmət", 3, "bản ước tính, báo giá sơ bộ", "The builder gave us an estimate for the repairs.", "Thợ xây đưa cho chúng tôi bản ước tính chi phí sửa chữa.")
W("reimburse", "v", "ˌriːɪmˈbɜːrs", 5, "hoàn trả (chi phí)", "The company will reimburse your travel costs.", "Công ty sẽ hoàn trả chi phí đi lại cho bạn.", fam={"noun": "reimbursement"})
W("quarter", "n", "ˈkwɔːrtər", 3, "quý (3 tháng)", "Sales rose in the second quarter.", "Doanh số tăng trong quý hai.", fam={"adj": "quarterly"})
W("annual", "adj", "ˈænjuəl", 3, "hằng năm", "The annual report will be published in March.", "Báo cáo thường niên sẽ được công bố vào tháng Ba.", fam={"adv": "annually"})
W("deduct", "v", "dɪˈdʌkt", 4, "khấu trừ", "Tax is deducted from your salary every month.", "Thuế được khấu trừ vào lương mỗi tháng.", fam={"noun": "deduction"})
W("figure", "n", "ˈfɪɡjər", 3, "con số, số liệu", "The sales figures for May look good.", "Số liệu doanh số tháng Năm trông khả quan.")
W("spreadsheet", "n", "ˈspredʃiːt", 3, "bảng tính", "I keep all the costs in a spreadsheet.", "Tôi ghi tất cả chi phí trong một bảng tính.")
W("asset", "n", "ˈæset", 4, "tài sản", "The building is the company's biggest asset.", "Tòa nhà là tài sản lớn nhất của công ty.")
W("payroll", "n", "ˈpeɪroʊl", 4, "bảng lương", "The payroll department pays staff every two weeks.", "Bộ phận lương trả lương cho nhân viên hai tuần một lần.")
W("record", "n", "ˈrekərd", 2, "hồ sơ, bản ghi", "Keep a record of all your expenses.", "Hãy ghi chép lại tất cả các khoản chi của bạn.")
W("outstanding", "adj", "aʊtˈstændɪŋ", 4, "chưa thanh toán; nổi bật", "There are three outstanding invoices.", "Có ba hóa đơn chưa thanh toán.")
W("overdue", "adj", "ˌoʊvərˈduː", 4, "quá hạn", "The payment is two weeks overdue.", "Khoản thanh toán đã quá hạn hai tuần.")
W("refund", "n", "ˈriːfʌnd", 3, "tiền hoàn lại", "You can get a full refund within 14 days.", "Bạn có thể được hoàn tiền toàn bộ trong vòng 14 ngày.")
W("charge", "v", "tʃɑːrdʒ", 3, "tính phí", "The hotel charged us for an extra night.", "Khách sạn tính thêm tiền một đêm của chúng tôi.")
W("total", "n", "ˈtoʊtl", 1, "tổng số", "The total comes to 45 dollars.", "Tổng cộng là 45 đô la.")
W("increase", "v", "ɪnˈkriːs", 2, "tăng", "Prices increased by 3 percent last month.", "Giá tăng 3% vào tháng trước.")
W("decrease", "v", "dɪˈkriːs", 2, "giảm", "The number of complaints decreased this year.", "Số lượng khiếu nại đã giảm trong năm nay.")
W("loss", "n", "lɔːs", 3, "khoản lỗ; sự mất mát", "The shop made a loss in its first year.", "Cửa hàng bị lỗ trong năm đầu tiên.")
W("cost", "n", "kɔːst", 1, "chi phí, giá", "The cost of living is rising.", "Chi phí sinh hoạt đang tăng.")
W("accurate", "adj", "ˈækjərət", 3, "chính xác", "Please make sure the figures are accurate.", "Vui lòng đảm bảo các số liệu chính xác.", fam={"noun": "accuracy", "adv": "accurately"})
W("fiscal year", "n", "ˈfɪskl jɪr", 5, "năm tài chính", "Our fiscal year begins in April.", "Năm tài chính của chúng tôi bắt đầu vào tháng Tư.")
W("bill", "n", "bɪl", 1, "hóa đơn (điện, nước, nhà hàng)", "Could we have the bill, please?", "Cho chúng tôi xin hóa đơn được không?")
W("balance sheet", "n", "ˈbæləns ʃiːt", 5, "bảng cân đối kế toán", "The balance sheet shows what the company owns and owes.", "Bảng cân đối kế toán cho thấy công ty sở hữu gì và nợ gì.")
W("expenditure", "n", "ɪkˈspendɪtʃər", 5, "khoản chi tiêu (chính thức)", "Government expenditure on education has increased.", "Chi tiêu của chính phủ cho giáo dục đã tăng.")

topic("marketing", "Marketing & quảng cáo", "📣", 4)
W("advertise", "v", "ˈædvərtaɪz", 2, "quảng cáo", "They advertise their products on social media.", "Họ quảng cáo sản phẩm trên mạng xã hội.", fam={"noun": "advertisement", "noun2": "advertising"})
W("campaign", "n", "kæmˈpeɪn", 3, "chiến dịch", "The new advertising campaign starts in May.", "Chiến dịch quảng cáo mới bắt đầu vào tháng Năm.")
W("brand", "n", "brænd", 2, "thương hiệu", "This is a well-known brand of coffee.", "Đây là một thương hiệu cà phê nổi tiếng.")
W("target", "n", "ˈtɑːrɡɪt", 3, "mục tiêu, đối tượng", "Young people are our main target market.", "Người trẻ là thị trường mục tiêu chính của chúng tôi.")
W("survey", "n", "ˈsɜːrveɪ", 3, "cuộc khảo sát", "We did a survey of 500 customers.", "Chúng tôi đã khảo sát 500 khách hàng.")
W("competitor", "n", "kəmˈpetɪtər", 3, "đối thủ cạnh tranh", "Our prices are lower than our competitors'.", "Giá của chúng tôi thấp hơn giá của đối thủ.", fam={"verb": "compete", "noun": "competition", "adj": "competitive"})
W("launch", "v", "lɔːntʃ", 3, "ra mắt (sản phẩm)", "The company will launch a new phone next month.", "Công ty sẽ ra mắt điện thoại mới vào tháng sau.")
W("promotion", "n", "prəˈmoʊʃn", 3, "khuyến mãi; sự thăng chức", "There is a special promotion on all shoes this week.", "Tuần này có khuyến mãi đặc biệt cho tất cả giày.")
W("consumer", "n", "kənˈsuːmər", 3, "người tiêu dùng", "Consumers are spending more online.", "Người tiêu dùng đang chi tiêu nhiều hơn trên mạng.", fam={"verb": "consume", "noun": "consumption"})
W("market share", "n", "ˈmɑːrkɪt ʃer", 4, "thị phần", "The firm increased its market share to 20 percent.", "Công ty tăng thị phần lên 20%.")
W("strategy", "n", "ˈstrætədʒi", 3, "chiến lược", "We need a new marketing strategy.", "Chúng ta cần một chiến lược marketing mới.", fam={"adj": "strategic"})
W("logo", "n", "ˈloʊɡoʊ", 1, "biểu trưng, logo", "The logo is printed on every bag.", "Logo được in trên mọi chiếc túi.")
W("slogan", "n", "ˈsloʊɡən", 3, "khẩu hiệu", "The slogan is short and easy to remember.", "Khẩu hiệu ngắn gọn và dễ nhớ.")
W("feedback", "n", "ˈfiːdbæk", 2, "phản hồi, góp ý", "Customer feedback helps us improve our service.", "Phản hồi của khách giúp chúng tôi cải thiện dịch vụ.")
W("trend", "n", "trend", 3, "xu hướng", "Healthy snacks are a growing trend.", "Đồ ăn vặt lành mạnh là một xu hướng đang tăng.")
W("audience", "n", "ˈɔːdiəns", 3, "khán giả, công chúng", "The ad reached a large audience.", "Quảng cáo đã tiếp cận một lượng lớn khán giả.")
W("commercial", "n", "kəˈmɜːrʃl", 3, "đoạn quảng cáo (TV, radio)", "The commercial was shown during the football match.", "Đoạn quảng cáo được phát trong trận bóng đá.")
W("flyer", "n", "ˈflaɪər", 3, "tờ rơi", "We handed out flyers at the train station.", "Chúng tôi phát tờ rơi ở ga tàu.")
W("demand", "n", "dɪˈmænd", 3, "nhu cầu", "Demand for electric cars is rising.", "Nhu cầu về xe điện đang tăng.", coll=["in demand", "supply and demand"])
W("attract", "v", "əˈtrækt", 3, "thu hút", "The sale attracted hundreds of shoppers.", "Đợt giảm giá thu hút hàng trăm người mua sắm.", fam={"adj": "attractive", "noun": "attraction"})
W("loyal", "adj", "ˈlɔɪəl", 3, "trung thành", "We reward our loyal customers with discounts.", "Chúng tôi thưởng giảm giá cho khách hàng thân thiết.", fam={"noun": "loyalty"})
W("sponsor", "v", "ˈspɑːnsər", 4, "tài trợ", "A local bank sponsored the music festival.", "Một ngân hàng địa phương đã tài trợ lễ hội âm nhạc.", fam={"noun": "sponsorship"})
W("publicity", "n", "pʌbˈlɪsəti", 4, "sự quảng bá, sự chú ý của công chúng", "The event got a lot of publicity.", "Sự kiện nhận được nhiều sự chú ý.")
W("innovative", "adj", "ˈɪnəveɪtɪv", 4, "sáng tạo, đổi mới", "The company is known for its innovative designs.", "Công ty nổi tiếng với những thiết kế sáng tạo.", fam={"noun": "innovation"})
W("potential", "adj", "pəˈtenʃl", 4, "tiềm năng", "We met several potential customers at the fair.", "Chúng tôi gặp vài khách hàng tiềm năng ở hội chợ.")
W("research", "n", "rɪˈsɜːrtʃ", 3, "nghiên cứu", "Market research shows that people want cheaper products.", "Nghiên cứu thị trường cho thấy mọi người muốn sản phẩm rẻ hơn.")
W("image", "n", "ˈɪmɪdʒ", 2, "hình ảnh (thương hiệu)", "The company wants to improve its public image.", "Công ty muốn cải thiện hình ảnh trước công chúng.")
W("billboard", "n", "ˈbɪlbɔːrd", 3, "biển quảng cáo lớn", "There is a huge billboard next to the highway.", "Có một biển quảng cáo khổng lồ cạnh đường cao tốc.")
W("exclusive", "adj", "ɪkˈskluːsɪv", 4, "độc quyền, dành riêng", "Members get exclusive offers every month.", "Thành viên nhận ưu đãi dành riêng mỗi tháng.", fam={"adv": "exclusively"})
W("boost", "v", "buːst", 4, "thúc đẩy, làm tăng", "The new ad boosted sales by 15 percent.", "Quảng cáo mới làm doanh số tăng 15%.")

topic("sales", "Bán hàng & chăm sóc khách hàng", "🛍️", 5)
W("customer", "n", "ˈkʌstəmər", 1, "khách hàng", "The customer asked for a refund.", "Khách hàng yêu cầu hoàn tiền.")
W("client", "n", "ˈklaɪənt", 2, "khách hàng (dịch vụ)", "The lawyer met her client at ten.", "Luật sư gặp khách hàng lúc mười giờ.")
W("discount", "n", "ˈdɪskaʊnt", 2, "sự giảm giá", "Students get a 10 percent discount.", "Sinh viên được giảm giá 10%.")
W("complaint", "n", "kəmˈpleɪnt", 3, "lời phàn nàn, khiếu nại", "We received a complaint about the late delivery.", "Chúng tôi nhận được khiếu nại về việc giao hàng trễ.", fam={"verb": "complain"})
W("warranty", "n", "ˈwɔːrənti", 3, "bảo hành", "The laptop comes with a two-year warranty.", "Máy tính xách tay được bảo hành hai năm.", coll=["under warranty"])
W("purchase", "v", "ˈpɜːrtʃəs", 3, "mua (trang trọng)", "You can purchase tickets online.", "Bạn có thể mua vé trực tuyến.")
W("deliver", "v", "dɪˈlɪvər", 2, "giao (hàng)", "We deliver free of charge within the city.", "Chúng tôi giao hàng miễn phí trong thành phố.", fam={"noun": "delivery"})
W("in stock", "phr", "ɪn stɑːk", 3, "còn hàng", "This model is not in stock at the moment.", "Mẫu này hiện đang hết hàng.", coll=["out of stock"])
W("satisfied", "adj", "ˈsætɪsfaɪd", 3, "hài lòng", "Most customers are satisfied with our service.", "Hầu hết khách hàng hài lòng với dịch vụ của chúng tôi.", fam={"noun": "satisfaction", "verb": "satisfy"})
W("replace", "v", "rɪˈpleɪs", 3, "thay thế, đổi", "We will replace the broken item for free.", "Chúng tôi sẽ đổi miễn phí món hàng bị hỏng.", fam={"noun": "replacement"})
W("inquiry", "n", "ˈɪŋkwəri", 4, "câu hỏi, yêu cầu thông tin", "Thank you for your inquiry about our prices.", "Cảm ơn bạn đã hỏi về giá của chúng tôi.", fam={"verb": "inquire"})
W("quote", "n", "kwoʊt", 4, "bảng báo giá", "Can you send me a quote for 200 chairs?", "Bạn có thể gửi báo giá cho 200 chiếc ghế không?")
W("order", "n", "ˈɔːrdər", 1, "đơn hàng", "Your order will arrive in three days.", "Đơn hàng của bạn sẽ đến trong ba ngày.")
W("cashier", "n", "kæˈʃɪr", 2, "thu ngân", "Please pay at the cashier.", "Vui lòng thanh toán ở quầy thu ngân.")
W("salesperson", "n", "ˈseɪlzpɜːrsn", 2, "nhân viên bán hàng", "The salesperson showed us several models.", "Nhân viên bán hàng cho chúng tôi xem vài mẫu.")
W("retail", "n", "ˈriːteɪl", 4, "bán lẻ", "She has worked in retail for ten years.", "Cô ấy làm trong ngành bán lẻ mười năm.", fam={"noun": "retailer"})
W("wholesale", "n", "ˈhoʊlseɪl", 4, "bán buôn, bán sỉ", "We buy our coffee at wholesale prices.", "Chúng tôi mua cà phê theo giá sỉ.")
W("bargain", "n", "ˈbɑːrɡən", 3, "món hời", "This jacket was a real bargain.", "Chiếc áo khoác này đúng là món hời.")
W("apologize", "v", "əˈpɑːlədʒaɪz", 3, "xin lỗi", "We apologize for the inconvenience.", "Chúng tôi xin lỗi vì sự bất tiện này.", fam={"noun": "apology"})
W("inconvenience", "n", "ˌɪnkənˈviːniəns", 4, "sự bất tiện", "We are sorry for any inconvenience caused.", "Chúng tôi xin lỗi vì mọi bất tiện gây ra.")
W("available", "adj", "əˈveɪləbl", 2, "có sẵn; rảnh", "The new model is available in three colors.", "Mẫu mới có ba màu.", fam={"noun": "availability"})
W("item", "n", "ˈaɪtəm", 1, "món đồ, mặt hàng", "Each item is checked before it is shipped.", "Mỗi mặt hàng đều được kiểm tra trước khi gửi.")
W("checkout", "n", "ˈtʃekaʊt", 3, "quầy thanh toán; bước thanh toán", "There was a long line at the checkout.", "Có một hàng dài ở quầy thanh toán.")
W("guarantee", "v", "ˌɡærənˈtiː", 4, "bảo đảm", "We guarantee delivery within 48 hours.", "Chúng tôi đảm bảo giao hàng trong 48 giờ.")
W("handle", "v", "ˈhændl", 3, "xử lý", "She handles all customer complaints.", "Cô ấy xử lý mọi khiếu nại của khách hàng.")
W("courteous", "adj", "ˈkɜːrtiəs", 5, "lịch sự, nhã nhặn", "Staff must always be courteous to customers.", "Nhân viên phải luôn lịch sự với khách hàng.", fam={"noun": "courtesy"})
W("loyalty card", "n", "ˈlɔɪəlti kɑːrd", 3, "thẻ khách hàng thân thiết", "You earn points with your loyalty card.", "Bạn được tích điểm với thẻ thành viên.")
W("receipt of", "phr", "rɪˈsiːt əv", 5, "việc nhận được (trang trọng)", "Please confirm receipt of this email.", "Vui lòng xác nhận đã nhận được email này.")
W("exchange", "v", "ɪksˈtʃeɪndʒ", 2, "đổi (hàng)", "Can I exchange this shirt for a larger size?", "Tôi có thể đổi chiếc áo này lấy cỡ lớn hơn không?")
W("representative", "n", "ˌreprɪˈzentətɪv", 4, "người đại diện", "A sales representative will call you shortly.", "Một đại diện kinh doanh sẽ gọi cho bạn ngay.", fam={"verb": "represent"})

topic("legal", "Hợp đồng & pháp lý", "📜", 6)
W("contract", "n", "ˈkɑːntrækt", 3, "hợp đồng", "Both sides signed the contract yesterday.", "Hai bên đã ký hợp đồng hôm qua.")
W("agreement", "n", "əˈɡriːmənt", 3, "thỏa thuận", "We reached an agreement after long talks.", "Chúng tôi đạt được thỏa thuận sau các cuộc đàm phán dài.", fam={"verb": "agree"})
W("terms", "n", "tɜːrmz", 4, "điều khoản", "Please read the terms and conditions carefully.", "Vui lòng đọc kỹ các điều khoản và điều kiện.")
W("sign", "v", "saɪn", 1, "ký (tên)", "Please sign here.", "Vui lòng ký vào đây.", fam={"noun": "signature"})
W("negotiate", "v", "nɪˈɡoʊʃieɪt", 4, "đàm phán", "We negotiated a lower price with the supplier.", "Chúng tôi đã đàm phán giá thấp hơn với nhà cung cấp.", fam={"noun": "negotiation"})
W("expire", "v", "ɪkˈspaɪər", 3, "hết hạn", "My passport expires next year.", "Hộ chiếu của tôi hết hạn vào năm sau.", fam={"noun": "expiration"})
W("renew", "v", "rɪˈnuː", 3, "gia hạn, làm mới", "You need to renew your license every five years.", "Bạn cần gia hạn giấy phép mỗi năm năm.", fam={"noun": "renewal"})
W("comply with", "phr", "kəmˈplaɪ wɪð", 5, "tuân thủ", "All products must comply with safety rules.", "Mọi sản phẩm phải tuân thủ quy định an toàn.", fam={"noun": "compliance"})
W("regulation", "n", "ˌreɡjuˈleɪʃn", 4, "quy định", "New regulations on food safety start in July.", "Các quy định mới về an toàn thực phẩm có hiệu lực từ tháng Bảy.", fam={"verb": "regulate"})
W("lawyer", "n", "ˈlɔːjər", 2, "luật sư", "You should talk to a lawyer before you sign.", "Bạn nên hỏi luật sư trước khi ký.")
W("legal", "adj", "ˈliːɡl", 3, "(thuộc) pháp luật; hợp pháp", "The company is facing legal problems.", "Công ty đang gặp các vấn đề pháp lý.", fam={"adj2": "illegal", "adv": "legally"})
W("clause", "n", "klɔːz", 5, "điều khoản (trong hợp đồng)", "A clause in the contract covers late payments.", "Một điều khoản trong hợp đồng quy định về việc trả chậm.")
W("valid", "adj", "ˈvælɪd", 3, "có hiệu lực, hợp lệ", "This ticket is valid for one month.", "Vé này có hiệu lực trong một tháng.", fam={"adj2": "invalid", "noun": "validity"})
W("permit", "n", "ˈpɜːrmɪt", 3, "giấy phép", "You need a permit to park here.", "Bạn cần giấy phép để đỗ xe ở đây.", fam={"verb": "permit", "noun2": "permission"})
W("policy", "n", "ˈpɑːləsi", 3, "chính sách", "Our return policy allows refunds within 30 days.", "Chính sách đổi trả cho phép hoàn tiền trong 30 ngày.")
W("party", "n", "ˈpɑːrti", 4, "bên (trong hợp đồng)", "Both parties must agree to any changes.", "Cả hai bên phải đồng ý với mọi thay đổi.")
W("breach", "n", "briːtʃ", 5, "sự vi phạm (hợp đồng)", "Late delivery is a breach of contract.", "Giao hàng trễ là vi phạm hợp đồng.")
W("dispute", "n", "dɪˈspjuːt", 4, "tranh chấp", "The two companies settled their dispute.", "Hai công ty đã giải quyết tranh chấp.")
W("court", "n", "kɔːrt", 3, "tòa án", "The case will go to court next month.", "Vụ việc sẽ được đưa ra tòa vào tháng sau.")
W("confidential", "adj", "ˌkɑːnfɪˈdenʃl", 4, "bí mật, mật", "This information is strictly confidential.", "Thông tin này tuyệt đối bảo mật.", fam={"noun": "confidentiality"})
W("liable", "adj", "ˈlaɪəbl", 5, "chịu trách nhiệm pháp lý", "The company is not liable for lost items.", "Công ty không chịu trách nhiệm về đồ bị mất.", fam={"noun": "liability"})
W("obligation", "n", "ˌɑːblɪˈɡeɪʃn", 4, "nghĩa vụ", "You are under no obligation to buy anything.", "Bạn không có nghĩa vụ phải mua gì cả.", fam={"verb": "oblige", "adj": "obligatory"})
W("draft", "n", "dræft", 3, "bản nháp", "I sent you the first draft of the contract.", "Tôi đã gửi bạn bản nháp đầu tiên của hợp đồng.")
W("binding", "adj", "ˈbaɪndɪŋ", 5, "có tính ràng buộc", "The agreement is legally binding.", "Thỏa thuận này có tính ràng buộc pháp lý.")
W("terminate", "v", "ˈtɜːrmɪneɪt", 5, "chấm dứt (hợp đồng)", "Either side may terminate the contract with 30 days' notice.", "Mỗi bên có thể chấm dứt hợp đồng với thông báo trước 30 ngày.", fam={"noun": "termination"})
W("notice", "n", "ˈnoʊtɪs", 3, "thông báo (trước)", "The rules may change without notice.", "Quy định có thể thay đổi mà không báo trước.", coll=["give notice", "at short notice"])
W("property", "n", "ˈprɑːpərti", 3, "tài sản; bất động sản", "Do not damage public property.", "Không được làm hư hại tài sản công.")
W("license", "n", "ˈlaɪsns", 3, "giấy phép", "The restaurant lost its license.", "Nhà hàng bị mất giấy phép kinh doanh.")
W("evidence", "n", "ˈevɪdəns", 3, "bằng chứng", "There is no evidence that he broke the rules.", "Không có bằng chứng anh ta vi phạm quy định.")
W("authorize", "v", "ˈɔːθəraɪz", 4, "ủy quyền, cho phép", "Only the manager can authorize refunds.", "Chỉ quản lý mới được phép duyệt hoàn tiền.", fam={"noun": "authorization", "noun2": "authority"})

topic("logistics", "Sản xuất & kho vận", "🏭", 7)
W("factory", "n", "ˈfæktri", 1, "nhà máy", "The factory produces 500 cars a day.", "Nhà máy sản xuất 500 xe mỗi ngày.")
W("manufacture", "v", "ˌmænjuˈfæktʃər", 4, "sản xuất (quy mô lớn)", "The company manufactures parts for airplanes.", "Công ty sản xuất linh kiện máy bay.", fam={"noun": "manufacturer"})
W("warehouse", "n", "ˈwerhaʊs", 3, "nhà kho", "The goods are stored in a warehouse.", "Hàng hóa được lưu trong nhà kho.")
W("shipment", "n", "ˈʃɪpmənt", 3, "lô hàng (vận chuyển)", "The shipment arrived two days late.", "Lô hàng đến trễ hai ngày.", fam={"verb": "ship"})
W("inventory", "n", "ˈɪnvəntɔːri", 4, "hàng tồn kho; kiểm kê", "We check our inventory every Friday.", "Chúng tôi kiểm kê hàng tồn mỗi thứ Sáu.")
W("supplier", "n", "səˈplaɪər", 3, "nhà cung cấp", "We are looking for a new paper supplier.", "Chúng tôi đang tìm nhà cung cấp giấy mới.", fam={"verb": "supply"})
W("assemble", "v", "əˈsembl", 4, "lắp ráp", "Workers assemble the phones by hand.", "Công nhân lắp ráp điện thoại bằng tay.", fam={"noun": "assembly"})
W("equipment", "n", "ɪˈkwɪpmənt", 3, "thiết bị", "All safety equipment must be checked daily.", "Tất cả thiết bị an toàn phải được kiểm tra hằng ngày.")
W("machinery", "n", "məˈʃiːnəri", 4, "máy móc (nói chung)", "The factory bought new machinery.", "Nhà máy đã mua máy móc mới.")
W("quality", "n", "ˈkwɑːləti", 2, "chất lượng", "We never compromise on quality.", "Chúng tôi không bao giờ đánh đổi chất lượng.", coll=["quality control"])
W("defective", "adj", "dɪˈfektɪv", 4, "bị lỗi", "Defective products will be replaced.", "Sản phẩm lỗi sẽ được thay thế.", fam={"noun": "defect"})
W("output", "n", "ˈaʊtpʊt", 4, "sản lượng", "Output rose by 10 percent this year.", "Sản lượng tăng 10% trong năm nay.")
W("capacity", "n", "kəˈpæsəti", 4, "công suất; sức chứa", "The plant is working at full capacity.", "Nhà máy đang chạy hết công suất.")
W("freight", "n", "freɪt", 4, "hàng hóa vận chuyển; cước", "Freight costs have doubled this year.", "Cước vận chuyển đã tăng gấp đôi trong năm nay.")
W("container", "n", "kənˈteɪnər", 3, "thùng hàng, công-ten-nơ", "The container was loaded onto the ship.", "Thùng hàng đã được đưa lên tàu.")
W("deliver on time", "phr", "dɪˈlɪvər ɑːn taɪm", 2, "giao đúng hạn", "Our drivers always deliver on time.", "Tài xế của chúng tôi luôn giao hàng đúng hạn.")
W("track", "v", "træk", 3, "theo dõi (đơn hàng)", "You can track your package online.", "Bạn có thể theo dõi gói hàng trực tuyến.", coll=["tracking number"])
W("package", "n", "ˈpækɪdʒ", 2, "gói hàng, bưu kiện", "A package arrived for you this morning.", "Sáng nay có một gói hàng gửi cho bạn.", fam={"noun": "packaging"})
W("load", "v", "loʊd", 3, "chất (hàng) lên", "They loaded the boxes onto the truck.", "Họ chất các thùng lên xe tải.", fam={"verb": "unload"})
W("raw material", "n", "rɔː məˈtɪriəl", 4, "nguyên liệu thô", "The price of raw materials has gone up.", "Giá nguyên liệu thô đã tăng.")
W("process", "n", "ˈprɑːses", 3, "quy trình", "The hiring process takes about a month.", "Quy trình tuyển dụng mất khoảng một tháng.")
W("operate", "v", "ˈɑːpəreɪt", 3, "vận hành", "Only trained staff may operate this machine.", "Chỉ nhân viên đã qua đào tạo mới được vận hành máy này.", fam={"noun": "operation", "noun2": "operator"})
W("maintenance", "n", "ˈmeɪntənəns", 4, "sự bảo trì", "The elevator is closed for maintenance.", "Thang máy đang tạm dừng để bảo trì.", fam={"verb": "maintain"})
W("safety", "n", "ˈseɪfti", 2, "sự an toàn", "Safety is our top priority.", "An toàn là ưu tiên hàng đầu của chúng tôi.", fam={"adj": "safe"})
W("distribute", "v", "dɪˈstrɪbjuːt", 4, "phân phối", "We distribute our products to 30 countries.", "Chúng tôi phân phối sản phẩm tới 30 quốc gia.", fam={"noun": "distribution", "noun2": "distributor"})
W("shortage", "n", "ˈʃɔːrtɪdʒ", 4, "sự thiếu hụt", "There is a shortage of skilled workers.", "Đang thiếu hụt lao động có tay nghề.")
W("automate", "v", "ˈɔːtəmeɪt", 5, "tự động hóa", "The factory has automated most of its production.", "Nhà máy đã tự động hóa phần lớn sản xuất.", fam={"noun": "automation", "adj": "automatic"})
W("delay", "n", "dɪˈleɪ", 2, "sự chậm trễ", "Bad weather caused long delays.", "Thời tiết xấu gây chậm trễ kéo dài.")
W("efficiency", "n", "ɪˈfɪʃnsi", 4, "hiệu suất", "New machines improved efficiency by 20 percent.", "Máy mới cải thiện hiệu suất 20%.")
W("specification", "n", "ˌspesɪfɪˈkeɪʃn", 5, "thông số kỹ thuật", "The parts must meet the customer's specifications.", "Linh kiện phải đáp ứng thông số kỹ thuật của khách hàng.")

topic("commerce", "Mua sắm & thương mại", "🛒", 8)
W("price", "n", "praɪs", 1, "giá", "The price includes breakfast.", "Giá đã bao gồm bữa sáng.")
W("cheap", "adj", "tʃiːp", 1, "rẻ", "The food here is cheap and good.", "Đồ ăn ở đây rẻ và ngon.")
W("expensive", "adj", "ɪkˈspensɪv", 1, "đắt", "Hotels in the city center are expensive.", "Khách sạn ở trung tâm thành phố đắt.")
W("import", "v", "ɪmˈpɔːrt", 3, "nhập khẩu", "Vietnam imports a lot of machinery.", "Việt Nam nhập khẩu nhiều máy móc.")
W("export", "v", "ɪkˈspɔːrt", 3, "xuất khẩu", "Vietnam exports coffee and rice.", "Việt Nam xuất khẩu cà phê và gạo.")
W("trade", "n", "treɪd", 3, "thương mại", "Trade between the two countries is growing.", "Thương mại giữa hai nước đang tăng.")
W("goods", "n", "ɡʊdz", 3, "hàng hóa", "The goods will be shipped by sea.", "Hàng hóa sẽ được vận chuyển bằng đường biển.")
W("merchandise", "n", "ˈmɜːrtʃəndaɪz", 5, "hàng hóa (để bán)", "All merchandise is 20 percent off.", "Tất cả hàng hóa được giảm 20%.")
W("vendor", "n", "ˈvendər", 4, "người bán", "Street vendors sell fruit near the market.", "Người bán hàng rong bán trái cây gần chợ.")
W("catalog", "n", "ˈkætəlɔːɡ", 3, "danh mục sản phẩm", "Please see our catalog for more products.", "Vui lòng xem danh mục để biết thêm sản phẩm.")
W("bulk", "n", "bʌlk", 4, "số lượng lớn", "It is cheaper to buy in bulk.", "Mua số lượng lớn thì rẻ hơn.")
W("affordable", "adj", "əˈfɔːrdəbl", 3, "giá phải chăng", "We offer affordable prices for students.", "Chúng tôi có giá phải chăng cho sinh viên.")
W("payment", "n", "ˈpeɪmənt", 2, "sự thanh toán, khoản thanh toán", "We accept payment by bank transfer.", "Chúng tôi nhận thanh toán bằng chuyển khoản.", fam={"verb": "pay"})
W("install", "v", "ɪnˈstɔːl", 3, "lắp đặt; cài đặt", "A technician will install the air conditioner.", "Kỹ thuật viên sẽ lắp máy điều hòa.", fam={"noun": "installation"})
W("compare", "v", "kəmˈper", 2, "so sánh", "Compare prices before you buy.", "So sánh giá trước khi mua.", fam={"noun": "comparison"})
W("brochure", "n", "broʊˈʃʊr", 3, "tờ quảng cáo, sách giới thiệu", "Take a brochure for more information.", "Hãy lấy một tờ giới thiệu để biết thêm thông tin.")
W("sale", "n", "seɪl", 1, "đợt giảm giá; sự bán", "These shoes are on sale this week.", "Đôi giày này đang giảm giá tuần này.")
W("customer service", "n", "ˈkʌstəmər ˈsɜːrvɪs", 2, "dịch vụ khách hàng", "Please call customer service for help.", "Vui lòng gọi dịch vụ khách hàng để được hỗ trợ.")
W("shopping mall", "n", "ˈʃɑːpɪŋ mɔːl", 1, "trung tâm mua sắm", "A new shopping mall opened downtown.", "Một trung tâm mua sắm mới mở ở trung tâm.")
W("brand-new", "adj", "ˌbrænd ˈnuː", 2, "mới toanh", "He bought a brand-new laptop.", "Anh ấy mua một chiếc laptop mới tinh.")
W("second-hand", "adj", "ˌsekənd ˈhænd", 2, "đã qua sử dụng", "I bought a second-hand bicycle.", "Tôi mua một chiếc xe đạp cũ.")
W("try on", "phr", "traɪ ɑːn", 1, "thử (quần áo)", "Can I try on this jacket?", "Tôi thử chiếc áo khoác này được không?")
W("size", "n", "saɪz", 1, "cỡ, kích cỡ", "Do you have this in a smaller size?", "Bạn có cỡ nhỏ hơn không?")
W("fit", "v", "fɪt", 2, "vừa (kích cỡ)", "These jeans don't fit me.", "Chiếc quần jean này không vừa với tôi.")
W("suit", "v", "suːt", 3, "hợp (với ai)", "Blue really suits you.", "Màu xanh rất hợp với bạn.", fam={"adj": "suitable"})
W("deal", "n", "diːl", 3, "giao dịch; món hời", "We made a deal with a new partner.", "Chúng tôi đã ký thỏa thuận với một đối tác mới.")
W("wholesaler", "n", "ˈhoʊlseɪlər", 5, "nhà bán sỉ", "The shop buys from a wholesaler.", "Cửa hàng mua từ một nhà bán sỉ.")
W("e-commerce", "n", "ˈiː kɑːmɜːrs", 4, "thương mại điện tử", "E-commerce has changed how people shop.", "Thương mại điện tử đã thay đổi cách mọi người mua sắm.")
W("free of charge", "phr", "friː əv tʃɑːrdʒ", 3, "miễn phí", "Delivery is free of charge.", "Giao hàng miễn phí.")
W("reasonable", "adj", "ˈriːznəbl", 3, "hợp lý (giá)", "The rent is quite reasonable.", "Tiền thuê nhà khá hợp lý.")

topic("travel", "Du lịch & di chuyển", "✈️", 9)
W("flight", "n", "flaɪt", 1, "chuyến bay", "Our flight leaves at 7 a.m.", "Chuyến bay của chúng tôi khởi hành lúc 7 giờ sáng.")
W("passenger", "n", "ˈpæsɪndʒər", 2, "hành khách", "All passengers must show their tickets.", "Tất cả hành khách phải xuất trình vé.")
W("luggage", "n", "ˈlʌɡɪdʒ", 2, "hành lý", "Please do not leave your luggage unattended.", "Vui lòng không để hành lý mà không trông coi.")
W("boarding pass", "n", "ˈbɔːrdɪŋ pæs", 2, "thẻ lên máy bay", "Have your boarding pass ready at the gate.", "Chuẩn bị sẵn thẻ lên máy bay ở cửa ra.")
W("departure", "n", "dɪˈpɑːrtʃər", 3, "sự khởi hành", "Check the departure time on the screen.", "Xem giờ khởi hành trên màn hình.", fam={"verb": "depart"})
W("arrival", "n", "əˈraɪvl", 3, "sự đến nơi", "The arrival hall is on the ground floor.", "Sảnh đến ở tầng trệt.", fam={"verb": "arrive"})
W("delayed", "adj", "dɪˈleɪd", 2, "bị hoãn, trễ", "The train was delayed by an hour.", "Tàu bị trễ một tiếng.")
W("cancel", "v", "ˈkænsl", 2, "hủy", "The flight was canceled because of the storm.", "Chuyến bay bị hủy vì bão.", fam={"noun": "cancellation"})
W("book", "v", "bʊk", 1, "đặt (vé, phòng)", "I booked a table for four.", "Tôi đã đặt bàn cho bốn người.", fam={"noun": "booking"})
W("reservation", "n", "ˌrezərˈveɪʃn", 3, "sự đặt chỗ trước", "I have a reservation under the name Nguyen.", "Tôi có đặt chỗ dưới tên Nguyễn.", fam={"verb": "reserve"})
W("itinerary", "n", "aɪˈtɪnəreri", 4, "lịch trình chuyến đi", "The travel agent emailed me the itinerary.", "Đại lý du lịch đã gửi email lịch trình cho tôi.")
W("destination", "n", "ˌdestɪˈneɪʃn", 3, "điểm đến", "Da Nang is a popular tourist destination.", "Đà Nẵng là điểm đến du lịch nổi tiếng.")
W("passport", "n", "ˈpæspɔːrt", 1, "hộ chiếu", "Don't forget your passport.", "Đừng quên hộ chiếu nhé.")
W("customs", "n", "ˈkʌstəmz", 3, "hải quan", "We went through customs quickly.", "Chúng tôi qua hải quan khá nhanh.")
W("round trip", "n", "ˌraʊnd ˈtrɪp", 3, "khứ hồi", "A round-trip ticket costs 300 dollars.", "Vé khứ hồi giá 300 đô la.", coll=["one-way ticket"])
W("fare", "n", "fer", 3, "giá vé (xe, tàu)", "Bus fares will rise next month.", "Giá vé xe buýt sẽ tăng vào tháng sau.")
W("commute", "v", "kəˈmjuːt", 4, "đi lại (giữa nhà và nơi làm)", "She commutes to work by train.", "Cô ấy đi làm bằng tàu.", fam={"noun": "commuter"})
W("platform", "n", "ˈplætfɔːrm", 2, "sân ga", "The train leaves from platform 3.", "Tàu khởi hành từ sân ga số 3.")
W("aisle", "n", "aɪl", 3, "lối đi (giữa các hàng ghế)", "I'd like an aisle seat, please.", "Tôi muốn ghế cạnh lối đi.")
W("souvenir", "n", "ˌsuːvəˈnɪr", 3, "quà lưu niệm", "We bought souvenirs at the night market.", "Chúng tôi mua quà lưu niệm ở chợ đêm.")
W("sightseeing", "n", "ˈsaɪtsiːɪŋ", 3, "việc tham quan", "We went sightseeing in Hanoi.", "Chúng tôi đi tham quan Hà Nội.")
W("tourist", "n", "ˈtʊrɪst", 1, "khách du lịch", "The beach is full of tourists in summer.", "Bãi biển đông khách du lịch vào mùa hè.", fam={"noun": "tourism"})
W("journey", "n", "ˈdʒɜːrni", 2, "chuyến đi, hành trình", "The journey takes about five hours.", "Hành trình mất khoảng năm tiếng.")
W("traffic jam", "n", "ˈtræfɪk dʒæm", 1, "tắc đường", "We were stuck in a traffic jam for an hour.", "Chúng tôi bị kẹt xe một tiếng.")
W("check in", "phr", "tʃek ɪn", 2, "làm thủ tục (lên máy bay/nhận phòng)", "You must check in two hours before the flight.", "Bạn phải làm thủ tục hai giờ trước chuyến bay.")
W("abroad", "adv", "əˈbrɔːd", 3, "ở/ra nước ngoài", "She plans to study abroad.", "Cô ấy dự định đi du học.")
W("accommodation", "n", "əˌkɑːməˈdeɪʃn", 4, "chỗ ở", "The price includes flights and accommodation.", "Giá đã bao gồm vé máy bay và chỗ ở.")
W("guide", "n", "ɡaɪd", 2, "hướng dẫn viên", "Our guide spoke excellent English.", "Hướng dẫn viên của chúng tôi nói tiếng Anh rất giỏi.")
W("map", "n", "mæp", 1, "bản đồ", "Can you show me on the map?", "Bạn chỉ cho tôi trên bản đồ được không?")
W("baggage claim", "n", "ˈbæɡɪdʒ kleɪm", 3, "khu nhận hành lý", "Meet me at baggage claim.", "Gặp tôi ở khu nhận hành lý nhé.")

topic("hospitality", "Khách sạn & nhà hàng", "🍽️", 0)
W("guest", "n", "ɡest", 1, "khách (khách sạn, tiệc)", "Hotel guests can use the pool for free.", "Khách của khách sạn được dùng hồ bơi miễn phí.")
W("vacant", "adj", "ˈveɪkənt", 4, "trống (phòng, ghế)", "Are there any vacant rooms tonight?", "Tối nay còn phòng trống không?")
W("check out", "phr", "tʃek aʊt", 2, "trả phòng", "Guests must check out by noon.", "Khách phải trả phòng trước buổi trưa.")
W("front desk", "n", "frʌnt desk", 2, "quầy lễ tân", "Please ask at the front desk.", "Vui lòng hỏi ở quầy lễ tân.")
W("menu", "n", "ˈmenjuː", 1, "thực đơn", "Could I see the menu, please?", "Cho tôi xem thực đơn được không?")
W("dish", "n", "dɪʃ", 2, "món ăn", "Pho is a famous Vietnamese dish.", "Phở là món ăn nổi tiếng của Việt Nam.")
W("order", "v", "ˈɔːrdər", 1, "gọi (món), đặt hàng", "Are you ready to order?", "Quý khách gọi món chưa ạ?")
W("waiter", "n", "ˈweɪtər", 1, "bồi bàn (nam)", "The waiter brought us some water.", "Người phục vụ mang nước cho chúng tôi.")
W("chef", "n", "ʃef", 2, "đầu bếp", "The chef cooks with local ingredients.", "Đầu bếp nấu với nguyên liệu địa phương.")
W("ingredient", "n", "ɪnˈɡriːdiənt", 3, "nguyên liệu (nấu ăn)", "Fresh ingredients make the food taste better.", "Nguyên liệu tươi làm món ăn ngon hơn.")
W("vegetarian", "adj", "ˌvedʒəˈteriən", 3, "chay", "Do you have any vegetarian dishes?", "Ở đây có món chay không?")
W("tip", "n", "tɪp", 2, "tiền boa", "We left a tip for the waiter.", "Chúng tôi để lại tiền boa cho người phục vụ.")
W("serve", "v", "sɜːrv", 2, "phục vụ", "Breakfast is served from 6 to 10.", "Bữa sáng được phục vụ từ 6 đến 10 giờ.", fam={"noun": "service"})
W("amenity", "n", "əˈmenəti", 5, "tiện nghi", "The hotel's amenities include a gym and a spa.", "Tiện nghi khách sạn gồm phòng tập và spa.")
W("housekeeping", "n", "ˈhaʊskiːpɪŋ", 4, "bộ phận buồng phòng", "Housekeeping cleans the rooms every day.", "Bộ phận buồng phòng dọn phòng mỗi ngày.")
W("suite", "n", "swiːt", 4, "phòng hạng sang (nhiều gian)", "They stayed in a suite with a sea view.", "Họ ở phòng hạng sang nhìn ra biển.")
W("complimentary", "adj", "ˌkɑːmplɪˈmentri", 5, "miễn phí (tặng kèm)", "Guests receive a complimentary breakfast.", "Khách được tặng bữa sáng miễn phí.")
W("cuisine", "n", "kwɪˈziːn", 4, "ẩm thực", "This restaurant serves Thai cuisine.", "Nhà hàng này phục vụ ẩm thực Thái.")
W("appetizer", "n", "ˈæpɪtaɪzər", 4, "món khai vị", "We ordered spring rolls as an appetizer.", "Chúng tôi gọi chả giò làm món khai vị.")
W("dessert", "n", "dɪˈzɜːrt", 2, "món tráng miệng", "Would you like some dessert?", "Bạn có muốn dùng tráng miệng không?")
W("beverage", "n", "ˈbevərɪdʒ", 4, "đồ uống", "Beverages are not included in the price.", "Đồ uống không bao gồm trong giá.")
W("reserve", "v", "rɪˈzɜːrv", 3, "đặt trước", "I'd like to reserve a table for two.", "Tôi muốn đặt bàn cho hai người.")
W("cater", "v", "ˈkeɪtər", 5, "cung cấp đồ ăn (cho sự kiện)", "A local company catered the wedding.", "Một công ty địa phương phụ trách tiệc cưới.", fam={"noun": "catering"})
W("room service", "n", "ruːm ˈsɜːrvɪs", 3, "dịch vụ phòng", "I ordered dinner from room service.", "Tôi gọi bữa tối từ dịch vụ phòng.")
W("lobby", "n", "ˈlɑːbi", 3, "sảnh", "I'll meet you in the hotel lobby.", "Tôi sẽ gặp bạn ở sảnh khách sạn.")
W("spicy", "adj", "ˈspaɪsi", 2, "cay", "This soup is too spicy for me.", "Món súp này quá cay với tôi.")
W("delicious", "adj", "dɪˈlɪʃəs", 1, "ngon", "The food was delicious.", "Đồ ăn rất ngon.")
W("portion", "n", "ˈpɔːrʃn", 4, "khẩu phần", "The portions here are very large.", "Khẩu phần ở đây rất lớn.")
W("host", "v", "hoʊst", 3, "tổ chức, đăng cai", "The hotel will host the awards dinner.", "Khách sạn sẽ tổ chức tiệc trao giải.")
W("recommend", "v", "ˌrekəˈmend", 3, "giới thiệu, khuyên dùng", "Can you recommend a good restaurant?", "Bạn có thể giới thiệu một nhà hàng ngon không?", fam={"noun": "recommendation"})

topic("events", "Sự kiện & hội nghị", "🎤", 1)
W("conference", "n", "ˈkɑːnfərəns", 3, "hội nghị", "The conference will be held in Hanoi.", "Hội nghị sẽ được tổ chức tại Hà Nội.")
W("seminar", "n", "ˈsemɪnɑːr", 3, "hội thảo", "I attended a seminar on online marketing.", "Tôi đã tham dự một hội thảo về marketing trực tuyến.")
W("workshop", "n", "ˈwɜːrkʃɑːp", 3, "buổi hội thảo thực hành", "The workshop teaches basic design skills.", "Buổi workshop dạy kỹ năng thiết kế cơ bản.")
W("venue", "n", "ˈvenjuː", 4, "địa điểm (tổ chức)", "The venue can hold 500 people.", "Địa điểm có sức chứa 500 người.")
W("register", "v", "ˈredʒɪstər", 3, "đăng ký", "Please register before May 1.", "Vui lòng đăng ký trước ngày 1 tháng Năm.", fam={"noun": "registration"})
W("participant", "n", "pɑːrˈtɪsɪpənt", 3, "người tham gia", "Each participant will receive a certificate.", "Mỗi người tham gia sẽ nhận một chứng nhận.", fam={"verb": "participate"})
W("speaker", "n", "ˈspiːkər", 2, "diễn giả", "The main speaker is a famous scientist.", "Diễn giả chính là một nhà khoa học nổi tiếng.")
W("presentation", "n", "ˌpriːzenˈteɪʃn", 3, "bài thuyết trình", "She gave a presentation on sales results.", "Cô ấy thuyết trình về kết quả kinh doanh.", fam={"verb": "present"})
W("organize", "v", "ˈɔːrɡənaɪz", 2, "tổ chức", "Who is organizing the company trip?", "Ai đang tổ chức chuyến đi của công ty?", fam={"noun": "organization", "noun2": "organizer"})
W("exhibition", "n", "ˌeksɪˈbɪʃn", 3, "triển lãm", "The art exhibition opens on Saturday.", "Triển lãm nghệ thuật khai mạc vào thứ Bảy.", fam={"verb": "exhibit"})
W("trade fair", "n", "treɪd fer", 4, "hội chợ thương mại", "We will have a booth at the trade fair.", "Chúng tôi sẽ có một gian hàng ở hội chợ thương mại.")
W("banquet", "n", "ˈbæŋkwɪt", 5, "tiệc lớn, yến tiệc", "A banquet was held in honor of the winners.", "Một bữa tiệc được tổ chức để vinh danh người thắng cuộc.")
W("invitation", "n", "ˌɪnvɪˈteɪʃn", 2, "lời mời, thiệp mời", "Thank you for the invitation.", "Cảm ơn lời mời của bạn.", fam={"verb": "invite"})
W("ceremony", "n", "ˈserəmoʊni", 3, "buổi lễ", "The opening ceremony starts at 6 p.m.", "Lễ khai mạc bắt đầu lúc 6 giờ tối.")
W("keynote", "n", "ˈkiːnoʊt", 5, "bài phát biểu chính", "The CEO will give the keynote speech.", "Giám đốc điều hành sẽ phát biểu chính.")
W("schedule", "v", "ˈskedʒuːl", 3, "lên lịch", "The meeting is scheduled for Monday.", "Cuộc họp được lên lịch vào thứ Hai.")
W("attendee", "n", "əˌtenˈdiː", 4, "người tham dự", "All attendees must wear a name badge.", "Tất cả người tham dự phải đeo thẻ tên.")
W("booth", "n", "buːθ", 4, "gian hàng (hội chợ)", "Visit our booth in Hall B.", "Hãy ghé gian hàng của chúng tôi ở Sảnh B.")
W("catering", "n", "ˈkeɪtərɪŋ", 4, "dịch vụ ăn uống (cho sự kiện)", "Catering is included in the ticket price.", "Dịch vụ ăn uống đã bao gồm trong giá vé.")
W("audience", "n", "ˈɔːdiəns", 3, "khán giả", "The audience clapped loudly.", "Khán giả vỗ tay rất to.")
W("anniversary", "n", "ˌænɪˈvɜːrsəri", 3, "lễ kỷ niệm", "The company celebrates its 20th anniversary this year.", "Công ty kỷ niệm 20 năm thành lập năm nay.")
W("celebrate", "v", "ˈselɪbreɪt", 2, "ăn mừng, kỷ niệm", "We celebrated the end of the project with dinner.", "Chúng tôi ăn tối mừng kết thúc dự án.", fam={"noun": "celebration"})
W("announce", "v", "əˈnaʊns", 3, "thông báo", "The winners will be announced tonight.", "Người thắng cuộc sẽ được công bố tối nay.", fam={"noun": "announcement"})
W("award", "n", "əˈwɔːrd", 3, "giải thưởng", "She won an award for her design.", "Cô ấy giành giải thưởng cho thiết kế của mình.")
W("brochure", "n", "broʊˈʃʊr", 3, "tờ giới thiệu", "The event brochure lists all the speakers.", "Tờ giới thiệu sự kiện liệt kê tất cả diễn giả.")
W("in advance", "phr", "ɪn ədˈvæns", 3, "trước (thời hạn)", "Tickets must be bought in advance.", "Vé phải được mua trước.")
W("session", "n", "ˈseʃn", 3, "phiên, buổi", "The afternoon session begins at 2 p.m.", "Phiên buổi chiều bắt đầu lúc 2 giờ.")
W("host", "n", "hoʊst", 3, "chủ nhà, người dẫn chương trình", "The host welcomed all the guests.", "Người dẫn chương trình chào đón tất cả khách mời.")
W("postpone", "v", "poʊstˈpoʊn", 3, "hoãn", "The concert was postponed because of rain.", "Buổi hòa nhạc bị hoãn vì mưa.")
W("venue capacity", "n", "ˈvenjuː kəˈpæsəti", 5, "sức chứa địa điểm", "Ticket sales are limited by venue capacity.", "Số vé bán giới hạn theo sức chứa địa điểm.")
