from lib import topic, W, S

topic("social", "Mạng xã hội & đời sống số", "📱", 0)
W("post", "n", "poʊst", 1, "bài đăng", "Your post got 500 likes!", "Bài đăng của bạn được 500 lượt thích!")
S("v", "đăng (lên mạng)", "She posts a new photo every day.", "Cô ấy đăng ảnh mới mỗi ngày.")
W("share", "v", "ʃer", 1, "chia sẻ", "Share this video with your friends.", "Chia sẻ video này với bạn bè nhé.")
W("comment", "n", "ˈkɑːment", 2, "bình luận", "Leave a comment below.", "Để lại bình luận bên dưới nhé.")
W("follower", "n", "ˈfɑːloʊər", 2, "người theo dõi", "He has over 10,000 followers.", "Anh ấy có hơn 10.000 người theo dõi.", fam={"verb": "follow"})
W("influencer", "n", "ˈɪnfluənsər", 3, "người có sức ảnh hưởng (trên mạng)", "Many brands pay influencers to promote products.", "Nhiều nhãn hàng trả tiền cho người có ảnh hưởng để quảng bá sản phẩm.")
W("hashtag", "n", "ˈhæʃtæɡ", 2, "thẻ bắt đầu bằng #", "Use the hashtag #learnenglish.", "Dùng hashtag #learnenglish nhé.")
W("selfie", "n", "ˈselfi", 1, "ảnh tự chụp", "Let's take a selfie!", "Chụp ảnh selfie đi!")
W("notification", "n", "ˌnoʊtɪfɪˈkeɪʃn", 3, "thông báo (trên điện thoại)", "I turned off notifications to focus.", "Tôi tắt thông báo để tập trung.", fam={"verb": "notify"})
W("scroll", "v", "skroʊl", 3, "lướt (màn hình)", "I spent an hour scrolling through videos.", "Tôi lướt video mất cả tiếng.")
W("block", "v", "blɑːk", 3, "chặn", "She blocked him on every app.", "Cô ấy chặn anh ta trên mọi ứng dụng.")
W("unfollow", "v", "ʌnˈfɑːloʊ", 3, "bỏ theo dõi", "I unfollowed accounts that made me feel bad.", "Tôi bỏ theo dõi những tài khoản làm tôi thấy tệ.")
W("profile", "n", "ˈproʊfaɪl", 3, "trang cá nhân, hồ sơ", "Update your profile picture.", "Cập nhật ảnh đại diện của bạn đi.")
W("username", "n", "ˈjuːzərneɪm", 2, "tên người dùng", "Choose a username and password.", "Chọn tên người dùng và mật khẩu.")
W("screenshot", "n", "ˈskriːnʃɑːt", 2, "ảnh chụp màn hình", "Send me a screenshot of the error.", "Gửi mình ảnh chụp màn hình lỗi nhé.")
W("emoji", "n", "ɪˈmoʊdʒi", 1, "biểu tượng cảm xúc", "She replied with a heart emoji.", "Cô ấy trả lời bằng một emoji trái tim.")
W("livestream", "n", "ˈlaɪvstriːm", 3, "buổi phát trực tiếp", "They sell clothes on livestreams.", "Họ bán quần áo qua livestream.")
W("content creator", "n", "ˈkɑːntent kriˈeɪtər", 3, "nhà sáng tạo nội dung", "She quit her job to become a content creator.", "Cô ấy nghỉ việc để làm nhà sáng tạo nội dung.")
W("go viral", "phr", "ɡoʊ ˈvaɪrəl", 3, "lan truyền chóng mặt", "His dance video went viral.", "Video nhảy của anh ấy lan truyền chóng mặt.")
W("online", "adv", "ˌɑːnˈlaɪn", 1, "trực tuyến", "I buy most things online.", "Tôi mua hầu hết đồ trên mạng.")
W("offline", "adv", "ˌɔːfˈlaɪn", 2, "ngoại tuyến", "This app works offline.", "Ứng dụng này dùng được khi không có mạng.")
W("screen time", "n", "skriːn taɪm", 3, "thời gian dùng màn hình", "I'm trying to reduce my screen time.", "Tôi đang cố giảm thời gian dùng điện thoại.")
W("digital detox", "n", "ˈdɪdʒɪtl ˈdiːtɑːks", 4, "cai nghiện thiết bị số", "I did a digital detox for a whole weekend.", "Tôi 'cai' điện thoại suốt một cuối tuần.")
W("privacy", "n", "ˈpraɪvəsi", 3, "quyền riêng tư", "Check your privacy settings.", "Kiểm tra cài đặt quyền riêng tư của bạn.", fam={"adj": "private"})
W("scam", "n", "skæm", 3, "trò lừa đảo", "That message is a scam. Don't click the link.", "Tin nhắn đó là lừa đảo. Đừng bấm vào đường dẫn.")
W("reply", "v", "rɪˈplaɪ", 2, "trả lời", "Sorry for the late reply!", "Xin lỗi vì trả lời muộn!")
S("n", "câu trả lời", "I'm still waiting for her reply.", "Tôi vẫn đang đợi cô ấy trả lời.")
W("video call", "n", "ˈvɪdioʊ kɔːl", 2, "cuộc gọi video", "We have a video call with grandma every Sunday.", "Chúng tôi gọi video cho bà mỗi Chủ nhật.")
W("charger", "n", "ˈtʃɑːrdʒər", 2, "bộ sạc", "Can I borrow your phone charger?", "Cho mình mượn sạc điện thoại được không?")
W("battery", "n", "ˈbætəri", 2, "pin", "My battery is almost dead.", "Điện thoại tôi sắp hết pin.")
W("app", "n", "æp", 1, "ứng dụng", "This app helps me learn English.", "Ứng dụng này giúp tôi học tiếng Anh.")
W("algorithm", "n", "ˈælɡərɪðəm", 5, "thuật toán", "The algorithm shows you videos you might like.", "Thuật toán hiển thị những video bạn có thể thích.")

topic("expressions", "Cách nói tự nhiên (giao tiếp)", "💬", 1)
W("no worries", "idiom", "noʊ ˈwɜːriz", 1, "không sao đâu", "— Sorry I'm late! — No worries.", "— Xin lỗi mình đến muộn! — Không sao đâu.")
W("my bad", "idiom", "maɪ bæd", 2, "lỗi của mình (thân mật)", "My bad, I sent it to the wrong person.", "Lỗi mình, mình gửi nhầm người.")
W("fair enough", "idiom", "fer ɪˈnʌf", 3, "cũng hợp lý (chấp nhận)", "— I'm too tired to go. — Fair enough.", "— Mình mệt quá không đi được. — Ừ, cũng phải.")
W("it's up to you", "idiom", "ɪts ʌp tuː juː", 2, "tùy bạn", "Pizza or noodles? It's up to you.", "Pizza hay mì? Tùy bạn.")
W("I'm down", "idiom", "aɪm daʊn", 3, "mình tham gia, mình ok (thân mật)", "— Want to get bubble tea? — I'm down!", "— Đi uống trà sữa không? — Đi luôn!")
W("hang on", "phr", "hæŋ ɑːn", 2, "đợi chút", "Hang on, I'll be right there.", "Đợi chút, mình tới ngay.")
W("no way", "idiom", "noʊ weɪ", 2, "không đời nào; không thể tin được", "No way! You passed with 990?", "Không thể nào! Bạn được 990 điểm á?")
W("for real", "idiom", "fɔːr riːl", 3, "thật á, thật sự", "Are you leaving for real?", "Bạn đi thật à?")
W("same here", "idiom", "seɪm hɪr", 2, "mình cũng vậy", "— I'm so hungry. — Same here.", "— Đói quá. — Mình cũng thế.")
W("what's up", "idiom", "wʌts ʌp", 1, "có chuyện gì thế; chào (thân mật)", "Hey, what's up?", "Ê, có gì mới không?")
W("take it easy", "idiom", "teɪk ɪt ˈiːzi", 2, "bình tĩnh, thư giãn đi", "Take it easy. It's just a practice test.", "Thư giãn đi. Chỉ là bài thi thử thôi mà.")
W("good luck", "idiom", "ɡʊd lʌk", 1, "chúc may mắn", "Good luck with your exam!", "Chúc thi tốt nhé!")
W("you got this", "idiom", "juː ɡɑːt ðɪs", 2, "bạn làm được mà", "Don't worry, you got this!", "Đừng lo, bạn làm được mà!")
W("long time no see", "idiom", "lɔːŋ taɪm noʊ siː", 2, "lâu rồi không gặp", "Long time no see! How have you been?", "Lâu rồi không gặp! Dạo này bạn thế nào?")
W("catch up", "phr", "kætʃ ʌp", 3, "hàn huyên, cập nhật tin; đuổi kịp", "Let's grab coffee and catch up.", "Đi cà phê rồi tám chuyện đi.")
W("my treat", "idiom", "maɪ triːt", 3, "để mình mời", "Put your wallet away. It's my treat.", "Cất ví đi. Để mình mời.")
W("I'm in", "idiom", "aɪm ɪn", 2, "mình tham gia", "A trip to Da Lat? I'm in!", "Đi Đà Lạt á? Cho mình theo với!")
W("that makes sense", "idiom", "ðæt meɪks sens", 3, "nghe hợp lý đấy", "Oh, that makes sense now.", "À, giờ thì hiểu rồi.")
W("I'm on my way", "idiom", "aɪm ɑːn maɪ weɪ", 2, "mình đang tới", "I'm on my way. See you in ten minutes.", "Mình đang tới. Mười phút nữa gặp.")
W("never mind", "idiom", "ˈnevər maɪnd", 2, "thôi bỏ đi, không sao", "Never mind, I'll do it myself.", "Thôi bỏ đi, mình tự làm.")
W("how come", "idiom", "haʊ kʌm", 3, "sao lại (thân mật)", "How come you're still awake?", "Sao giờ này bạn còn thức?")
W("by the way", "idiom", "baɪ ðə weɪ", 2, "nhân tiện", "By the way, your English is great.", "Nhân tiện, tiếng Anh của bạn hay lắm.")
W("I'm kidding", "idiom", "aɪm ˈkɪdɪŋ", 2, "mình đùa thôi", "Relax, I'm kidding!", "Thư giãn đi, mình đùa thôi!")
W("sounds good", "idiom", "saʊndz ɡʊd", 1, "nghe được đấy", "— Meet at 7? — Sounds good.", "— Gặp lúc 7 giờ nhé? — Được đấy.")
W("cheers", "idiom", "tʃɪrz", 2, "cảm ơn (Anh-Anh); chúc mừng (khi cụng ly)", "Cheers for the help, mate!", "Cảm ơn đã giúp nhé, bạn!")
W("hit me up", "idiom", "hɪt miː ʌp", 4, "liên lạc với mình nhé (thân mật)", "Hit me up when you're free.", "Rảnh thì nhắn mình nhé.")
W("low-key", "adj", "ˌloʊ ˈkiː", 4, "nhẹ nhàng, kín đáo; (thân mật) hơi hơi", "We had a low-key birthday dinner at home.", "Chúng tôi ăn sinh nhật nhẹ nhàng ở nhà.")
W("awesome", "adj", "ˈɔːsəm", 1, "tuyệt vời", "The trip was awesome!", "Chuyến đi tuyệt vời!")
W("chill", "v", "tʃɪl", 3, "thư giãn (thân mật)", "We just chilled at home all day.", "Bọn mình nằm nhà chill cả ngày.")
S("adj", "thoải mái, dễ chịu (thân mật)", "My boss is pretty chill.", "Sếp mình khá dễ tính.")
W("totally", "adv", "ˈtoʊtəli", 2, "hoàn toàn (nhấn mạnh)", "You're totally right.", "Bạn hoàn toàn đúng.")

topic("phrasal", "Cụm động từ thông dụng", "🔗", 2)
W("give up", "phr", "ɡɪv ʌp", 2, "từ bỏ", "Don't give up! You're almost there.", "Đừng bỏ cuộc! Bạn sắp tới đích rồi.")
W("look for", "phr", "lʊk fɔːr", 1, "tìm kiếm", "I'm looking for my keys.", "Tôi đang tìm chìa khóa.")
W("look forward to", "phr", "lʊk ˈfɔːrwərd tuː", 3, "mong chờ", "I look forward to hearing from you.", "Tôi mong nhận được hồi âm của bạn.")
W("find out", "phr", "faɪnd aʊt", 2, "tìm ra, phát hiện", "I found out the truth yesterday.", "Hôm qua tôi đã phát hiện ra sự thật.")
W("turn on", "phr", "tɜːrn ɑːn", 1, "bật", "Turn on the lights, please.", "Làm ơn bật đèn lên.")
W("turn off", "phr", "tɜːrn ɔːf", 1, "tắt", "Turn off your phone in the cinema.", "Tắt điện thoại trong rạp chiếu phim.")
W("turn down", "phr", "tɜːrn daʊn", 3, "từ chối; vặn nhỏ", "She turned down the job offer.", "Cô ấy từ chối lời mời làm việc.")
W("set up", "phr", "set ʌp", 3, "thành lập; thiết lập", "They set up a small company in 2020.", "Họ thành lập một công ty nhỏ năm 2020.")
W("figure out", "phr", "ˈfɪɡjər aʊt", 3, "hiểu ra, tìm ra cách", "I can't figure out this math problem.", "Tôi không giải được bài toán này.")
W("come up with", "phr", "kʌm ʌp wɪð", 4, "nghĩ ra", "She came up with a great idea.", "Cô ấy nghĩ ra một ý tưởng tuyệt vời.")
W("put off", "phr", "pʊt ɔːf", 3, "trì hoãn", "Stop putting off your homework!", "Đừng trì hoãn bài tập nữa!")
W("call off", "phr", "kɔːl ɔːf", 3, "hủy bỏ", "The match was called off because of rain.", "Trận đấu bị hủy vì mưa.")
W("carry on", "phr", "ˈkæri ɑːn", 3, "tiếp tục", "Carry on with your work.", "Cứ tiếp tục công việc đi.")
W("fill in", "phr", "fɪl ɪn", 2, "điền vào", "Please fill in this form.", "Vui lòng điền vào mẫu đơn này.")
W("pick up", "phr", "pɪk ʌp", 2, "đón; nhặt lên; học lỏm", "I'll pick you up at 7.", "Mình sẽ đón bạn lúc 7 giờ.")
S("phr", "học được (một cách tự nhiên)", "I picked up some Korean from TV dramas.", "Tôi học lỏm được ít tiếng Hàn từ phim truyền hình.")
W("show up", "phr", "ʃoʊ ʌp", 3, "xuất hiện, có mặt", "He didn't show up to the meeting.", "Anh ấy không có mặt ở cuộc họp.")
W("get over", "phr", "ɡet ˈoʊvər", 4, "vượt qua (ốm, buồn)", "It took her months to get over the breakup.", "Cô ấy mất nhiều tháng để vượt qua chuyện chia tay.")
W("break down", "phr", "breɪk daʊn", 3, "hỏng (máy); suy sụp", "My car broke down on the highway.", "Xe tôi bị hỏng trên đường cao tốc.")
W("go on", "phr", "ɡoʊ ɑːn", 2, "tiếp tục; xảy ra", "What's going on here?", "Có chuyện gì ở đây vậy?")
W("hold on", "phr", "hoʊld ɑːn", 2, "giữ máy, chờ chút", "Hold on, let me check.", "Chờ chút, để mình kiểm tra.")
W("keep up with", "phr", "kiːp ʌp wɪð", 4, "theo kịp", "It's hard to keep up with new technology.", "Thật khó theo kịp công nghệ mới.")
W("run into", "phr", "rʌn ˈɪntuː", 3, "tình cờ gặp", "I ran into my old teacher at the mall.", "Tôi tình cờ gặp cô giáo cũ ở trung tâm thương mại.")
W("check out", "phr", "tʃek aʊt", 2, "xem thử; trả phòng", "Check out this new song!", "Nghe thử bài hát mới này đi!")
W("sign up", "phr", "saɪn ʌp", 2, "đăng ký", "I signed up for a yoga class.", "Tôi đăng ký một lớp yoga.")
W("work on", "phr", "wɜːrk ɑːn", 2, "làm, cải thiện (cái gì)", "I need to work on my pronunciation.", "Tôi cần luyện phát âm thêm.")
W("end up", "phr", "end ʌp", 3, "rốt cuộc, cuối cùng thì", "We ended up staying home.", "Rốt cuộc chúng tôi ở nhà.")
W("deal with", "phr", "diːl wɪð", 3, "giải quyết, đối phó", "How do you deal with stress?", "Bạn đối phó với căng thẳng thế nào?")
W("point out", "phr", "pɔɪnt aʊt", 4, "chỉ ra", "My teacher pointed out a few mistakes.", "Cô giáo chỉ ra vài lỗi sai.")
W("cut down on", "phr", "kʌt daʊn ɑːn", 4, "cắt giảm", "I'm trying to cut down on sugar.", "Tôi đang cố giảm đường.")
W("get rid of", "phr", "ɡet rɪd əv", 4, "loại bỏ, vứt bỏ", "I got rid of all my old clothes.", "Tôi đã bỏ hết quần áo cũ.")

topic("idioms", "Thành ngữ thú vị", "🎯", 3)
W("piece of cake", "idiom", "piːs əv keɪk", 2, "dễ như ăn kẹo", "The test was a piece of cake.", "Bài kiểm tra dễ như ăn kẹo.")
W("break the ice", "idiom", "breɪk ðə aɪs", 3, "phá vỡ sự ngượng ngùng ban đầu", "He told a joke to break the ice.", "Anh ấy kể chuyện cười để phá tan không khí ngượng ngùng.")
W("hit the books", "idiom", "hɪt ðə bʊks", 3, "học bài chăm chỉ", "Exams are next week. Time to hit the books!", "Tuần sau thi rồi. Đến lúc cày bài thôi!")
W("under the weather", "idiom", "ˈʌndər ðə ˈweðər", 3, "không khỏe, hơi mệt", "I'm feeling a bit under the weather today.", "Hôm nay tôi thấy hơi mệt trong người.")
W("once in a blue moon", "idiom", "wʌns ɪn ə bluː muːn", 4, "hiếm khi, năm thì mười họa", "I eat fast food once in a blue moon.", "Năm thì mười họa tôi mới ăn đồ ăn nhanh.")
W("cost an arm and a leg", "idiom", "kɔːst ən ɑːrm ənd ə leɡ", 4, "đắt cắt cổ", "That phone costs an arm and a leg.", "Cái điện thoại đó đắt cắt cổ.")
W("hit the nail on the head", "idiom", "hɪt ðə neɪl ɑːn ðə hed", 5, "nói trúng phóc", "You hit the nail on the head!", "Bạn nói trúng phóc!")
W("the ball is in your court", "idiom", "ðə bɔːl ɪz ɪn jɔːr kɔːrt", 5, "đến lượt bạn quyết định", "I've made my offer. The ball is in your court.", "Tôi đã đưa ra đề nghị. Giờ đến lượt bạn quyết định.")
W("better late than never", "idiom", "ˈbetər leɪt ðæn ˈnevər", 3, "muộn còn hơn không", "You started learning at 40? Better late than never!", "Bạn bắt đầu học lúc 40 tuổi à? Muộn còn hơn không!")
W("spill the beans", "idiom", "spɪl ðə biːnz", 4, "lỡ tiết lộ bí mật", "Who spilled the beans about the surprise party?", "Ai đã để lộ bí mật về bữa tiệc bất ngờ vậy?")
W("on cloud nine", "idiom", "ɑːn klaʊd naɪn", 4, "vui như trên mây", "She's been on cloud nine since she got the job.", "Cô ấy vui như trên mây từ khi được nhận việc.")
W("a blessing in disguise", "idiom", "ə ˈblesɪŋ ɪn dɪsˈɡaɪz", 5, "trong cái rủi có cái may", "Missing the bus was a blessing in disguise.", "Lỡ chuyến xe buýt hóa ra lại là may.")
W("call it a day", "idiom", "kɔːl ɪt ə deɪ", 3, "nghỉ thôi, kết thúc công việc hôm nay", "It's 9 p.m. Let's call it a day.", "9 giờ tối rồi. Nghỉ thôi.")
W("get the hang of", "idiom", "ɡet ðə hæŋ əv", 4, "quen tay, nắm được cách làm", "You'll get the hang of it soon.", "Bạn sẽ sớm quen thôi.")
W("in hot water", "idiom", "ɪn hɑːt ˈwɔːtər", 5, "gặp rắc rối", "He's in hot water for missing the deadline.", "Anh ấy gặp rắc rối vì trễ hạn.")
W("keep an eye on", "idiom", "kiːp ən aɪ ɑːn", 3, "để mắt tới, trông chừng", "Can you keep an eye on my bag?", "Bạn trông giúp mình cái túi nhé?")
W("let the cat out of the bag", "idiom", "let ðə kæt aʊt əv ðə bæɡ", 5, "để lộ bí mật", "Don't let the cat out of the bag!", "Đừng để lộ bí mật nhé!")
W("practice makes perfect", "idiom", "ˈpræktɪs meɪks ˈpɜːrfɪkt", 2, "có công mài sắt có ngày nên kim", "Keep going. Practice makes perfect!", "Cố lên. Có công mài sắt có ngày nên kim!")
W("time flies", "idiom", "taɪm flaɪz", 2, "thời gian trôi nhanh quá", "Time flies when you're having fun.", "Vui thì thời gian trôi nhanh lắm.")
W("easier said than done", "idiom", "ˈiːziər sed ðæn dʌn", 3, "nói thì dễ, làm mới khó", "Waking up at 5 a.m. is easier said than done.", "Dậy lúc 5 giờ sáng nói thì dễ, làm mới khó.")
W("on the same page", "idiom", "ɑːn ðə seɪm peɪdʒ", 4, "cùng quan điểm, hiểu ý nhau", "Let's make sure we're all on the same page.", "Hãy đảm bảo tất cả chúng ta hiểu ý nhau.")
W("think outside the box", "idiom", "θɪŋk ˌaʊtˈsaɪd ðə bɑːks", 4, "suy nghĩ sáng tạo, khác lối mòn", "We need to think outside the box.", "Chúng ta cần suy nghĩ sáng tạo hơn.")
W("pull someone's leg", "idiom", "pʊl ˈsʌmwʌnz leɡ", 5, "trêu đùa ai", "Relax, I'm just pulling your leg.", "Thư giãn đi, mình chỉ trêu bạn thôi.")
W("a piece of advice", "phr", "ə piːs əv ədˈvaɪs", 3, "một lời khuyên", "Let me give you a piece of advice.", "Để mình cho bạn một lời khuyên.")
W("burn the midnight oil", "idiom", "bɜːrn ðə ˈmɪdnaɪt ɔɪl", 5, "thức khuya làm việc/học", "She burned the midnight oil to finish the report.", "Cô ấy thức khuya để hoàn thành báo cáo.")
W("feel blue", "idiom", "fiːl bluː", 4, "cảm thấy buồn", "I always feel blue on rainy days.", "Tôi luôn thấy buồn vào những ngày mưa.")
W("rain cats and dogs", "idiom", "reɪn kæts ənd dɔːɡz", 4, "mưa như trút nước", "Take an umbrella. It's raining cats and dogs.", "Mang ô đi. Trời mưa như trút nước.")
W("see eye to eye", "idiom", "siː aɪ tuː aɪ", 5, "đồng quan điểm", "We don't always see eye to eye.", "Không phải lúc nào chúng tôi cũng đồng quan điểm.")
W("go the extra mile", "idiom", "ɡoʊ ðə ˈekstrə maɪl", 5, "cố gắng hơn mức cần thiết", "Great staff always go the extra mile.", "Nhân viên giỏi luôn nỗ lực hơn mong đợi.")
W("learn by heart", "idiom", "lɜːrn baɪ hɑːrt", 3, "học thuộc lòng", "We had to learn the poem by heart.", "Chúng tôi phải học thuộc bài thơ.")
