from lib import topic, W, S

topic("family", "Gia đình & các mối quan hệ", "👨‍👩‍👧", 0)
W("parents", "n", "ˈperənts", 1, "bố mẹ", "My parents live in Hue.", "Bố mẹ tôi sống ở Huế.")
W("sibling", "n", "ˈsɪblɪŋ", 3, "anh chị em ruột", "Do you have any siblings?", "Bạn có anh chị em ruột không?")
W("cousin", "n", "ˈkʌzn", 2, "anh chị em họ", "My cousin is studying in Canada.", "Anh họ tôi đang du học Canada.")
W("niece", "n", "niːs", 3, "cháu gái (con anh chị em)", "My niece is five years old.", "Cháu gái tôi năm tuổi.")
W("nephew", "n", "ˈnefjuː", 3, "cháu trai (con anh chị em)", "I bought a toy for my nephew.", "Tôi mua đồ chơi cho cháu trai.")
W("grandparents", "n", "ˈɡrænperənts", 1, "ông bà", "We visit our grandparents every Tet.", "Chúng tôi thăm ông bà mỗi dịp Tết.")
W("husband", "n", "ˈhʌzbənd", 1, "chồng", "Her husband is a teacher.", "Chồng cô ấy là giáo viên.")
W("wife", "n", "waɪf", 1, "vợ", "His wife works at a hospital.", "Vợ anh ấy làm ở bệnh viện.")
W("relative", "n", "ˈrelətɪv", 3, "họ hàng", "All our relatives came to the wedding.", "Tất cả họ hàng đều đến dự đám cưới.")
S("adj", "tương đối", "The test was relatively easy.", "Bài kiểm tra tương đối dễ.")
W("raise", "v", "reɪz", 3, "nuôi nấng; nâng lên", "She raised three children on her own.", "Cô ấy một mình nuôi ba đứa con.")
S("n", "sự tăng lương", "He asked his boss for a raise.", "Anh ấy xin sếp tăng lương.")
W("bring up", "phr", "brɪŋ ʌp", 3, "nuôi dạy; nêu ra (chủ đề)", "I was brought up by my grandmother.", "Tôi được bà nuôi lớn.")
W("get married", "phr", "ɡet ˈmærid", 2, "kết hôn", "They got married last spring.", "Họ kết hôn vào mùa xuân năm ngoái.")
W("divorce", "n", "dɪˈvɔːrs", 4, "sự ly hôn", "Their divorce was difficult for the kids.", "Cuộc ly hôn khó khăn với bọn trẻ.")
W("engaged", "adj", "ɪnˈɡeɪdʒd", 3, "đã đính hôn", "My sister just got engaged.", "Chị tôi vừa đính hôn.")
W("relationship", "n", "rɪˈleɪʃnʃɪp", 3, "mối quan hệ", "They have a close relationship.", "Họ có mối quan hệ thân thiết.")
W("close", "adj", "kloʊs", 2, "thân thiết; gần", "We are very close friends.", "Chúng tôi là bạn rất thân.")
S("v", "đóng (phát âm /kloʊz/)", "Please close the door.", "Vui lòng đóng cửa.")
W("trust", "v", "trʌst", 2, "tin tưởng", "I trust my best friend completely.", "Tôi hoàn toàn tin tưởng bạn thân.")
S("n", "sự tin tưởng", "Trust takes years to build.", "Lòng tin cần nhiều năm để xây dựng.")
W("support", "v", "səˈpɔːrt", 2, "ủng hộ, hỗ trợ", "My family always supports my decisions.", "Gia đình luôn ủng hộ quyết định của tôi.", fam={"adj": "supportive"})
S("n", "sự hỗ trợ", "Thank you for your support.", "Cảm ơn sự hỗ trợ của bạn.")
W("argue", "v", "ˈɑːrɡjuː", 3, "cãi nhau", "My brothers argue about everything.", "Các anh tôi cãi nhau về mọi thứ.")
W("apologize", "v", "əˈpɑːlədʒaɪz", 3, "xin lỗi", "He apologized for being late.", "Anh ấy xin lỗi vì đến muộn.")
W("generation", "n", "ˌdʒenəˈreɪʃn", 3, "thế hệ", "Three generations live in this house.", "Ba thế hệ sống trong ngôi nhà này.")
W("only child", "n", "ˈoʊnli tʃaɪld", 2, "con một", "I'm an only child.", "Tôi là con một.")
W("twin", "n", "twɪn", 2, "sinh đôi", "Lan and Mai are twins.", "Lan và Mai là chị em sinh đôi.")
W("take after", "phr", "teɪk ˈæftər", 3, "giống (người lớn trong nhà)", "She takes after her mother.", "Cô ấy giống mẹ.")
W("look up to", "phr", "lʊk ʌp tuː", 4, "ngưỡng mộ, kính trọng", "I've always looked up to my older brother.", "Tôi luôn ngưỡng mộ anh trai mình.")
W("crush", "n", "krʌʃ", 3, "người mình thầm thích", "I have a crush on a girl in my class.", "Tôi thầm thích một bạn nữ trong lớp.")
W("date", "n", "deɪt", 2, "buổi hẹn hò; ngày", "They went on their first date last night.", "Tối qua họ có buổi hẹn hò đầu tiên.")
S("n", "ngày tháng", "What's the date today?", "Hôm nay là ngày bao nhiêu?")
W("best friend", "n", "best frend", 1, "bạn thân nhất", "She's my best friend since primary school.", "Cô ấy là bạn thân nhất của tôi từ hồi tiểu học.")

topic("feelings", "Cảm xúc & tính cách", "😊", 1)
W("happy", "adj", "ˈhæpi", 1, "vui vẻ, hạnh phúc", "I'm so happy to see you!", "Mình rất vui được gặp bạn!")
W("sad", "adj", "sæd", 1, "buồn", "She felt sad when her friend moved away.", "Cô ấy buồn khi bạn chuyển đi.")
W("angry", "adj", "ˈæŋɡri", 1, "tức giận", "Don't be angry with me.", "Đừng giận mình nhé.")
W("excited", "adj", "ɪkˈsaɪtɪd", 2, "hào hứng, phấn khích", "I'm excited about the trip.", "Mình rất háo hức về chuyến đi.", fam={"adj2": "exciting"})
W("bored", "adj", "bɔːrd", 2, "chán (cảm thấy)", "I'm bored. Let's go out.", "Chán quá. Đi chơi thôi.", fam={"adj2": "boring"})
W("nervous", "adj", "ˈnɜːrvəs", 2, "lo lắng, hồi hộp", "I always get nervous before exams.", "Tôi luôn hồi hộp trước kỳ thi.")
W("worried", "adj", "ˈwɜːrid", 2, "lo lắng", "Mom is worried because I'm late.", "Mẹ lo vì tôi về muộn.")
W("proud", "adj", "praʊd", 2, "tự hào", "I'm proud of you.", "Mình tự hào về bạn.", fam={"noun": "pride"})
W("embarrassed", "adj", "ɪmˈbærəst", 3, "xấu hổ, ngại", "I was embarrassed when I fell in front of everyone.", "Tôi xấu hổ khi ngã trước mặt mọi người.", fam={"adj2": "embarrassing"})
W("confident", "adj", "ˈkɑːnfɪdənt", 3, "tự tin", "Practice makes you more confident.", "Luyện tập giúp bạn tự tin hơn.", fam={"noun": "confidence"})
W("shy", "adj", "ʃaɪ", 2, "nhút nhát", "He's shy with new people.", "Cậu ấy nhút nhát với người lạ.")
W("friendly", "adj", "ˈfrendli", 1, "thân thiện", "The staff are very friendly.", "Nhân viên rất thân thiện.")
W("honest", "adj", "ˈɑːnɪst", 2, "trung thực", "To be honest, I don't like it.", "Thành thật mà nói, mình không thích nó.", fam={"noun": "honesty"})
W("lazy", "adj", "ˈleɪzi", 1, "lười", "I feel lazy on Sunday mornings.", "Sáng Chủ nhật tôi thấy lười.")
W("hard-working", "adj", "ˌhɑːrd ˈwɜːrkɪŋ", 2, "chăm chỉ", "She is a hard-working student.", "Cô ấy là học sinh chăm chỉ.")
W("generous", "adj", "ˈdʒenərəs", 3, "hào phóng", "It was generous of you to help.", "Bạn thật hào phóng khi giúp đỡ.")
W("selfish", "adj", "ˈselfɪʃ", 3, "ích kỷ", "Don't be selfish. Share with your sister.", "Đừng ích kỷ. Chia cho em đi.")
W("patient", "adj", "ˈpeɪʃnt", 2, "kiên nhẫn", "Learning a language takes a patient mind.", "Học ngoại ngữ cần sự kiên nhẫn.")
W("stressed out", "adj", "strest aʊt", 3, "căng thẳng", "I'm so stressed out about work.", "Tôi căng thẳng vì công việc quá.")
W("relieved", "adj", "rɪˈliːvd", 3, "nhẹ nhõm", "I was relieved to hear the news.", "Tôi nhẹ nhõm khi nghe tin.", fam={"noun": "relief"})
W("disappointed", "adj", "ˌdɪsəˈpɔɪntɪd", 3, "thất vọng", "I was disappointed with the movie.", "Tôi thất vọng về bộ phim.")
W("grateful", "adj", "ˈɡreɪtfl", 3, "biết ơn", "I'm grateful for your help.", "Tôi biết ơn sự giúp đỡ của bạn.")
W("jealous", "adj", "ˈdʒeləs", 3, "ghen tị", "He's jealous of his brother's success.", "Anh ấy ghen tị với thành công của em trai.")
W("lonely", "adj", "ˈloʊnli", 2, "cô đơn", "She felt lonely in the new city.", "Cô ấy thấy cô đơn ở thành phố mới.")
W("calm", "adj", "kɑːm", 2, "bình tĩnh", "Stay calm and think.", "Bình tĩnh và suy nghĩ.")
S("v", "calm down: bình tĩnh lại", "Calm down. Everything will be fine.", "Bình tĩnh nào. Mọi chuyện sẽ ổn thôi.")
W("curious", "adj", "ˈkjʊriəs", 3, "tò mò", "Kids are curious about everything.", "Trẻ con tò mò về mọi thứ.", fam={"noun": "curiosity"})
W("mood", "n", "muːd", 2, "tâm trạng", "I'm in a good mood today.", "Hôm nay tâm trạng tôi tốt.")
W("upset", "adj", "ʌpˈset", 3, "buồn bực, khó chịu", "She was upset about her grades.", "Cô ấy buồn vì điểm số.")
W("thrilled", "adj", "θrɪld", 4, "cực kỳ vui sướng", "We were thrilled with the result.", "Chúng tôi cực kỳ vui với kết quả.")
W("overwhelmed", "adj", "ˌoʊvərˈwelmd", 4, "choáng ngợp, quá tải", "I feel overwhelmed by all this homework.", "Tôi thấy quá tải với đống bài tập này.")

topic("food", "Đồ ăn & nấu nướng", "🍜", 2)
W("rice", "n", "raɪs", 1, "cơm, gạo", "We eat rice almost every day.", "Chúng tôi ăn cơm gần như mỗi ngày.")
W("noodles", "n", "ˈnuːdlz", 1, "mì, bún, phở", "I had beef noodle soup for breakfast.", "Tôi ăn phở bò cho bữa sáng.")
W("vegetable", "n", "ˈvedʒtəbl", 1, "rau củ", "Eat more vegetables.", "Hãy ăn nhiều rau hơn.")
W("fruit", "n", "fruːt", 1, "trái cây", "Mango is my favorite fruit.", "Xoài là loại trái cây tôi thích nhất.")
W("cook", "v", "kʊk", 1, "nấu ăn", "My dad cooks dinner on weekends.", "Bố tôi nấu bữa tối vào cuối tuần.")
S("n", "đầu bếp, người nấu", "She's a great cook.", "Cô ấy nấu ăn rất giỏi.")
W("boil", "v", "bɔɪl", 2, "luộc, đun sôi", "Boil the eggs for ten minutes.", "Luộc trứng trong mười phút.")
W("fry", "v", "fraɪ", 2, "chiên, rán", "She fried some fish for lunch.", "Cô ấy rán ít cá cho bữa trưa.")
W("grill", "v", "ɡrɪl", 3, "nướng (vỉ)", "We grilled pork on the balcony.", "Chúng tôi nướng thịt heo ở ban công.")
W("bake", "v", "beɪk", 2, "nướng (lò)", "I baked a cake for her birthday.", "Tôi nướng bánh cho sinh nhật cô ấy.")
W("recipe", "n", "ˈresəpi", 3, "công thức nấu ăn", "Can you share the recipe?", "Bạn chia sẻ công thức được không?")
W("taste", "v", "teɪst", 2, "có vị; nếm", "This soup tastes amazing.", "Món súp này ngon tuyệt.")
S("n", "vị; gu", "We have the same taste in music.", "Chúng tôi có cùng gu âm nhạc.")
W("sweet", "adj", "swiːt", 1, "ngọt", "This coffee is too sweet.", "Cà phê này ngọt quá.")
S("adj", "dễ thương, tử tế", "That's so sweet of you!", "Bạn thật dễ thương!")
W("sour", "adj", "saʊər", 2, "chua", "Green mangoes are sour.", "Xoài xanh chua.")
W("bitter", "adj", "ˈbɪtər", 3, "đắng", "Black coffee is a bit bitter.", "Cà phê đen hơi đắng.")
W("salty", "adj", "ˈsɔːlti", 2, "mặn", "The fish sauce is very salty.", "Nước mắm rất mặn.")
W("fresh", "adj", "freʃ", 2, "tươi", "We buy fresh fish at the market.", "Chúng tôi mua cá tươi ở chợ.")
W("snack", "n", "snæk", 2, "đồ ăn vặt", "I'm hungry. Let's get a snack.", "Đói rồi. Ăn chút gì đi.")
W("meal", "n", "miːl", 1, "bữa ăn", "Dinner is my favorite meal.", "Bữa tối là bữa tôi thích nhất.")
W("hungry", "adj", "ˈhʌŋɡri", 1, "đói", "I'm so hungry!", "Mình đói quá!")
W("full", "adj", "fʊl", 1, "no; đầy", "I can't eat anymore. I'm full.", "Mình không ăn được nữa. No rồi.")
W("leftovers", "n", "ˈleftoʊvərz", 3, "đồ ăn thừa", "We had leftovers for lunch.", "Trưa chúng tôi ăn đồ thừa.")
W("chopsticks", "n", "ˈtʃɑːpstɪks", 2, "đũa", "Can you use chopsticks?", "Bạn dùng được đũa không?")
W("street food", "n", "striːt fuːd", 2, "đồ ăn đường phố", "Hanoi is famous for its street food.", "Hà Nội nổi tiếng với đồ ăn đường phố.")
W("takeaway", "n", "ˈteɪkəweɪ", 3, "đồ ăn mang đi", "Let's get a takeaway tonight.", "Tối nay mua đồ ăn mang về đi.")
W("flavor", "n", "ˈfleɪvər", 3, "hương vị", "Which ice cream flavor do you want?", "Bạn muốn kem vị gì?")
W("crispy", "adj", "ˈkrɪspi", 3, "giòn", "The spring rolls are hot and crispy.", "Chả giò nóng và giòn.")
W("slice", "n", "slaɪs", 2, "lát, miếng", "Would you like a slice of pizza?", "Bạn ăn một miếng pizza không?")
W("starving", "adj", "ˈstɑːrvɪŋ", 3, "đói meo", "I'm starving! When is dinner?", "Mình đói meo rồi! Khi nào ăn tối?")
W("mouth-watering", "adj", "ˈmaʊθ wɔːtərɪŋ", 4, "hấp dẫn (thèm chảy nước miếng)", "The smell of grilled meat was mouth-watering.", "Mùi thịt nướng thơm phát thèm.")

topic("weather", "Thời tiết & thiên nhiên", "⛅", 3)
W("sunny", "adj", "ˈsʌni", 1, "nắng", "It's sunny and warm today.", "Hôm nay trời nắng và ấm.")
W("rainy", "adj", "ˈreɪni", 1, "mưa", "The rainy season starts in May.", "Mùa mưa bắt đầu vào tháng Năm.")
W("cloudy", "adj", "ˈklaʊdi", 1, "nhiều mây", "It's cloudy, but it isn't raining.", "Trời nhiều mây nhưng không mưa.")
W("windy", "adj", "ˈwɪndi", 2, "nhiều gió", "It's too windy to go to the beach.", "Trời quá nhiều gió để đi biển.")
W("humid", "adj", "ˈhjuːmɪd", 3, "ẩm ướt, oi", "Saigon is hot and humid.", "Sài Gòn nóng và oi.", fam={"noun": "humidity"})
W("storm", "n", "stɔːrm", 2, "cơn bão", "A big storm is coming.", "Một cơn bão lớn đang đến.")
W("forecast", "n", "ˈfɔːrkæst", 3, "dự báo", "The forecast says it will rain tomorrow.", "Dự báo nói mai trời sẽ mưa.")
W("thunder", "n", "ˈθʌndər", 3, "sấm", "The dog is scared of thunder.", "Con chó sợ sấm.")
W("lightning", "n", "ˈlaɪtnɪŋ", 3, "tia chớp", "Lightning hit the tree.", "Sét đánh trúng cái cây.")
W("freezing", "adj", "ˈfriːzɪŋ", 3, "lạnh cóng", "It's freezing outside. Take a jacket.", "Ngoài trời lạnh cóng. Mang áo khoác đi.")
W("season", "n", "ˈsiːzn", 1, "mùa", "Autumn is the best season in Hanoi.", "Mùa thu là mùa đẹp nhất ở Hà Nội.")
W("mountain", "n", "ˈmaʊntn", 1, "núi", "We climbed the mountain at sunrise.", "Chúng tôi leo núi lúc bình minh.")
W("river", "n", "ˈrɪvər", 1, "sông", "The Mekong is a long river.", "Mê Kông là một con sông dài.")
W("ocean", "n", "ˈoʊʃn", 2, "đại dương", "The ocean looks beautiful at night.", "Đại dương trông thật đẹp vào ban đêm.")
W("island", "n", "ˈaɪlənd", 2, "hòn đảo", "Phu Quoc is a beautiful island.", "Phú Quốc là một hòn đảo đẹp.")
W("waterfall", "n", "ˈwɔːtərfɔːl", 3, "thác nước", "We swam under the waterfall.", "Chúng tôi bơi dưới thác nước.")
W("cave", "n", "keɪv", 3, "hang động", "Son Doong is the largest cave in the world.", "Sơn Đoòng là hang động lớn nhất thế giới.")
W("sunrise", "n", "ˈsʌnraɪz", 2, "bình minh", "We got up early to watch the sunrise.", "Chúng tôi dậy sớm ngắm bình minh.")
W("sunset", "n", "ˈsʌnset", 2, "hoàng hôn", "The sunset over the sea was amazing.", "Hoàng hôn trên biển thật tuyệt.")
W("rainbow", "n", "ˈreɪnboʊ", 2, "cầu vồng", "Look! There's a rainbow!", "Nhìn kìa! Có cầu vồng!")
W("breeze", "n", "briːz", 4, "gió nhẹ", "A cool breeze came from the sea.", "Một làn gió mát thổi từ biển vào.")
W("heatwave", "n", "ˈhiːtweɪv", 4, "đợt nắng nóng", "The heatwave lasted two weeks.", "Đợt nắng nóng kéo dài hai tuần.")
W("typhoon", "n", "taɪˈfuːn", 3, "bão nhiệt đới (siêu bão)", "The typhoon hit the central coast.", "Cơn bão đổ bộ vào bờ biển miền Trung.")
W("pour", "v", "pɔːr", 3, "mưa như trút; rót", "It's pouring outside.", "Ngoài trời mưa như trút.")
W("degree", "n", "dɪˈɡriː", 3, "độ", "It's 38 degrees today!", "Hôm nay 38 độ!")
W("nature", "n", "ˈneɪtʃər", 2, "thiên nhiên", "I love being close to nature.", "Tôi thích gần gũi thiên nhiên.", fam={"adj": "natural"})
W("landscape", "n", "ˈlændskeɪp", 4, "phong cảnh", "The landscape in Ha Giang is stunning.", "Phong cảnh Hà Giang đẹp ngỡ ngàng.")
W("earthquake", "n", "ˈɜːrθkweɪk", 3, "động đất", "The earthquake shook the whole city.", "Trận động đất làm rung chuyển cả thành phố.")
W("fog", "n", "fɔːɡ", 3, "sương mù", "The fog was so thick we couldn't see the road.", "Sương mù dày đến mức không thấy đường.", fam={"adj": "foggy"})
W("melt", "v", "melt", 3, "tan chảy", "The ice cream melted in the sun.", "Kem tan chảy dưới nắng.")

topic("sports", "Thể thao & vận động", "⚽", 4)
W("football", "n", "ˈfʊtbɔːl", 1, "bóng đá", "Football is the most popular sport in Vietnam.", "Bóng đá là môn thể thao phổ biến nhất ở Việt Nam.")
W("team", "n", "tiːm", 1, "đội", "Which team do you support?", "Bạn cổ vũ đội nào?")
W("match", "n", "mætʃ", 2, "trận đấu", "The match ended 2–1.", "Trận đấu kết thúc 2–1.")
S("v", "hợp với, khớp với", "Your shoes match your bag.", "Giày của bạn hợp với túi.")
W("score", "v", "skɔːr", 2, "ghi bàn", "He scored two goals.", "Anh ấy ghi hai bàn.")
S("n", "điểm số, tỷ số", "What's the score?", "Tỷ số bao nhiêu rồi?")
W("win", "v", "wɪn", 1, "thắng", "We won the game!", "Chúng ta thắng rồi!")
W("lose", "v", "luːz", 1, "thua; làm mất", "They lost the final.", "Họ thua trận chung kết.")
S("v", "làm mất", "I lost my keys again.", "Tôi lại làm mất chìa khóa rồi.")
W("coach", "n", "koʊtʃ", 2, "huấn luyện viên", "The coach is happy with the team.", "Huấn luyện viên hài lòng với đội.")
S("n", "xe khách đường dài", "We took a coach to Da Lat.", "Chúng tôi đi xe khách lên Đà Lạt.")
W("champion", "n", "ˈtʃæmpiən", 3, "nhà vô địch", "She is the national swimming champion.", "Cô ấy là nhà vô địch bơi lội quốc gia.", fam={"noun": "championship"})
W("tournament", "n", "ˈtʊrnəmənt", 4, "giải đấu", "Thirty teams joined the tournament.", "Ba mươi đội tham gia giải đấu.")
W("referee", "n", "ˌrefəˈriː", 3, "trọng tài", "The referee gave him a yellow card.", "Trọng tài rút thẻ vàng cho anh ấy.")
W("stadium", "n", "ˈsteɪdiəm", 2, "sân vận động", "The stadium was full of fans.", "Sân vận động chật kín cổ động viên.")
W("fan", "n", "fæn", 1, "người hâm mộ", "I'm a big fan of this singer.", "Tôi là fan cuồng của ca sĩ này.")
S("n", "cái quạt", "Turn on the fan, it's hot.", "Bật quạt lên, nóng quá.")
W("work out", "phr", "wɜːrk aʊt", 2, "tập luyện (gym)", "I work out three times a week.", "Tôi tập gym ba lần một tuần.")
S("phr", "tìm ra, giải quyết", "Don't worry, we'll work it out.", "Đừng lo, chúng ta sẽ tìm ra cách.")
W("jog", "v", "dʒɑːɡ", 2, "chạy bộ", "I jog in the park every morning.", "Tôi chạy bộ trong công viên mỗi sáng.")
W("gym", "n", "dʒɪm", 1, "phòng tập", "The gym is open until 10 p.m.", "Phòng tập mở cửa đến 10 giờ tối.")
W("muscle", "n", "ˈmʌsl", 3, "cơ bắp", "Swimming builds muscle.", "Bơi lội giúp phát triển cơ bắp.")
W("fit", "adj", "fɪt", 2, "khỏe mạnh, cân đối", "She keeps fit by cycling.", "Cô ấy giữ dáng bằng cách đạp xe.", fam={"noun": "fitness"})
W("compete", "v", "kəmˈpiːt", 3, "thi đấu, cạnh tranh", "Over 100 athletes will compete.", "Hơn 100 vận động viên sẽ thi đấu.", fam={"noun": "competition"})
W("athlete", "n", "ˈæθliːt", 3, "vận động viên", "Athletes train for years for the Olympics.", "Các vận động viên tập luyện nhiều năm cho Thế vận hội.")
W("medal", "n", "ˈmedl", 3, "huy chương", "Vietnam won three gold medals.", "Việt Nam giành ba huy chương vàng.")
W("draw", "n", "drɔː", 3, "trận hòa", "The game ended in a draw.", "Trận đấu kết thúc với tỷ số hòa.")
S("v", "vẽ", "Can you draw a cat?", "Bạn vẽ được con mèo không?")
W("injured", "adj", "ˈɪndʒərd", 3, "bị thương", "Two players are injured.", "Hai cầu thủ bị chấn thương.")
W("cheer", "v", "tʃɪr", 3, "cổ vũ", "The crowd cheered for the home team.", "Đám đông cổ vũ đội nhà.")
W("warm up", "phr", "wɔːrm ʌp", 2, "khởi động", "Always warm up before running.", "Luôn khởi động trước khi chạy.")
W("badminton", "n", "ˈbædmɪntən", 1, "cầu lông", "We play badminton after work.", "Chúng tôi chơi cầu lông sau giờ làm.")
W("record", "n", "ˈrekərd", 3, "kỷ lục", "She broke the world record.", "Cô ấy phá kỷ lục thế giới.")
S("v", "ghi lại, thu âm (phát âm /rɪˈkɔːrd/)", "We recorded a song together.", "Chúng tôi thu âm một bài hát cùng nhau.")

topic("entertainment", "Phim, nhạc & giải trí", "🎬", 5)
W("movie", "n", "ˈmuːvi", 1, "bộ phim", "Let's watch a movie tonight.", "Tối nay xem phim đi.")
W("actor", "n", "ˈæktər", 1, "diễn viên", "He's my favorite actor.", "Anh ấy là diễn viên tôi thích nhất.")
W("director", "n", "dəˈrektər", 2, "đạo diễn; giám đốc", "The director won an award.", "Vị đạo diễn đã giành giải thưởng.")
W("plot", "n", "plɑːt", 3, "cốt truyện", "The plot is a bit confusing.", "Cốt truyện hơi khó hiểu.")
W("character", "n", "ˈkærəktər", 3, "nhân vật; tính cách", "The main character is a young doctor.", "Nhân vật chính là một bác sĩ trẻ.")
W("episode", "n", "ˈepɪsoʊd", 3, "tập (phim)", "I watched three episodes last night.", "Tối qua tôi xem ba tập.")
W("series", "n", "ˈsɪriːz", 3, "loạt phim; chuỗi", "This series has five seasons.", "Bộ phim này có năm mùa.")
W("spoiler", "n", "ˈspɔɪlər", 3, "tiết lộ nội dung (làm mất hay)", "No spoilers, please! I haven't seen it.", "Đừng spoil nhé! Mình chưa xem.")
W("binge-watch", "v", "ˈbɪndʒ wɑːtʃ", 4, "cày phim (xem liền nhiều tập)", "I binge-watched the whole season this weekend.", "Cuối tuần này tôi cày hết cả mùa phim.")
W("song", "n", "sɔːŋ", 1, "bài hát", "This song is so catchy.", "Bài hát này dễ nghe quá.")
W("lyrics", "n", "ˈlɪrɪks", 3, "lời bài hát", "Do you know the lyrics?", "Bạn có thuộc lời bài hát không?")
W("catchy", "adj", "ˈkætʃi", 3, "bắt tai, dễ nhớ", "The song has a catchy chorus.", "Bài hát có điệp khúc bắt tai.")
W("concert", "n", "ˈkɑːnsərt", 2, "buổi hòa nhạc", "We got tickets for the concert!", "Bọn mình mua được vé concert rồi!")
W("band", "n", "bænd", 2, "ban nhạc", "My brother plays guitar in a band.", "Anh tôi chơi guitar trong một ban nhạc.")
W("album", "n", "ˈælbəm", 2, "album", "Their new album comes out next week.", "Album mới của họ ra mắt tuần sau.")
W("playlist", "n", "ˈpleɪlɪst", 2, "danh sách phát", "I made a playlist for studying.", "Tôi tạo một playlist để học.")
W("game", "n", "ɡeɪm", 1, "trò chơi", "This game is really addictive.", "Trò chơi này gây nghiện thật.")
W("addictive", "adj", "əˈdɪktɪv", 4, "gây nghiện", "Social media can be addictive.", "Mạng xã hội có thể gây nghiện.")
W("comedy", "n", "ˈkɑːmədi", 3, "phim hài", "I prefer comedies to horror films.", "Tôi thích phim hài hơn phim kinh dị.")
W("horror", "n", "ˈhɔːrər", 3, "kinh dị", "I can't watch horror movies alone.", "Tôi không dám xem phim kinh dị một mình.")
W("cartoon", "n", "kɑːrˈtuːn", 1, "phim hoạt hình", "Kids love cartoons.", "Trẻ con thích phim hoạt hình.")
W("ticket", "n", "ˈtɪkɪt", 1, "vé", "Two tickets for the 8 o'clock show, please.", "Cho hai vé suất 8 giờ.")
W("trailer", "n", "ˈtreɪlər", 3, "đoạn giới thiệu phim", "The trailer looks amazing.", "Trailer trông tuyệt quá.")
W("review", "n", "rɪˈvjuː", 3, "bài đánh giá", "The film got great reviews.", "Bộ phim nhận được đánh giá rất tốt.")
S("v", "ôn lại; xem xét", "Let's review the new words.", "Cùng ôn lại từ mới nhé.")
W("perform", "v", "pərˈfɔːrm", 3, "biểu diễn", "The band performed three new songs.", "Ban nhạc biểu diễn ba bài mới.")
W("audience", "n", "ˈɔːdiəns", 3, "khán giả", "The audience loved the show.", "Khán giả rất thích buổi diễn.")
W("subtitles", "n", "ˈsʌbtaɪtlz", 3, "phụ đề", "I watch movies with English subtitles.", "Tôi xem phim có phụ đề tiếng Anh.")
W("streaming", "n", "ˈstriːmɪŋ", 3, "phát trực tuyến", "Streaming services are very popular.", "Các dịch vụ xem phim trực tuyến rất phổ biến.", fam={"verb": "stream"})
W("fan club", "n", "fæn klʌb", 3, "câu lạc bộ người hâm mộ", "She joined the singer's fan club.", "Cô ấy tham gia fan club của ca sĩ.")
W("masterpiece", "n", "ˈmæstərpiːs", 4, "kiệt tác", "This film is a true masterpiece.", "Bộ phim này đúng là kiệt tác.")

topic("body", "Cơ thể & ngoại hình", "🧍", 6)
W("head", "n", "hed", 1, "đầu", "He shook his head.", "Anh ấy lắc đầu.")
S("v", "đi về phía", "We're heading home now.", "Giờ bọn mình về nhà đây.")
W("shoulder", "n", "ˈʃoʊldər", 2, "vai", "My shoulder hurts.", "Vai tôi bị đau.")
W("knee", "n", "niː", 2, "đầu gối", "He hurt his knee playing football.", "Anh ấy đau đầu gối khi đá bóng.")
W("back", "n", "bæk", 1, "lưng", "Sitting too long is bad for your back.", "Ngồi lâu không tốt cho lưng.")
S("adv", "trở lại", "I'll be back in five minutes.", "Năm phút nữa mình quay lại.")
W("stomach", "n", "ˈstʌmək", 2, "bụng, dạ dày", "I have a stomachache.", "Tôi bị đau bụng.")
W("tooth", "n", "tuːθ", 1, "răng", "Brush your teeth twice a day.", "Đánh răng hai lần mỗi ngày.")
W("finger", "n", "ˈfɪŋɡər", 1, "ngón tay", "I cut my finger.", "Tôi bị đứt tay.")
W("hair", "n", "her", 1, "tóc", "She has long black hair.", "Cô ấy có mái tóc đen dài.")
W("tall", "adj", "tɔːl", 1, "cao", "My brother is very tall.", "Anh tôi rất cao.")
W("slim", "adj", "slɪm", 2, "thon thả", "She is tall and slim.", "Cô ấy cao và thon thả.")
W("curly", "adj", "ˈkɜːrli", 2, "xoăn", "He has curly hair.", "Anh ấy có tóc xoăn.")
W("good-looking", "adj", "ˌɡʊd ˈlʊkɪŋ", 2, "ưa nhìn, đẹp", "Her boyfriend is very good-looking.", "Bạn trai cô ấy rất đẹp trai.")
W("cute", "adj", "kjuːt", 1, "dễ thương", "What a cute puppy!", "Chú cún dễ thương quá!")
W("skin", "n", "skɪn", 2, "da", "Use sunscreen to protect your skin.", "Dùng kem chống nắng để bảo vệ da.")
W("blink", "v", "blɪŋk", 3, "chớp mắt", "She didn't even blink.", "Cô ấy thậm chí không chớp mắt.")
W("yawn", "v", "jɔːn", 3, "ngáp", "He yawned during the meeting.", "Anh ấy ngáp trong cuộc họp.")
W("sneeze", "v", "sniːz", 3, "hắt hơi", "Cover your mouth when you sneeze.", "Che miệng khi hắt hơi.")
W("height", "n", "haɪt", 3, "chiều cao", "What's your height?", "Bạn cao bao nhiêu?")
W("weight", "n", "weɪt", 3, "cân nặng", "He lost a lot of weight.", "Anh ấy giảm nhiều cân.", fam={"verb": "weigh"})
W("brain", "n", "breɪn", 2, "não", "Learning languages is good for your brain.", "Học ngoại ngữ tốt cho não.")
W("heart", "n", "hɑːrt", 1, "tim", "Exercise keeps your heart healthy.", "Tập thể dục giúp tim khỏe.")
S("phr", "by heart: thuộc lòng", "I know this poem by heart.", "Tôi thuộc lòng bài thơ này.")
W("ankle", "n", "ˈæŋkl", 3, "mắt cá chân", "I twisted my ankle.", "Tôi bị trẹo mắt cá chân.")
W("wrist", "n", "rɪst", 3, "cổ tay", "She wears a watch on her left wrist.", "Cô ấy đeo đồng hồ ở cổ tay trái.")
W("eyebrow", "n", "ˈaɪbraʊ", 3, "lông mày", "He raised his eyebrows in surprise.", "Anh ấy nhướn mày ngạc nhiên.")
W("chin", "n", "tʃɪn", 3, "cằm", "Keep your chin up!", "Ngẩng cao đầu lên nào!")
W("thumb", "n", "θʌm", 3, "ngón cái", "She gave me a thumbs-up.", "Cô ấy giơ ngón cái với tôi.")
W("muscle", "n", "ˈmʌsl", 3, "cơ bắp", "Stretch your muscles after exercise.", "Giãn cơ sau khi tập.")
W("appearance", "n", "əˈpɪrəns", 4, "ngoại hình", "Don't judge people by their appearance.", "Đừng đánh giá người khác qua vẻ bề ngoài.", fam={"verb": "appear"})

topic("animals", "Động vật & thú cưng", "🐾", 7)
W("pet", "n", "pet", 1, "thú cưng", "Do you have any pets?", "Bạn có nuôi thú cưng không?")
S("v", "vuốt ve", "You can pet the dog. He's friendly.", "Bạn có thể vuốt ve con chó. Nó hiền lắm.")
W("puppy", "n", "ˈpʌpi", 1, "chó con", "The puppy is sleeping in its basket.", "Chú cún đang ngủ trong giỏ.")
W("kitten", "n", "ˈkɪtn", 2, "mèo con", "The kitten is playing with a ball.", "Mèo con đang chơi với quả bóng.")
W("feed", "v", "fiːd", 2, "cho ăn", "Don't forget to feed the cat.", "Đừng quên cho mèo ăn.")
S("n", "bảng tin (mạng xã hội)", "Your post is all over my feed.", "Bài đăng của bạn tràn ngập bảng tin của mình.")
W("tail", "n", "teɪl", 2, "cái đuôi", "The dog is wagging its tail.", "Con chó đang vẫy đuôi.")
W("fur", "n", "fɜːr", 3, "lông thú", "The cat has soft white fur.", "Con mèo có bộ lông trắng mềm.")
W("paw", "n", "pɔː", 3, "chân (có móng) của thú", "The kitten licked its paw.", "Mèo con liếm chân.")
W("bark", "v", "bɑːrk", 3, "sủa", "The dog barks at strangers.", "Con chó sủa người lạ.")
W("bite", "v", "baɪt", 2, "cắn", "Don't worry, he doesn't bite.", "Đừng lo, nó không cắn đâu.")
W("cage", "n", "keɪdʒ", 3, "cái lồng", "The bird is in its cage.", "Con chim ở trong lồng.")
W("vet", "n", "vet", 3, "bác sĩ thú y", "We took the dog to the vet.", "Chúng tôi đưa chó đi thú y.")
W("wild", "adj", "waɪld", 2, "hoang dã", "Wild animals should live in nature.", "Động vật hoang dã nên sống trong tự nhiên.")
W("elephant", "n", "ˈelɪfənt", 1, "con voi", "Elephants have great memories.", "Voi có trí nhớ rất tốt.")
W("tiger", "n", "ˈtaɪɡər", 1, "con hổ", "Tigers are good swimmers.", "Hổ bơi rất giỏi.")
W("monkey", "n", "ˈmʌŋki", 1, "con khỉ", "The monkey stole my banana!", "Con khỉ lấy trộm chuối của tôi!")
W("bird", "n", "bɜːrd", 1, "con chim", "Birds sing in the morning.", "Chim hót vào buổi sáng.")
W("butterfly", "n", "ˈbʌtərflaɪ", 2, "con bướm", "A butterfly landed on the flower.", "Một con bướm đậu lên bông hoa.")
W("dolphin", "n", "ˈdɑːlfɪn", 2, "cá heo", "Dolphins are very smart.", "Cá heo rất thông minh.")
W("turtle", "n", "ˈtɜːrtl", 2, "con rùa", "Sea turtles lay eggs on the beach.", "Rùa biển đẻ trứng trên bãi biển.")
W("rabbit", "n", "ˈræbɪt", 1, "con thỏ", "The rabbit is eating a carrot.", "Con thỏ đang ăn cà rốt.")
W("hamster", "n", "ˈhæmstər", 2, "chuột hamster", "My hamster sleeps all day.", "Con hamster của tôi ngủ cả ngày.")
W("adopt", "v", "əˈdɑːpt", 3, "nhận nuôi", "We adopted a cat from a shelter.", "Chúng tôi nhận nuôi một con mèo từ trại cứu hộ.", fam={"noun": "adoption"})
W("shelter", "n", "ˈʃeltər", 4, "trại cứu hộ; nơi trú ẩn", "The animal shelter needs volunteers.", "Trại cứu hộ động vật cần tình nguyện viên.")
W("loyal", "adj", "ˈlɔɪəl", 3, "trung thành", "Dogs are loyal animals.", "Chó là loài vật trung thành.")
W("cuddle", "v", "ˈkʌdl", 3, "ôm ấp", "The kids love to cuddle the puppy.", "Bọn trẻ thích ôm chú cún.")
W("dragon", "n", "ˈdræɡən", 2, "con rồng", "In the story, a friendly dragon helps the village.", "Trong truyện, một chú rồng thân thiện giúp ngôi làng.")
W("feather", "n", "ˈfeðər", 3, "lông vũ", "The parrot has bright green feathers.", "Con vẹt có bộ lông xanh sáng.")
W("nest", "n", "nest", 3, "cái tổ", "The bird built a nest in the tree.", "Con chim làm tổ trên cây.")
W("insect", "n", "ˈɪnsekt", 3, "côn trùng", "Ants are tiny insects.", "Kiến là loài côn trùng nhỏ xíu.")
W("habitat", "n", "ˈhæbɪtæt", 4, "môi trường sống", "Forests are the natural habitat of many animals.", "Rừng là môi trường sống tự nhiên của nhiều loài vật.")

topic("clothes", "Quần áo & thời trang", "👕", 8)
W("shirt", "n", "ʃɜːrt", 1, "áo sơ mi", "He wears a white shirt to work.", "Anh ấy mặc áo sơ mi trắng đi làm.")
W("jeans", "n", "dʒiːnz", 1, "quần bò", "I bought a new pair of jeans.", "Tôi mua một chiếc quần bò mới.")
W("dress", "n", "dres", 1, "váy liền", "She wore a red dress to the party.", "Cô ấy mặc váy đỏ đến bữa tiệc.")
S("v", "mặc đồ", "Get dressed quickly, we're late!", "Mặc đồ nhanh lên, muộn rồi!")
W("jacket", "n", "ˈdʒækɪt", 1, "áo khoác", "Take a jacket. It's cold.", "Mang áo khoác đi. Trời lạnh đấy.")
W("sneakers", "n", "ˈsniːkərz", 2, "giày thể thao", "These sneakers are really comfortable.", "Đôi giày thể thao này thật thoải mái.")
W("hat", "n", "hæt", 1, "cái mũ", "Wear a hat in the sun.", "Đội mũ khi đi nắng.")
W("scarf", "n", "skɑːrf", 2, "khăn quàng", "She knitted a scarf for her dad.", "Cô ấy đan khăn cho bố.")
W("glasses", "n", "ˈɡlæsɪz", 1, "kính mắt", "I need glasses to read.", "Tôi cần đeo kính để đọc.")
W("uniform", "n", "ˈjuːnɪfɔːrm", 2, "đồng phục", "Students must wear a uniform.", "Học sinh phải mặc đồng phục.")
W("fashion", "n", "ˈfæʃn", 2, "thời trang", "She works in the fashion industry.", "Cô ấy làm trong ngành thời trang.", fam={"adj": "fashionable"})
W("outfit", "n", "ˈaʊtfɪt", 3, "bộ trang phục", "I love your outfit today!", "Mình thích bộ đồ hôm nay của bạn!")
W("style", "n", "staɪl", 2, "phong cách", "He has his own style.", "Anh ấy có phong cách riêng.", fam={"adj": "stylish"})
W("trendy", "adj", "ˈtrendi", 3, "hợp mốt", "That café is full of trendy young people.", "Quán cà phê đó toàn giới trẻ sành điệu.")
W("loose", "adj", "luːs", 3, "rộng, lỏng", "These pants are too loose.", "Quần này rộng quá.")
W("tight", "adj", "taɪt", 3, "chật, bó", "My shoes are too tight.", "Giày tôi chật quá.")
W("wear", "v", "wer", 1, "mặc, đeo, đội", "What are you wearing tonight?", "Tối nay bạn mặc gì?")
W("put on", "phr", "pʊt ɑːn", 1, "mặc vào", "Put on your coat.", "Mặc áo khoác vào.")
W("take off", "phr", "teɪk ɔːf", 1, "cởi ra; cất cánh", "Please take off your shoes.", "Vui lòng cởi giày ra.")
S("phr", "cất cánh; phát triển nhanh", "The plane took off on time.", "Máy bay cất cánh đúng giờ.")
W("pocket", "n", "ˈpɑːkɪt", 2, "túi (quần áo)", "My phone is in my pocket.", "Điện thoại ở trong túi tôi.")
W("sleeve", "n", "sliːv", 3, "tay áo", "I like shirts with short sleeves.", "Tôi thích áo sơ mi tay ngắn.")
W("button", "n", "ˈbʌtn", 2, "cúc áo; nút bấm", "A button fell off my shirt.", "Một chiếc cúc áo bị rơi.")
W("match", "v", "mætʃ", 2, "hợp (màu, kiểu)", "Does this tie match my shirt?", "Cà vạt này có hợp áo không?")
W("casual", "adj", "ˈkæʒuəl", 3, "thường ngày, thoải mái", "Friday is casual dress day.", "Thứ Sáu là ngày mặc đồ thoải mái.")
W("formal", "adj", "ˈfɔːrml", 3, "trang trọng", "You need formal clothes for the interview.", "Bạn cần trang phục trang trọng khi phỏng vấn.")
W("brand", "n", "brænd", 2, "nhãn hiệu", "Which brand is your bag?", "Túi bạn hiệu gì?")
W("accessory", "n", "əkˈsesəri", 4, "phụ kiện", "Earrings are my favorite accessory.", "Khuyên tai là phụ kiện tôi thích nhất.")
W("jewelry", "n", "ˈdʒuːəlri", 3, "đồ trang sức", "She doesn't wear much jewelry.", "Cô ấy không đeo nhiều trang sức.")
W("umbrella", "n", "ʌmˈbrelə", 1, "cái ô", "Don't forget your umbrella.", "Đừng quên ô nhé.")
W("look good on", "phr", "lʊk ɡʊd ɑːn", 2, "trông hợp với ai", "That color looks good on you.", "Màu đó hợp với bạn đấy.")

topic("city", "Thành phố & chỉ đường", "🏙️", 9)
W("street", "n", "striːt", 1, "đường phố", "Cross the street carefully.", "Băng qua đường cẩn thận.")
W("crossroads", "n", "ˈkrɔːsroʊdz", 3, "ngã tư", "Turn left at the crossroads.", "Rẽ trái ở ngã tư.")
W("traffic light", "n", "ˈtræfɪk laɪt", 1, "đèn giao thông", "Stop at the traffic light.", "Dừng ở đèn giao thông.")
W("turn left", "phr", "tɜːrn left", 1, "rẽ trái", "Turn left at the bank.", "Rẽ trái ở ngân hàng.")
W("go straight", "phr", "ɡoʊ streɪt", 1, "đi thẳng", "Go straight for two blocks.", "Đi thẳng qua hai dãy nhà.")
W("opposite", "prep", "ˈɑːpəzɪt", 2, "đối diện", "The bank is opposite the post office.", "Ngân hàng đối diện bưu điện.")
S("adj", "trái ngược", "'Hot' is the opposite of 'cold'.", "'Nóng' là từ trái nghĩa với 'lạnh'.")
W("next to", "prep", "nekst tuː", 1, "bên cạnh", "The café is next to the bookshop.", "Quán cà phê ở cạnh hiệu sách.")
W("between", "prep", "bɪˈtwiːn", 1, "ở giữa (hai)", "The pharmacy is between the bank and the school.", "Nhà thuốc ở giữa ngân hàng và trường học.")
W("corner", "n", "ˈkɔːrnər", 2, "góc (phố)", "There's a shop on the corner.", "Có một cửa hàng ở góc phố.")
W("block", "n", "blɑːk", 3, "dãy nhà; khối", "The hotel is two blocks away.", "Khách sạn cách hai dãy nhà.")
W("bridge", "n", "brɪdʒ", 2, "cây cầu", "Walk across the bridge.", "Đi bộ qua cầu.")
W("sidewalk", "n", "ˈsaɪdwɔːk", 3, "vỉa hè", "People park their motorbikes on the sidewalk.", "Mọi người đỗ xe máy trên vỉa hè.")
W("crowded", "adj", "ˈkraʊdɪd", 2, "đông đúc", "The market is crowded on weekends.", "Chợ đông vào cuối tuần.")
W("downtown", "n", "ˌdaʊnˈtaʊn", 2, "trung tâm thành phố", "Downtown is busy at night.", "Trung tâm thành phố nhộn nhịp về đêm.")
W("landmark", "n", "ˈlændmɑːrk", 4, "địa danh, công trình nổi bật", "The cathedral is a famous landmark.", "Nhà thờ lớn là một địa danh nổi tiếng.")
W("museum", "n", "mjuˈziːəm", 2, "bảo tàng", "The museum is free on Sundays.", "Bảo tàng miễn phí vào Chủ nhật.")
W("library", "n", "ˈlaɪbreri", 1, "thư viện", "I study at the library.", "Tôi học ở thư viện.")
W("post office", "n", "poʊst ˈɔːfɪs", 1, "bưu điện", "Where is the nearest post office?", "Bưu điện gần nhất ở đâu?")
W("hospital", "n", "ˈhɑːspɪtl", 1, "bệnh viện", "She works at the city hospital.", "Cô ấy làm ở bệnh viện thành phố.")
W("lost", "adj", "lɔːst", 2, "bị lạc", "Excuse me, I think I'm lost.", "Xin lỗi, hình như tôi bị lạc.")
W("direction", "n", "dəˈrekʃn", 2, "hướng; chỉ dẫn", "Can you give me directions to the station?", "Bạn chỉ đường đến ga giúp tôi được không?")
W("far", "adj", "fɑːr", 1, "xa", "Is it far from here?", "Chỗ đó có xa đây không?")
W("nearby", "adv", "ˌnɪrˈbaɪ", 2, "gần đây", "Is there an ATM nearby?", "Gần đây có ATM không?")
W("public transport", "n", "ˈpʌblɪk ˈtrænspɔːrt", 3, "giao thông công cộng", "I use public transport every day.", "Tôi dùng giao thông công cộng mỗi ngày.")
W("motorbike", "n", "ˈmoʊtərbaɪk", 1, "xe máy", "Most people in Vietnam ride motorbikes.", "Hầu hết người Việt đi xe máy.")
W("pedestrian", "n", "pəˈdestriən", 4, "người đi bộ", "This street is for pedestrians only.", "Con phố này chỉ dành cho người đi bộ.")
W("park", "v", "pɑːrk", 2, "đỗ xe", "Where can I park my bike?", "Tôi có thể đỗ xe ở đâu?")
S("n", "công viên", "Let's meet at the park.", "Gặp nhau ở công viên nhé.")
W("rush hour", "n", "rʌʃ aʊər", 3, "giờ cao điểm", "Avoid driving during rush hour.", "Tránh lái xe vào giờ cao điểm.")
W("skyscraper", "n", "ˈskaɪskreɪpər", 4, "nhà chọc trời", "The city has many new skyscrapers.", "Thành phố có nhiều tòa nhà chọc trời mới.")
