from lib import topic, W, S

topic("tech", "Công nghệ & IT", "💻", 2)
W("software", "n", "ˈsɔːftwer", 2, "phần mềm", "You need to update the software.", "Bạn cần cập nhật phần mềm.")
W("hardware", "n", "ˈhɑːrdwer", 3, "phần cứng", "The problem is with the hardware, not the program.", "Lỗi nằm ở phần cứng, không phải chương trình.")
W("download", "v", "ˌdaʊnˈloʊd", 1, "tải xuống", "Download the app for free.", "Tải ứng dụng miễn phí.")
W("upload", "v", "ˌʌpˈloʊd", 2, "tải lên", "She uploaded the photos to her blog.", "Cô ấy tải ảnh lên blog.")
W("password", "n", "ˈpæswɜːrd", 1, "mật khẩu", "Never share your password with anyone.", "Đừng bao giờ chia sẻ mật khẩu với ai.")
W("log in", "phr", "lɔːɡ ɪn", 2, "đăng nhập", "Log in with your email address.", "Đăng nhập bằng địa chỉ email của bạn.")
W("device", "n", "dɪˈvaɪs", 3, "thiết bị", "The app works on all mobile devices.", "Ứng dụng chạy trên mọi thiết bị di động.")
W("network", "n", "ˈnetwɜːrk", 3, "mạng (lưới)", "The office network is down.", "Mạng văn phòng đang bị sập.")
S("v", "giao lưu, mở rộng quan hệ (công việc)", "Conferences are a great place to network.", "Hội nghị là nơi tuyệt vời để mở rộng quan hệ.")
W("data", "n", "ˈdeɪtə", 2, "dữ liệu", "We collect data from our customers' surveys.", "Chúng tôi thu thập dữ liệu từ khảo sát khách hàng.")
W("backup", "n", "ˈbækʌp", 3, "bản sao lưu", "Always keep a backup of important files.", "Luôn giữ bản sao lưu các tệp quan trọng.")
W("install", "v", "ɪnˈstɔːl", 3, "cài đặt", "Install the latest version of the app.", "Cài phiên bản mới nhất của ứng dụng.")
W("update", "n", "ˈʌpdeɪt", 2, "bản cập nhật", "A new update is available.", "Đã có bản cập nhật mới.")
S("v", "cập nhật", "I'll update you on the project tomorrow.", "Ngày mai tôi sẽ cập nhật cho bạn về dự án.")
W("security", "n", "səˈkjʊrəti", 3, "an ninh, bảo mật", "Online security is very important.", "Bảo mật trực tuyến rất quan trọng.", fam={"adj": "secure"})
W("virus", "n", "ˈvaɪrəs", 2, "vi-rút", "My computer has a virus.", "Máy tính của tôi bị nhiễm vi-rút.")
W("screen", "n", "skriːn", 1, "màn hình", "The screen is too small to read.", "Màn hình quá nhỏ để đọc.")
W("keyboard", "n", "ˈkiːbɔːrd", 1, "bàn phím", "My keyboard stopped working.", "Bàn phím của tôi bị hỏng.")
W("technician", "n", "tekˈnɪʃn", 3, "kỹ thuật viên", "A technician will fix the printer.", "Một kỹ thuật viên sẽ sửa máy in.")
W("malfunction", "n", "mælˈfʌŋkʃn", 5, "sự trục trặc", "A malfunction stopped the production line.", "Một sự cố trục trặc làm ngừng dây chuyền sản xuất.")
W("user", "n", "ˈjuːzər", 2, "người dùng", "The app has over a million users.", "Ứng dụng có hơn một triệu người dùng.")
W("website", "n", "ˈwebsaɪt", 1, "trang web", "Visit our website for details.", "Hãy truy cập trang web của chúng tôi để biết chi tiết.")
W("browser", "n", "ˈbraʊzər", 3, "trình duyệt", "Open the link in your browser.", "Mở đường dẫn trong trình duyệt.")
W("attachment", "n", "əˈtætʃmənt", 3, "tệp đính kèm", "Please see the attachment for details.", "Vui lòng xem tệp đính kèm để biết chi tiết.", fam={"verb": "attach"})
W("artificial intelligence", "n", "ˌɑːrtɪˈfɪʃl ɪnˈtelɪdʒəns", 4, "trí tuệ nhân tạo (AI)", "Artificial intelligence can translate texts in seconds.", "Trí tuệ nhân tạo có thể dịch văn bản trong vài giây.")
W("innovation", "n", "ˌɪnəˈveɪʃn", 4, "sự đổi mới", "Innovation is the key to our success.", "Đổi mới là chìa khóa thành công của chúng tôi.")
W("digital", "adj", "ˈdɪdʒɪtl", 3, "kỹ thuật số", "Many companies are going digital.", "Nhiều công ty đang chuyển sang số hóa.")
W("access", "n", "ˈækses", 3, "quyền truy cập", "Only managers have access to this file.", "Chỉ quản lý có quyền truy cập tệp này.")
S("v", "truy cập", "You can access your account from any device.", "Bạn có thể truy cập tài khoản từ bất kỳ thiết bị nào.")
W("compatible", "adj", "kəmˈpætəbl", 5, "tương thích", "This charger is compatible with most phones.", "Bộ sạc này tương thích với hầu hết điện thoại.")
W("troubleshoot", "v", "ˈtrʌblʃuːt", 5, "khắc phục sự cố", "The IT team will troubleshoot the problem.", "Đội IT sẽ khắc phục sự cố.")
W("wireless", "adj", "ˈwaɪərləs", 3, "không dây", "The hotel offers free wireless internet.", "Khách sạn có internet không dây miễn phí.")

topic("health", "Y tế & bảo hiểm", "🩺", 3)
W("doctor", "n", "ˈdɑːktər", 1, "bác sĩ", "You should see a doctor.", "Bạn nên đi khám bác sĩ.")
W("appointment", "n", "əˈpɔɪntmənt", 2, "cuộc hẹn", "I have a dentist appointment at three.", "Tôi có hẹn nha sĩ lúc ba giờ.")
W("patient", "n", "ˈpeɪʃnt", 2, "bệnh nhân", "The nurse checked on the patient.", "Y tá kiểm tra tình trạng bệnh nhân.")
S("adj", "kiên nhẫn", "Be patient. The bus will come soon.", "Kiên nhẫn nhé. Xe buýt sẽ đến sớm thôi.")
W("symptom", "n", "ˈsɪmptəm", 3, "triệu chứng", "Fever is a common symptom of flu.", "Sốt là triệu chứng thường gặp của cúm.")
W("prescription", "n", "prɪˈskrɪpʃn", 4, "đơn thuốc", "You need a prescription for this medicine.", "Bạn cần đơn thuốc để mua loại thuốc này.", fam={"verb": "prescribe"})
W("pharmacy", "n", "ˈfɑːrməsi", 3, "nhà thuốc", "The pharmacy is open 24 hours.", "Nhà thuốc mở cửa 24 giờ.", fam={"noun": "pharmacist"})
W("medicine", "n", "ˈmedɪsn", 1, "thuốc", "Take this medicine twice a day.", "Uống thuốc này hai lần mỗi ngày.")
W("insurance", "n", "ɪnˈʃʊrəns", 3, "bảo hiểm", "Does your insurance cover dental care?", "Bảo hiểm của bạn có chi trả nha khoa không?", fam={"verb": "insure"})
W("treatment", "n", "ˈtriːtmənt", 3, "sự điều trị", "The treatment takes six weeks.", "Việc điều trị kéo dài sáu tuần.", fam={"verb": "treat"})
W("recover", "v", "rɪˈkʌvər", 3, "hồi phục", "She recovered quickly after the operation.", "Cô ấy hồi phục nhanh sau ca phẫu thuật.", fam={"noun": "recovery"})
W("injury", "n", "ˈɪndʒəri", 3, "chấn thương", "He missed the match because of a knee injury.", "Anh ấy lỡ trận đấu vì chấn thương đầu gối.", fam={"verb": "injure"})
W("headache", "n", "ˈhedeɪk", 1, "đau đầu", "I have a terrible headache.", "Tôi bị đau đầu kinh khủng.")
W("fever", "n", "ˈfiːvər", 2, "cơn sốt", "The child has a high fever.", "Đứa trẻ bị sốt cao.")
W("clinic", "n", "ˈklɪnɪk", 2, "phòng khám", "There is a small clinic near my house.", "Có một phòng khám nhỏ gần nhà tôi.")
W("surgery", "n", "ˈsɜːrdʒəri", 4, "phẫu thuật", "He needs surgery on his back.", "Anh ấy cần phẫu thuật lưng.", fam={"noun": "surgeon"})
W("emergency", "n", "ɪˈmɜːrdʒənsi", 3, "trường hợp khẩn cấp", "In an emergency, call 115.", "Trong trường hợp khẩn cấp, hãy gọi 115.")
W("nurse", "n", "nɜːrs", 1, "y tá", "The nurse gave me an injection.", "Y tá tiêm cho tôi một mũi.")
W("check-up", "n", "ˈtʃek ʌp", 3, "buổi khám sức khỏe định kỳ", "I go for a check-up every year.", "Tôi đi khám sức khỏe định kỳ mỗi năm.")
W("allergic", "adj", "əˈlɜːrdʒɪk", 4, "bị dị ứng", "I'm allergic to peanuts.", "Tôi bị dị ứng đậu phộng.", fam={"noun": "allergy"})
W("diet", "n", "ˈdaɪət", 2, "chế độ ăn", "A healthy diet includes lots of vegetables.", "Chế độ ăn lành mạnh có nhiều rau.")
W("exercise", "n", "ˈeksərsaɪz", 1, "sự tập thể dục; bài tập", "Regular exercise is good for your heart.", "Tập thể dục đều đặn tốt cho tim.")
S("v", "tập thể dục", "I exercise for 30 minutes every morning.", "Tôi tập thể dục 30 phút mỗi sáng.")
W("stress", "n", "stres", 2, "sự căng thẳng", "Too much work causes stress.", "Làm việc quá nhiều gây căng thẳng.", fam={"adj": "stressful"})
S("v", "nhấn mạnh", "The teacher stressed the importance of practice.", "Giáo viên nhấn mạnh tầm quan trọng của việc luyện tập.")
W("cure", "n", "kjʊr", 4, "phương thuốc chữa khỏi", "There is no cure for the common cold.", "Không có thuốc chữa khỏi cảm lạnh thông thường.")
W("cough", "n", "kɔːf", 2, "cơn ho", "He has a bad cough.", "Anh ấy bị ho nặng.")
W("vaccine", "n", "vækˈsiːn", 4, "vắc-xin", "The vaccine protects against flu.", "Vắc-xin giúp phòng cúm.")
W("claim", "n", "kleɪm", 4, "yêu cầu bồi thường", "You can file an insurance claim online.", "Bạn có thể nộp yêu cầu bồi thường bảo hiểm trực tuyến.")
S("v", "khẳng định (điều chưa chắc đúng)", "He claims that he saw a UFO.", "Anh ta khẳng định đã nhìn thấy UFO.")
W("coverage", "n", "ˈkʌvərɪdʒ", 5, "phạm vi bảo hiểm; sự đưa tin", "The policy offers full coverage for accidents.", "Hợp đồng bảo hiểm chi trả toàn bộ cho tai nạn.")
W("healthy", "adj", "ˈhelθi", 1, "khỏe mạnh, lành mạnh", "Eating fruit is healthy.", "Ăn trái cây rất tốt cho sức khỏe.")
W("well-being", "n", "ˌwel ˈbiːɪŋ", 4, "sự khỏe mạnh, hạnh phúc", "Sleep is important for your well-being.", "Giấc ngủ quan trọng với sức khỏe và tinh thần của bạn.")

topic("housing", "Bất động sản & nhà ở", "🏠", 4)
W("apartment", "n", "əˈpɑːrtmənt", 1, "căn hộ", "They live in a small apartment downtown.", "Họ sống trong một căn hộ nhỏ ở trung tâm.")
W("rent", "n", "rent", 2, "tiền thuê nhà", "The rent is due on the first of the month.", "Tiền thuê nhà phải trả vào ngày đầu tháng.")
S("v", "thuê", "We rented a car for the weekend.", "Chúng tôi thuê một chiếc xe cho cuối tuần.")
W("landlord", "n", "ˈlændlɔːrd", 3, "chủ nhà (cho thuê)", "Call the landlord if the heater breaks.", "Hãy gọi chủ nhà nếu máy sưởi hỏng.")
W("tenant", "n", "ˈtenənt", 4, "người thuê nhà", "The new tenants move in on Monday.", "Người thuê mới chuyển đến vào thứ Hai.")
W("lease", "n", "liːs", 4, "hợp đồng thuê", "We signed a one-year lease.", "Chúng tôi ký hợp đồng thuê một năm.")
W("real estate", "n", "ˈriːəl ɪsteɪt", 4, "bất động sản", "He works as a real estate agent.", "Anh ấy làm môi giới bất động sản.")
W("neighborhood", "n", "ˈneɪbərhʊd", 2, "khu phố", "This is a quiet neighborhood.", "Đây là một khu phố yên tĩnh.")
W("furniture", "n", "ˈfɜːrnɪtʃər", 2, "đồ nội thất", "We bought some new furniture for the living room.", "Chúng tôi mua đồ nội thất mới cho phòng khách.", fam={"adj": "furnished"})
W("renovate", "v", "ˈrenəveɪt", 4, "cải tạo, sửa sang", "They renovated the old house.", "Họ đã cải tạo căn nhà cũ.", fam={"noun": "renovation"})
W("utilities", "n", "juːˈtɪlətiz", 4, "các tiện ích (điện, nước, gas)", "The rent includes utilities.", "Tiền thuê đã bao gồm điện nước.")
W("move", "v", "muːv", 1, "di chuyển; chuyển nhà", "We moved to Da Nang last year.", "Chúng tôi chuyển đến Đà Nẵng năm ngoái.")
S("n", "nước đi, bước đi (quyết định)", "Learning English was a smart move.", "Học tiếng Anh là một bước đi khôn ngoan.")
W("spacious", "adj", "ˈspeɪʃəs", 4, "rộng rãi", "The kitchen is bright and spacious.", "Nhà bếp sáng sủa và rộng rãi.")
W("balcony", "n", "ˈbælkəni", 2, "ban công", "We have breakfast on the balcony.", "Chúng tôi ăn sáng ở ban công.")
W("garage", "n", "ɡəˈrɑːʒ", 2, "nhà để xe", "The car is in the garage.", "Xe đang ở trong nhà để xe.")
W("location", "n", "loʊˈkeɪʃn", 3, "vị trí", "The hotel is in a great location.", "Khách sạn ở vị trí tuyệt vời.", fam={"verb": "locate"})
W("deposit", "n", "dɪˈpɑːzɪt", 3, "tiền đặt cọc", "You must pay a deposit of one month's rent.", "Bạn phải đặt cọc một tháng tiền nhà.")
W("plumber", "n", "ˈplʌmər", 3, "thợ sửa ống nước", "We called a plumber to fix the leak.", "Chúng tôi gọi thợ đến sửa chỗ rò rỉ.")
W("leak", "n", "liːk", 3, "chỗ rò rỉ", "There's a leak in the roof.", "Mái nhà bị dột.")
W("property", "n", "ˈprɑːpərti", 3, "bất động sản", "Property prices in the city keep rising.", "Giá bất động sản trong thành phố liên tục tăng.")
W("residential", "adj", "ˌrezɪˈdenʃl", 4, "(thuộc) khu dân cư", "This is a residential area, so please drive slowly.", "Đây là khu dân cư, vui lòng lái chậm.", fam={"noun": "resident"})
W("roommate", "n", "ˈruːmmeɪt", 2, "bạn cùng phòng", "My roommate is from Japan.", "Bạn cùng phòng của tôi đến từ Nhật Bản.")
W("downtown", "adv", "ˌdaʊnˈtaʊn", 2, "ở/đến trung tâm thành phố", "I work downtown.", "Tôi làm việc ở trung tâm thành phố.")
W("suburb", "n", "ˈsʌbɜːrb", 3, "vùng ngoại ô", "They live in a quiet suburb.", "Họ sống ở một vùng ngoại ô yên tĩnh.")
W("own", "v", "oʊn", 2, "sở hữu", "They own two houses.", "Họ sở hữu hai căn nhà.", fam={"noun": "owner"})
S("adj", "của riêng (mình)", "I want my own room.", "Tôi muốn có phòng riêng.")
W("construction", "n", "kənˈstrʌkʃn", 3, "sự xây dựng", "The road is under construction.", "Con đường đang được thi công.", fam={"verb": "construct"})
W("brick", "n", "brɪk", 3, "gạch", "The house is made of red brick.", "Ngôi nhà được xây bằng gạch đỏ.")
W("ceiling", "n", "ˈsiːlɪŋ", 3, "trần nhà", "The ceiling is very high.", "Trần nhà rất cao.")
W("household", "n", "ˈhaʊshoʊld", 3, "hộ gia đình", "Most households have a washing machine.", "Hầu hết hộ gia đình đều có máy giặt.")
W("mortgage rate", "n", "ˈmɔːrɡɪdʒ reɪt", 5, "lãi suất vay mua nhà", "Mortgage rates fell this year.", "Lãi suất vay mua nhà đã giảm năm nay.")

topic("education", "Giáo dục & đào tạo", "🎓", 5)
W("student", "n", "ˈstuːdnt", 1, "học sinh, sinh viên", "She is a student at Hanoi University.", "Cô ấy là sinh viên Đại học Hà Nội.")
W("lesson", "n", "ˈlesn", 1, "bài học", "Today's lesson is about verbs.", "Bài học hôm nay về động từ.")
W("homework", "n", "ˈhoʊmwɜːrk", 1, "bài tập về nhà", "Did you finish your homework?", "Bạn làm xong bài tập về nhà chưa?")
W("exam", "n", "ɪɡˈzæm", 1, "kỳ thi", "I have an English exam tomorrow.", "Ngày mai tôi có bài thi tiếng Anh.")
W("degree", "n", "dɪˈɡriː", 3, "bằng cấp; độ", "She has a degree in economics.", "Cô ấy có bằng kinh tế.")
S("n", "độ (nhiệt độ, góc)", "It's 35 degrees today.", "Hôm nay trời 35 độ.")
W("graduate", "v", "ˈɡrædʒueɪt", 3, "tốt nghiệp", "He graduated from university in 2020.", "Anh ấy tốt nghiệp đại học năm 2020.", fam={"noun": "graduation"})
S("n", "người đã tốt nghiệp", "The company hires many new graduates.", "Công ty tuyển nhiều người mới tốt nghiệp.")
W("scholarship", "n", "ˈskɑːlərʃɪp", 3, "học bổng", "She won a scholarship to study in Australia.", "Cô ấy giành học bổng du học Úc.")
W("tuition", "n", "tuˈɪʃn", 4, "học phí", "Tuition fees are rising every year.", "Học phí tăng mỗi năm.")
W("certificate", "n", "sərˈtɪfɪkət", 3, "chứng chỉ", "You will get a certificate after the course.", "Bạn sẽ nhận chứng chỉ sau khóa học.")
W("course", "n", "kɔːrs", 2, "khóa học", "I'm taking an online English course.", "Tôi đang học một khóa tiếng Anh trực tuyến.")
S("phr", "of course: tất nhiên", "Of course I'll help you.", "Tất nhiên là tôi sẽ giúp bạn.")
W("lecture", "n", "ˈlektʃər", 3, "bài giảng", "The lecture lasts two hours.", "Bài giảng kéo dài hai tiếng.", fam={"noun": "lecturer"})
W("semester", "n", "sɪˈmestər", 3, "học kỳ", "The new semester starts in September.", "Học kỳ mới bắt đầu vào tháng Chín.")
W("assignment", "n", "əˈsaɪnmənt", 3, "bài tập (được giao)", "The assignment is due next Monday.", "Bài tập phải nộp vào thứ Hai tới.")
W("knowledge", "n", "ˈnɑːlɪdʒ", 3, "kiến thức", "Reading improves your general knowledge.", "Đọc sách giúp mở rộng kiến thức chung.")
W("skill", "n", "skɪl", 2, "kỹ năng", "Communication is an important skill.", "Giao tiếp là một kỹ năng quan trọng.", fam={"adj": "skillful"})
W("improve", "v", "ɪmˈpruːv", 2, "cải thiện", "I want to improve my speaking.", "Tôi muốn cải thiện kỹ năng nói.", fam={"noun": "improvement"})
W("memorize", "v", "ˈmeməraɪz", 3, "ghi nhớ, học thuộc", "It's hard to memorize long lists of words.", "Học thuộc danh sách từ dài rất khó.")
W("revise", "v", "rɪˈvaɪz", 3, "ôn tập (Anh-Anh); chỉnh sửa", "I need to revise for the test.", "Tôi cần ôn bài cho bài kiểm tra.")
W("fluent", "adj", "ˈfluːənt", 3, "trôi chảy", "She is fluent in three languages.", "Cô ấy nói trôi chảy ba thứ tiếng.", fam={"noun": "fluency", "adv": "fluently"})
W("vocabulary", "n", "voʊˈkæbjəleri", 2, "từ vựng", "Reading helps you build your vocabulary.", "Đọc giúp bạn tích lũy từ vựng.")
W("grammar", "n", "ˈɡræmər", 2, "ngữ pháp", "English grammar is not as hard as you think.", "Ngữ pháp tiếng Anh không khó như bạn nghĩ.")
W("pronunciation", "n", "prəˌnʌnsiˈeɪʃn", 3, "cách phát âm", "Her pronunciation is very clear.", "Phát âm của cô ấy rất rõ ràng.", fam={"verb": "pronounce"})
W("principal", "n", "ˈprɪnsəpl", 3, "hiệu trưởng", "The principal gave a speech at graduation.", "Hiệu trưởng phát biểu tại lễ tốt nghiệp.")
S("adj", "chính, chủ yếu", "The principal reason is cost.", "Lý do chính là chi phí.")
W("curriculum", "n", "kəˈrɪkjələm", 5, "chương trình giảng dạy", "English is part of the school curriculum.", "Tiếng Anh là một phần của chương trình học.")
W("enroll", "v", "ɪnˈroʊl", 4, "ghi danh, nhập học", "Over 200 students enrolled in the course.", "Hơn 200 học viên đã ghi danh khóa học.", fam={"noun": "enrollment"})
W("instructor", "n", "ɪnˈstrʌktər", 3, "người hướng dẫn, giảng viên", "Our yoga instructor is very patient.", "Giáo viên yoga của chúng tôi rất kiên nhẫn.", fam={"noun": "instruction"})
W("mark", "n", "mɑːrk", 2, "điểm số", "She got full marks on the test.", "Cô ấy đạt điểm tuyệt đối bài kiểm tra.")
S("v", "đánh dấu", "Mark the words you don't know.", "Đánh dấu những từ bạn chưa biết.")
W("motivated", "adj", "ˈmoʊtɪveɪtɪd", 3, "có động lực", "Small goals keep you motivated.", "Mục tiêu nhỏ giúp bạn giữ động lực.", fam={"noun": "motivation"})
W("practice", "n", "ˈpræktɪs", 1, "sự luyện tập", "Practice makes perfect.", "Có công mài sắt có ngày nên kim.")
S("v", "luyện tập", "I practice English every day.", "Tôi luyện tiếng Anh mỗi ngày.")

topic("environment", "Môi trường & năng lượng", "🌱", 6)
W("environment", "n", "ɪnˈvaɪrənmənt", 2, "môi trường", "We must protect the environment.", "Chúng ta phải bảo vệ môi trường.", fam={"adj": "environmental"})
W("pollution", "n", "pəˈluːʃn", 2, "sự ô nhiễm", "Air pollution is a big problem in many cities.", "Ô nhiễm không khí là vấn đề lớn ở nhiều thành phố.", fam={"verb": "pollute"})
W("recycle", "v", "ˌriːˈsaɪkl", 2, "tái chế", "We recycle paper and plastic.", "Chúng tôi tái chế giấy và nhựa.", fam={"noun": "recycling"})
W("waste", "n", "weɪst", 2, "rác thải; sự lãng phí", "Factories produce a lot of waste.", "Các nhà máy thải ra nhiều rác.")
S("v", "lãng phí", "Don't waste your time.", "Đừng lãng phí thời gian.")
W("climate change", "n", "ˈklaɪmət tʃeɪndʒ", 3, "biến đổi khí hậu", "Climate change affects everyone.", "Biến đổi khí hậu ảnh hưởng đến mọi người.")
W("renewable", "adj", "rɪˈnuːəbl", 4, "tái tạo được", "Solar power is a renewable energy source.", "Năng lượng mặt trời là nguồn năng lượng tái tạo.")
W("energy", "n", "ˈenərdʒi", 2, "năng lượng", "Turn off the lights to save energy.", "Tắt đèn để tiết kiệm năng lượng.")
W("solar", "adj", "ˈsoʊlər", 3, "(thuộc) mặt trời", "They put solar panels on the roof.", "Họ lắp tấm pin mặt trời trên mái nhà.")
W("emission", "n", "iˈmɪʃn", 5, "khí thải", "The city wants to cut carbon emissions.", "Thành phố muốn cắt giảm khí thải carbon.", fam={"verb": "emit"})
W("conserve", "v", "kənˈsɜːrv", 4, "bảo tồn, tiết kiệm", "Please conserve water during the dry season.", "Vui lòng tiết kiệm nước trong mùa khô.", fam={"noun": "conservation"})
W("sustainable", "adj", "səˈsteɪnəbl", 5, "bền vững", "We use sustainable materials.", "Chúng tôi dùng vật liệu bền vững.", fam={"noun": "sustainability"})
W("plastic", "n", "ˈplæstɪk", 1, "nhựa", "Plastic bags are bad for the ocean.", "Túi nhựa có hại cho đại dương.")
W("flood", "n", "flʌd", 2, "lũ lụt", "The flood destroyed many homes.", "Trận lũ phá hủy nhiều ngôi nhà.")
W("drought", "n", "draʊt", 4, "hạn hán", "The drought hurt the rice harvest.", "Hạn hán làm thiệt hại vụ lúa.")
W("wildlife", "n", "ˈwaɪldlaɪf", 3, "động vật hoang dã", "The park protects local wildlife.", "Công viên bảo vệ động vật hoang dã địa phương.")
W("species", "n", "ˈspiːʃiːz", 4, "loài", "Many species are in danger.", "Nhiều loài đang gặp nguy hiểm.")
W("endangered", "adj", "ɪnˈdeɪndʒərd", 4, "có nguy cơ tuyệt chủng", "The tiger is an endangered animal.", "Hổ là loài động vật có nguy cơ tuyệt chủng.")
W("fuel", "n", "fjuːəl", 3, "nhiên liệu", "Fuel prices went up again.", "Giá nhiên liệu lại tăng.")
W("reduce", "v", "rɪˈduːs", 2, "giảm", "We need to reduce plastic waste.", "Chúng ta cần giảm rác thải nhựa.", fam={"noun": "reduction"})
W("protect", "v", "prəˈtekt", 2, "bảo vệ", "Sunscreen protects your skin.", "Kem chống nắng bảo vệ da bạn.", fam={"noun": "protection"})
W("global warming", "n", "ˌɡloʊbl ˈwɔːrmɪŋ", 3, "sự nóng lên toàn cầu", "Global warming is melting the ice.", "Sự nóng lên toàn cầu đang làm băng tan.")
W("eco-friendly", "adj", "ˌiːkoʊ ˈfrendli", 3, "thân thiện với môi trường", "We sell eco-friendly bags.", "Chúng tôi bán túi thân thiện môi trường.")
W("resource", "n", "ˈriːsɔːrs", 3, "tài nguyên, nguồn lực", "Water is a precious resource.", "Nước là tài nguyên quý giá.")
W("electricity", "n", "ɪˌlekˈtrɪsəti", 2, "điện", "The storm cut off the electricity.", "Cơn bão làm mất điện.")
W("carbon footprint", "n", "ˈkɑːrbən ˈfʊtprɪnt", 5, "lượng khí thải carbon (của một người/hoạt động)", "Cycling to work reduces your carbon footprint.", "Đạp xe đi làm giúp giảm lượng khí thải carbon của bạn.")
W("disposable", "adj", "dɪˈspoʊzəbl", 4, "dùng một lần", "Avoid disposable cups.", "Tránh dùng cốc dùng một lần.", fam={"verb": "dispose"})
W("forest", "n", "ˈfɔːrɪst", 1, "rừng", "Forests are home to many animals.", "Rừng là nhà của nhiều loài động vật.")
W("organic", "adj", "ɔːrˈɡænɪk", 3, "hữu cơ", "This shop sells organic vegetables.", "Cửa hàng này bán rau hữu cơ.")
W("temperature", "n", "ˈtemprətʃər", 2, "nhiệt độ", "The temperature dropped at night.", "Nhiệt độ giảm vào ban đêm.")

topic("media", "Truyền thông & báo chí", "📰", 7)
W("news", "n", "nuːz", 1, "tin tức", "I read the news every morning.", "Tôi đọc tin tức mỗi sáng.")
W("article", "n", "ˈɑːrtɪkl", 2, "bài báo", "I read an interesting article about AI.", "Tôi đọc một bài báo thú vị về AI.")
S("n", "mạo từ (a, an, the)", "'The' is called the definite article.", "'The' được gọi là mạo từ xác định.")
W("journalist", "n", "ˈdʒɜːrnəlɪst", 3, "nhà báo", "The journalist interviewed the mayor.", "Nhà báo phỏng vấn thị trưởng.", fam={"noun": "journalism"})
W("headline", "n", "ˈhedlaɪn", 3, "tiêu đề (báo)", "The story made the headlines.", "Câu chuyện lên trang nhất.")
W("broadcast", "v", "ˈbrɔːdkæst", 4, "phát sóng", "The match will be broadcast live.", "Trận đấu sẽ được phát sóng trực tiếp.")
W("editor", "n", "ˈedɪtər", 3, "biên tập viên", "The editor checks every article.", "Biên tập viên kiểm tra mọi bài báo.", fam={"verb": "edit", "noun": "edition"})
W("publish", "v", "ˈpʌblɪʃ", 3, "xuất bản, đăng", "Her first book was published in 2019.", "Cuốn sách đầu tiên của cô ấy xuất bản năm 2019.", fam={"noun": "publisher"})
W("magazine", "n", "ˈmæɡəziːn", 1, "tạp chí", "I bought a fashion magazine.", "Tôi mua một cuốn tạp chí thời trang.")
W("report", "n", "rɪˈpɔːrt", 2, "báo cáo; bản tin", "The report was published yesterday.", "Báo cáo được công bố hôm qua.")
S("v", "báo cáo, đưa tin", "Please report any problems to the manager.", "Vui lòng báo mọi vấn đề cho quản lý.")
W("interview", "v", "ˈɪntərvjuː", 2, "phỏng vấn", "The TV station interviewed the winner.", "Đài truyền hình phỏng vấn người chiến thắng.")
W("press", "n", "pres", 3, "báo chí", "The minister spoke to the press.", "Bộ trưởng trả lời báo chí.", coll=["press release", "press conference"])
S("v", "nhấn", "Press the red button to stop.", "Nhấn nút đỏ để dừng.")
W("channel", "n", "ˈtʃænl", 2, "kênh", "Which channel is the film on?", "Bộ phim chiếu trên kênh nào?")
W("subscribe", "v", "səbˈskraɪb", 3, "đăng ký (theo dõi)", "Subscribe to our channel for new videos.", "Đăng ký kênh của chúng tôi để xem video mới.", fam={"noun": "subscription", "noun2": "subscriber"})
W("advertisement", "n", "ˌædvərˈtaɪzmənt", 3, "mẩu quảng cáo", "I saw an advertisement for the job.", "Tôi thấy quảng cáo tuyển dụng vị trí đó.")
W("source", "n", "sɔːrs", 3, "nguồn (tin)", "Always check the source of the news.", "Luôn kiểm tra nguồn tin.")
W("fake news", "n", "feɪk nuːz", 3, "tin giả", "Don't share fake news.", "Đừng chia sẻ tin giả.")
W("documentary", "n", "ˌdɑːkjuˈmentri", 4, "phim tài liệu", "We watched a documentary about the ocean.", "Chúng tôi xem phim tài liệu về đại dương.")
W("reporter", "n", "rɪˈpɔːrtər", 2, "phóng viên", "The reporter asked difficult questions.", "Phóng viên hỏi những câu khó.")
W("column", "n", "ˈkɑːləm", 4, "chuyên mục; cột", "She writes a weekly column on health.", "Cô ấy viết chuyên mục sức khỏe hàng tuần.")
W("issue", "n", "ˈɪʃuː", 3, "vấn đề; số (báo)", "The article discusses several important issues.", "Bài báo bàn về một số vấn đề quan trọng.")
S("v", "phát hành, cấp", "The bank will issue a new card.", "Ngân hàng sẽ cấp thẻ mới.")
W("coverage", "n", "ˈkʌvərɪdʒ", 5, "sự đưa tin", "The election got a lot of media coverage.", "Cuộc bầu cử được truyền thông đưa tin rộng rãi.")
W("viral", "adj", "ˈvaɪrəl", 3, "lan truyền mạnh (trên mạng)", "The video went viral overnight.", "Video lan truyền chóng mặt chỉ sau một đêm.")
W("podcast", "n", "ˈpɑːdkæst", 3, "chương trình âm thanh trực tuyến", "I listen to an English podcast on the bus.", "Tôi nghe podcast tiếng Anh trên xe buýt.")
W("audience", "n", "ˈɔːdiəns", 3, "khán thính giả", "The show has a young audience.", "Chương trình có khán giả trẻ.")
W("announcement", "n", "əˈnaʊnsmənt", 3, "thông báo", "The company made an important announcement.", "Công ty đưa ra một thông báo quan trọng.")
W("censor", "v", "ˈsensər", 5, "kiểm duyệt", "Some scenes were censored.", "Một số cảnh đã bị kiểm duyệt.")
W("trending", "adj", "ˈtrendɪŋ", 3, "đang thịnh hành", "This song is trending on social media.", "Bài hát này đang thịnh hành trên mạng xã hội.")
W("live", "adj", "laɪv", 2, "trực tiếp", "The concert is live on TV.", "Buổi hòa nhạc phát trực tiếp trên TV.")

topic("daily", "Đời sống hàng ngày", "☀️", 8)
W("wake up", "phr", "weɪk ʌp", 1, "thức dậy", "I wake up at six every day.", "Tôi thức dậy lúc sáu giờ mỗi ngày.")
W("breakfast", "n", "ˈbrekfəst", 1, "bữa sáng", "What did you have for breakfast?", "Bạn ăn gì vào bữa sáng?")
W("commute", "n", "kəˈmjuːt", 4, "quãng đường đi làm", "My commute takes 40 minutes.", "Tôi mất 40 phút để đi làm.")
W("grocery", "n", "ˈɡroʊsəri", 2, "đồ tạp hóa", "I go grocery shopping on Sundays.", "Tôi đi mua đồ tạp hóa vào Chủ nhật.")
W("laundry", "n", "ˈlɔːndri", 2, "việc giặt giũ; đồ giặt", "I do the laundry on weekends.", "Tôi giặt đồ vào cuối tuần.")
W("chore", "n", "tʃɔːr", 3, "việc nhà", "We share the household chores.", "Chúng tôi chia nhau làm việc nhà.")
W("habit", "n", "ˈhæbɪt", 2, "thói quen", "Reading before bed is a good habit.", "Đọc sách trước khi ngủ là thói quen tốt.")
W("routine", "n", "ruːˈtiːn", 3, "thói quen hằng ngày", "Exercise is part of my daily routine.", "Tập thể dục là một phần thói quen hằng ngày của tôi.")
W("neighbor", "n", "ˈneɪbər", 1, "hàng xóm", "Our neighbors are very friendly.", "Hàng xóm của chúng tôi rất thân thiện.")
W("weekend", "n", "ˌwiːkˈend", 1, "cuối tuần", "What are you doing this weekend?", "Cuối tuần này bạn làm gì?")
W("hobby", "n", "ˈhɑːbi", 1, "sở thích", "My hobby is taking photos.", "Sở thích của tôi là chụp ảnh.")
W("relax", "v", "rɪˈlæks", 1, "thư giãn", "I relax by listening to music.", "Tôi thư giãn bằng cách nghe nhạc.")
W("busy", "adj", "ˈbɪzi", 1, "bận rộn", "I'm too busy to talk right now.", "Bây giờ tôi bận quá không nói chuyện được.")
W("tired", "adj", "ˈtaɪərd", 1, "mệt", "I'm tired after a long day.", "Tôi mệt sau một ngày dài.")
W("borrow", "v", "ˈbɑːroʊ", 2, "mượn", "Can I borrow your umbrella?", "Tôi mượn ô của bạn được không?")
W("appointment", "n", "əˈpɔɪntmənt", 2, "cuộc hẹn", "I made an appointment with the hairdresser.", "Tôi đã hẹn với thợ làm tóc.")
W("errand", "n", "ˈerənd", 4, "việc vặt (phải ra ngoài làm)", "I have a few errands to run this afternoon.", "Chiều nay tôi có vài việc vặt phải làm.")
W("hang out", "phr", "hæŋ aʊt", 2, "đi chơi, tụ tập", "We often hang out at the coffee shop.", "Chúng tôi hay tụ tập ở quán cà phê.")
W("take a nap", "phr", "teɪk ə næp", 2, "chợp mắt", "I usually take a nap after lunch.", "Tôi thường chợp mắt sau bữa trưa.")
W("dishes", "n", "ˈdɪʃɪz", 1, "bát đĩa", "It's your turn to do the dishes.", "Đến lượt bạn rửa bát rồi.")
W("bill", "n", "bɪl", 1, "hóa đơn", "I pay the electricity bill online.", "Tôi thanh toán hóa đơn điện trực tuyến.")
W("fridge", "n", "frɪdʒ", 1, "tủ lạnh", "Put the milk in the fridge.", "Cất sữa vào tủ lạnh.")
W("alarm", "n", "əˈlɑːrm", 2, "chuông báo thức; báo động", "My alarm didn't go off this morning.", "Sáng nay chuông báo thức của tôi không kêu.")
W("schedule", "n", "ˈskedʒuːl", 2, "lịch", "My schedule is full this week.", "Lịch của tôi tuần này kín rồi.")
W("traffic", "n", "ˈtræfɪk", 1, "giao thông", "The traffic is terrible at 5 p.m.", "Giao thông lúc 5 giờ chiều rất tệ.")
W("on time", "phr", "ɑːn taɪm", 1, "đúng giờ", "Please be on time for class.", "Vui lòng đến lớp đúng giờ.")
W("in a hurry", "phr", "ɪn ə ˈhɜːri", 2, "vội vàng", "Sorry, I'm in a hurry.", "Xin lỗi, tôi đang vội.")
W("get along with", "phr", "ɡet əˈlɔːŋ wɪð", 3, "hòa hợp với", "I get along well with my roommate.", "Tôi rất hợp với bạn cùng phòng.")
W("look after", "phr", "lʊk ˈæftər", 2, "chăm sóc", "Can you look after my cat this weekend?", "Bạn chăm mèo giúp tôi cuối tuần này được không?")
W("run out of", "phr", "rʌn aʊt əv", 3, "hết, cạn", "We've run out of coffee.", "Chúng ta hết cà phê rồi.")

topic("academic", "Học thuật cơ bản", "📚", 9)
W("analyze", "v", "ˈænəlaɪz", 4, "phân tích", "Scientists analyzed the data carefully.", "Các nhà khoa học đã phân tích dữ liệu cẩn thận.", fam={"noun": "analysis"})
W("theory", "n", "ˈθɪəri", 3, "lý thuyết", "In theory, the plan should work.", "Về lý thuyết, kế hoạch sẽ hiệu quả.")
W("hypothesis", "n", "haɪˈpɑːθəsɪs", 5, "giả thuyết", "The experiment tested the hypothesis.", "Thí nghiệm kiểm tra giả thuyết.")
W("evidence", "n", "ˈevɪdəns", 3, "bằng chứng", "There is strong evidence that exercise reduces stress.", "Có bằng chứng rõ ràng rằng tập thể dục giảm căng thẳng.")
W("conclusion", "n", "kənˈkluːʒn", 3, "kết luận", "What conclusion can we draw from this?", "Chúng ta rút ra kết luận gì từ điều này?", fam={"verb": "conclude"})
W("significant", "adj", "sɪɡˈnɪfɪkənt", 4, "đáng kể, quan trọng", "There was a significant increase in sales.", "Doanh số tăng đáng kể.", fam={"noun": "significance", "adv": "significantly"})
W("method", "n", "ˈmeθəd", 3, "phương pháp", "This is a simple method for learning words.", "Đây là một phương pháp học từ đơn giản.")
W("approach", "n", "əˈproʊtʃ", 4, "cách tiếp cận", "We need a new approach to the problem.", "Chúng ta cần cách tiếp cận mới cho vấn đề.")
S("v", "tiến lại gần; tiếp cận", "A man approached me and asked for directions.", "Một người đàn ông lại gần hỏi đường tôi.")
W("factor", "n", "ˈfæktər", 3, "yếu tố", "Price is an important factor for buyers.", "Giá là yếu tố quan trọng với người mua.")
W("affect", "v", "əˈfekt", 3, "ảnh hưởng đến", "Lack of sleep affects your memory.", "Thiếu ngủ ảnh hưởng đến trí nhớ của bạn.")
W("effect", "n", "ɪˈfekt", 3, "tác động, hiệu quả", "The medicine had no effect.", "Thuốc không có tác dụng.", fam={"adj": "effective"})
W("define", "v", "dɪˈfaɪn", 3, "định nghĩa", "How would you define success?", "Bạn định nghĩa thành công như thế nào?", fam={"noun": "definition"})
W("summary", "n", "ˈsʌməri", 3, "bản tóm tắt", "Write a short summary of the article.", "Viết một đoạn tóm tắt ngắn về bài báo.", fam={"verb": "summarize"})
W("percentage", "n", "pərˈsentɪdʒ", 3, "tỷ lệ phần trăm", "A large percentage of students passed.", "Một tỷ lệ lớn học sinh đã đỗ.")
W("chart", "n", "tʃɑːrt", 2, "biểu đồ", "The chart shows sales by month.", "Biểu đồ thể hiện doanh số theo tháng.")
W("research", "v", "rɪˈsɜːrtʃ", 3, "nghiên cứu", "She is researching the history of Hue.", "Cô ấy đang nghiên cứu lịch sử Huế.", fam={"noun": "researcher"})
W("experiment", "n", "ɪkˈsperɪmənt", 3, "thí nghiệm", "We did an experiment in the lab.", "Chúng tôi làm thí nghiệm trong phòng lab.")
W("argument", "n", "ˈɑːrɡjumənt", 3, "lập luận; cuộc tranh cãi", "Her argument is clear and logical.", "Lập luận của cô ấy rõ ràng và logic.", fam={"verb": "argue"})
W("assume", "v", "əˈsuːm", 4, "cho rằng, giả định", "I assume you've read the report.", "Tôi cho rằng bạn đã đọc báo cáo.", fam={"noun": "assumption"})
W("indicate", "v", "ˈɪndɪkeɪt", 4, "chỉ ra, cho thấy", "The results indicate a clear trend.", "Kết quả cho thấy một xu hướng rõ ràng.", fam={"noun": "indication"})
W("contrast", "n", "ˈkɑːntræst", 4, "sự tương phản", "In contrast, prices in the countryside are low.", "Ngược lại, giá ở nông thôn thấp.")
W("previous", "adj", "ˈpriːviəs", 3, "trước đó", "The previous owner painted the house blue.", "Chủ cũ đã sơn ngôi nhà màu xanh.", fam={"adv": "previously"})
W("approximately", "adv", "əˈprɑːksɪmətli", 4, "xấp xỉ", "The trip takes approximately three hours.", "Chuyến đi mất xấp xỉ ba giờ.")
W("compare", "v", "kəmˈper", 2, "so sánh", "Compare the two charts.", "So sánh hai biểu đồ.")
W("consequence", "n", "ˈkɑːnsəkwens", 4, "hậu quả", "Think about the consequences before you act.", "Hãy nghĩ đến hậu quả trước khi hành động.")
W("crucial", "adj", "ˈkruːʃl", 4, "cực kỳ quan trọng", "Sleep is crucial for learning.", "Giấc ngủ cực kỳ quan trọng cho việc học.")
W("demonstrate", "v", "ˈdemənstreɪt", 4, "chứng minh; trình bày", "The study demonstrates the value of practice.", "Nghiên cứu chứng minh giá trị của việc luyện tập.", fam={"noun": "demonstration"})
W("interpret", "v", "ɪnˈtɜːrprɪt", 5, "diễn giải; phiên dịch", "How do you interpret these results?", "Bạn diễn giải những kết quả này như thế nào?", fam={"noun": "interpretation", "noun2": "interpreter"})
W("relevant", "adj", "ˈreləvənt", 4, "liên quan, thích hợp", "Only include relevant information.", "Chỉ đưa vào thông tin liên quan.", fam={"adj2": "irrelevant"})
W("whereas", "conj", "werˈæz", 5, "trong khi (đối lập)", "Some students like grammar, whereas others prefer speaking.", "Một số học sinh thích ngữ pháp, trong khi số khác thích nói.")
